### ISSUE TITLE
[BUG]Login problem

### ISSUE THREAD

**Issue by Yan19960220** [adw0rd/instagrapi#1037]
### Compensate with donations ($15 and more) for the time I spent to fix problems or send me your [Pull Request](https://github.com/adw0rd/instagrapi/pulls) with fixes

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

* Tron TRX/USDT: `TLprxuzHjXPkHYa7ZfTTt165p7Fphwy1Ee`
* Bitcoin: `bc1qmp7538hktvg2gx994hrpkmsmyjc03q29awe9ra`
* Ethereum: `0x0E674815d513d4a00F6a7Cd4A990807aB97cC70D`
* Dogecoin: `DSEXzMBYhBTwhNqzPGxVWFsTqVsTCeDejo`

**Describe the bug**
I have followed the instruction to change my proxy for a while. But recently I always meet one error when I tried to login in my account.

The username you entered doesn't appear to belong to an account. Please check your username and try again.

I am sure that my accounts work well. 

**Traceback**
Status 429: Too many requests
Ignore 429: Continue login
Traceback (most recent call last):
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yanzhang/Projects/work/ins/ins/setting/loggin.py", line 81, in login
    if not self.cl.login(self.user_name, self.passwd, relogin=False):
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/auth.py", line 391, in login
    logged = self.private_request("accounts/login/", data, login=True)
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 447, in private_request
    raise e
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 434, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 354, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: The username you entered doesn't appear to belong to an account. Please check your username and try again.

**Expected behavior**
Sometimes I can login successfully. It is very strange the next time will be prevented.

**Comment by adw0rd** [comment]
> The username you entered doesn't appear to belong to an account. Please check your username and try again.

This error says only one thing - you have bad proxies
