### ISSUE TITLE
[BUG] Challenger not working

### ISSUE THREAD

**Issue by h4ng3r** [adw0rd/instagrapi#1041]
**Describe the bug**

I implemented the challenge following the example:
```
insta = Client()
insta.challenge_code_handler = challenge_code_handler
insta.change_password_handler = change_password_handler
nsta.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)
```
But the "challenge_code_handler" is not being called and I'm getting a ChallengeRequired exception. 

**To Reproduce**
Just run the example code with an account that requires email challenge.

**Traceback**
```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 302, in _send_private_request
    response.raise_for_status()
  File "/home/pi/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/reels_tray/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 438, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 334, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 302, in _send_private_request
    response.raise_for_status()
  File "/home/pi/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/reels_tray/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/instagram/main.py", line 110, in <module>
    main()
  File "/home/pi/instagram/main.py", line 70, in main
    if insta.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD) == False:
  File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/auth.py", line 417, in login
    self.login_flow()
  File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/auth.py", line 167, in login_flow
    check_flow.append(self.get_reels_tray_feed("cold_start"))
  File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/auth.py", line 244, in get_reels_tray_feed
    return self.private_request("feed/reels_tray/", data)
  File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 455, in private_request
    return self._send_private_request(endpoint, **kwargs)
  File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 334, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required
```

**Expected behavior**
According to documentation and the example the "challenge_code_handler" function should be called when IG requests a challenge.

**Desktop (please complete the following information):**
 - OS: Raspbian 10
 - Python version 3.10.2
 - instagrapi version 1.16.30

Thanks,

**Comment by RogerVFbr** [comment]
I'm getting an error when issuing "hashtag_info", seems to be related:
`
ChallengeResolve: Unknown step_name "submit_phone" for "factsaboutus022" in challenge resolver: {'step_name': 'submit_phone', 'step_data': {'phone_number': 'None'}, 'flow_render_type': 3, 'bloks_action': 'com.instagram.challenge.navigation.take_challenge', 'cni': 17845117700910164, 'challenge_context': '{"step_name": "submit_phone", "cni": 17845117700910164, "is_stateless": false, "challenge_type_enum": "SMS", "present_as_modal": false}', 'challenge_type_enum_str': 'SMS', 'status': 'ok'}
`

**Comment by jstchw** [comment]
> **Describe the bug**
> 
> I implemented the challenge following the example:
> 
> ```
> insta = Client()
> insta.challenge_code_handler = challenge_code_handler
> insta.change_password_handler = change_password_handler
> nsta.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)
> ```
> 
> But the "challenge_code_handler" is not being called and I'm getting a ChallengeRequired exception.
> 
> **To Reproduce** Just run the example code with an account that requires email challenge.
> 
> **Traceback**
> 
> ```
> Traceback (most recent call last):
>   File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 302, in _send_private_request
>     response.raise_for_status()
>   File "/home/pi/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/reels_tray/
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 438, in private_request
>     self._send_private_request(endpoint, **kwargs)
>   File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 334, in _send_private_request
>     raise ChallengeRequired(**last_json)
> instagrapi.exceptions.ChallengeRequired: challenge_required
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 302, in _send_private_request
>     response.raise_for_status()
>   File "/home/pi/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/reels_tray/
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/pi/instagram/main.py", line 110, in <module>
>     main()
>   File "/home/pi/instagram/main.py", line 70, in main
>     if insta.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD) == False:
>   File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/auth.py", line 417, in login
>     self.login_flow()
>   File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/auth.py", line 167, in login_flow
>     check_flow.append(self.get_reels_tray_feed("cold_start"))
>   File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/auth.py", line 244, in get_reels_tray_feed
>     return self.private_request("feed/reels_tray/", data)
>   File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 455, in private_request
>     return self._send_private_request(endpoint, **kwargs)
>   File "/home/pi/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 334, in _send_private_request
>     raise ChallengeRequired(**last_json)
> instagrapi.exceptions.ChallengeRequired: challenge_required
> ```
> 
> **Expected behavior** According to documentation and the example the "challenge_code_handler" function should be called when IG requests a challenge.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Raspbian 10
> * Python version 3.10.2
> * instagrapi version 1.16.30
> 
> Thanks,

Having exactly the same issue, any resolution?

**Comment by adw0rd** [comment]
@jstchw we are waiting for a decision from the community, you can help the project and send me a PR

**Comment by nebula0225** [comment]
same for me
don't work
How to call ChallengeChoice ?

**Comment by adw0rd** [comment]
@nebula0225 what do you mean? Please provide examples of usage

**Comment by nebula0225** [comment]
I have a account that need have to solve challenge 
When i try login using that didn't go "challenge_code_handler"
It just throw error "challenge_required"

**Comment by adw0rd** [comment]
@nebula0225 so what's the question? So that you don't define parameters, according to the documentation?

https://adw0rd.github.io/instagrapi/usage-guide/challenge_resolver.html

**Comment by nebula0225** [comment]
@adw0rd
No, The code above is just an example
In fact, I worked by referring to that document.
I think there are accounts where the challenge doesn't work.
The account I tried did not have email and SMS information registered.

**Comment by adw0rd** [comment]
If you reproduce this issue, then you can send your fixes in the form of a PR, or give me access to the instagram account username, password, proxy and mail access to get the code from isntagram.

Without this, I can't reproduce the problem.

My accounts work fine with the current challenge resolver

**Comment by EchterAlsFake** [comment]
Hey Guys,

I am facing the same Issue, but I have some new information.

When I try to do the challenge resolve stuff with a little test script

```from instagrapi.mixins.challenge import ChallengeChoice
from instagrapi import Client

IG_USERNAME = "username..."
IG_PASSWORD = 'pass...'

def get_code_from_email(username):
    return input("Code lol:")

def get_code_from_sms(username):
    return input("Code lol:")



def challenge_code_handler(username, choice):
    if choice == ChallengeChoice.SMS:
        return get_code_from_sms(username)
    elif choice == ChallengeChoice.EMAIL:
        return get_code_from_email(username)
    return False

cl = Client()
cl.challenge_code_handler = challenge_code_handler
cl.login(IG_USERNAME, IG_PASSWORD)

```

the SMS code actually shows up on my phone. Seems like the API request for the challenge is working, but at some point there is an issue.


I think, the Issue is here:

Traceback (most recent call last):
  File "/home/asuna/PycharmProjects/Osintgram2/venv/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 360, in _send_private_request
    response.raise_for_status()
  File "/home/asuna/PycharmProjects/Osintgram2/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/
 

because when I go to this URL, I get a HTTP 405 Error.


If you need my account credentials to reproduce the error, I can send them to you.
I tested the script on 2 Accounts.


Hope that helps a little bit.

Thanks :)

**Comment by AndydeCleyre** [comment]
Also each time this happens, I get the usual email alert that there has been a new login detected, and that security and account settings will be limited for a few days.

So as far as Instagram is concerned, the login is successful. But the client object fails to reach a logged in state.

**Comment by subzeroid** [comment]
Current triage note after rechecking the challenge resolver on `master` / `instagrapi 2.9.1`:

`challenge_code_handler` is only called after Instagram returns an actual code-verification step, for example `verify_email`, `verify_sms`, `verify_phone`, `select_verify_method`, or contact-point recovery.

The recent traceback in this issue shows a post-login `feed/reels_tray/` request returning a generic checkpoint envelope:

```python
{"message": "challenge_required", "challenge": {"api_path": "/challenge/", "flow_render_type": 0}, "status": "fail"}
```

That payload does not yet identify an email/SMS code step, so there may be no code for `challenge_code_handler` to request. In that case the resolver can only attempt to open the challenge endpoint; if Instagram keeps returning a manual checkpoint, it has to be resolved in the official app/web flow and retried with the same saved settings/device/proxy.

I also re-ran the focused regression coverage for supported resolver paths:

```text
test_challenge_resolve_simple_fails_fast_when_handler_has_no_code
test_challenge_resolve_simple_select_verify_method_uses_sms_choice_for_code
test_challenge_resolve_simple_submit_phone_posts_number_then_sms_code
test_challenge_resolve_simple_bloks_redirect_step_raises_clear_manual_error

4 passed
```

Leaving this open for now, but to make it actionable we need a sanitized current `last_json` from `instagrapi >= 2.9.1` after the resolver opens `/challenge/` and before it retries the original endpoint. The useful fields are `step_name`, `challengeType`, `bloks_action`, `challenge_type_enum_str`, `challenge.api_path`, and `status`; credentials, tokens, contact points, and user IDs should be redacted.

**Comment by subzeroid** [comment]
Keeping this open and marking it as waiting for current data.

I rechecked the current resolver coverage on `master`: `tests/regression/test_challenge.py` is green (`31 passed`). The supported email/SMS/select-method/submit-phone/manual-Bloks paths are covered.

The remaining unresolved case is the generic post-login checkpoint where Instagram returns `challenge_required` for something like `feed/reels_tray/` before exposing a concrete code-verification `step_name`. In that state `challenge_code_handler` should not be called yet, because there is no email/SMS code step to request.

Still needed for a code fix: sanitized current `last_json` from the failing account after `challenge_resolve(...)` opens the challenge endpoint, including `step_name`, `challengeType`, `bloks_action`, `challenge_type_enum_str`, `challenge.api_path`, and `status` with tokens/contact points/user IDs redacted.

**Comment by subzeroid** [comment]
Closing as cannot reproduce on current versions. The current challenge resolver regression coverage is green, and the remaining reports describe account/session-specific checkpoints where Instagram does not expose an actionable email/SMS verification step for `challenge_code_handler`.

If this still happens on the latest release, please open a fresh focused issue with details from an account where it can be reproduced: exact instagrapi version, Python version, sanitized `last_json` after `challenge_resolve(...)` opens the challenge endpoint, whether the same account can pass the checkpoint in the official app/web, and enough account/proxy/session context for maintainers to reproduce privately if needed. Redact credentials, tokens, contact points, and user IDs from public logs.
