### ISSUE TITLE
[BUG] 2FA login issue

### ISSUE THREAD

**Issue by akirajay** [adw0rd/instagrapi#1042]
Is there someone faced this error while using verification_code

inst.login(username=args.user, password=args.userpwd, verification_code='27605381')

error is 

 File "C:\Python311\Lib\site-packages\requests-2.28.1-py3.11.egg\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
**requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/two_factor_login/**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\My Drive\Coding\workspace\NewInstProject\instCampaignBot.py", line 76, in <module>
    inst.login(username=args.user, password=args.userpwd, verification_code='27605381')
  File "C:\Python311\Lib\site-packages\instapy2\instapy2_base.py", line 92, in login
    logged_in = self.session.login(username=username, password=password, verification_code=verification_code)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\instagrapi-1.16.30-py3.11.egg\instagrapi\mixins\auth.py", line 412, in login
    logged = self.private_request("accounts/two_factor_login/", data, login=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\instagrapi-1.16.30-py3.11.egg\instagrapi\mixins\private.py", line 451, in private_request
    raise e
  File "C:\Python311\Lib\site-packages\instagrapi-1.16.30-py3.11.egg\instagrapi\mixins\private.py", line 438, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Python311\Lib\site-packages\instagrapi-1.16.30-py3.11.egg\instagrapi\mixins\private.py", line 358, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: Please check the security code and try again.

**Comment by philwillnyc** [comment]
I'm getting an identical error.

**Comment by LUCIAWEN** [comment]
Listen what they do now is come telling you how helpful this or that man helped them recover their accounts or hack anything, i fell for those lies 5 times before i stumbled into the only legit man online Mr Bohdan who we worked through bohdanbohdan93 @ mail . ru doing this to save any victim out there please be careful anyone different from him is another possible fake my friend

**Comment by regulad** [comment]
I am having the same problem as of February 17, 2023. The endpoint seems to have changed somehow.

**Comment by regulad** [comment]
@adw0rd would you consider fixing this the next time you check the Private API?

**Comment by adw0rd** [comment]
@regulad I will gladly accept your fixes as PR if you take the time to do so

**Comment by subzeroid** [comment]
Current releases include the documented 2FA login path and newer Bloks two-factor helpers.

Docs: https://subzeroid.github.io/instagrapi/usage-guide/totp

Closing this old 2FA report as covered by the current API.
