### ISSUE TITLE
[BUG] HTTPError: 400 Client Error: Bad Request 

### ISSUE THREAD

**Issue by Yqno** [adw0rd/instagrapi#1047]
**Describe the bug**
I Can't log in with my code-server (Docker) on any Instagram account that I have 

**To Reproduce**
username = input("Username: ")
password = input("Password: ")

client = Client()
client.login(username, password)

**Traceback**
Status 429: Too many requests
Ignore 429: Continue login
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 302, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/codec/mounts/vscode/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/codec/mounts/vscode/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/codec/mounts/vscode/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/codec/mounts/vscode/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/codec/mounts/vscode/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/codec/mounts/vscode/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/codec/workspace/Python/InstagramBot V4.py", line 27, in <module>
    client.login(username, password)
  File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/auth.py", line 390, in login
    logged = self.private_request("accounts/login/", data, login=True)
  File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 451, in private_request
    raise e
  File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 438, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 358, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: The username you entered doesn't appear to belong to an account. Please check your username and try again.

**Expected behavior**
a Login

**Desktop (please complete the following information):**
 - OS: ubuntu jammy InRelease (Latest Docker image)
 - Python version: 3.10.6
 - instagrapi version: 1.16.30

**Additional context**

**Comment by adw0rd** [comment]
https://github.com/adw0rd/instagrapi/issues?q=The+username+you+entered
