### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Laura-Ag** [adw0rd/instagrapi#1050]
Hello,

it seems that my code stacks on this line user_followings = API.user_following(user_id, 0) and I get the following error.. Any ideas on what's going on?

int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\user.py", line 189, in user_info_by_username
    user = self.user_info_by_username_gql(username)
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\user.py", line 142, in user_info_by_username_gql
    return extract_user_gql(self.public_a1_request(f"/{username!s}/")["user"])
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\public.py", line 173, in public_a1_request
    response = self.public_request(
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\public.py", line 72, in public_request
    return self._send_public_request(url, **kwargs)
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\public.py", line 106, in _send_public_request
    expected_length = int(response.headers.get("Content-Length"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "c:\Users\laura\Desktop\Διάφορα\Workspace\InstaSpector\main.py", line 27, in <module>
    user_followings = API.user_following(user_id, 0)
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\user.py", line 550, in user_following
    users = self.user_following_v1(user_id, amount)
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\user.py", line 509, in user_following_v1
    result = self.private_request(f"friendships/{user_id}/following/", params=params)
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\private.py", line 268, in _send_private_request
    time.sleep(self.request_timeout)

**Comment by insolitum** [comment]
Share the code (or snippet where instagrapi is used)

**Comment by Laura-Ag** [comment]
Hello, 

here is my code:
```
from instagrapi import Client

API = Client()

USERNAME = 'username'
PASSWORD = 'password'

def init_user():
    try:
        print('Logging in...')
        API.login(USERNAME, PASSWORD)
        print('Logged in successfully!\n')

        print('Getting user info...')
        user_id = API.user_id_from_username(USERNAME)
        print('User ID:', user_id)

        user_followings = API.user_following(user_id, 0)
        
        print('Done!\n')

        return user_followings

    except Exception as error:
        print('\nSomething went wrong:', error)
        print('\nExiting script...\n')
        sys.exit()
```


Terminal Output:
```Logging in...
Logged in successfully!

Getting user info...
User ID: XXXXXXXXX

Something went wrong: login_required
```

**Comment by adw0rd** [comment]
@Laura-Ag try using `user_following_v1` instead of `user_following`

**Comment by Laura-Ag** [comment]
Hello @adw0rd and thank you for your answer. 
I used ```user_following_v1``` but it didn't work either.

**Comment by official-antique** [comment]
@Laura-Ag Can you print the return from API.login(...)? Could be that it's not actually logged in.

Do you have email or any other 2FA enabled on the account?

**Comment by insolitum** [comment]
Can you share the traceback of the exception? And are you using the latest version of instagrapi?

**Comment by Laura-Ag** [comment]
Hello @insolitum!
Yes I am using the latest version.
 
Here is the traceback
```Traceback (most recent call last):
  File "C:\Users\....\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\private.py", line 302, in _send_private_request
    response.raise_for_status()
  File "C:\Users\....\Programs\Python\Python39-32\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/friendships/xxxxxxxxxx/following/?rank_token=xxxxxxxxxx_5cceb876-8ab2-4332-9ee9-2d0d54604e95&search_surface=follow_list_page&includes_hashtags=true&enable_groups=true&query=&count=10000&max_id=4000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\....\instaspector.py", line 89, in <module>
    user_followings = init_user()
  File "c:\Users\....\InstaSpector\instaspector.py", line 27, in init_user
    user_followings = API.user_following_v1(user_id, 0)
  File "C:\Users\....\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\user.py", line 552, in user_following_v1
    result = self.private_request(f"friendships/{user_id}/following/", params=params)
  File "C:\Users\....\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\private.py", line 451, in private_request
    raise e
  File "C:\Users\....\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\private.py", line 438, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\....\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\private.py", line 327, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required

**Comment by Laura-Ag** [comment]
Hello, any ideas guys?

**Comment by bueroingleuering** [comment]
I have the same problem. `user_followers`works, but `user_following`is not working, since I got an exception: 
**instagrapi.exceptions.LoginRequired: login_required**

code:
`cl = Client()`
`cl.login(username="Insta_account", password="insta_password")`
`follower = cl.user_followers(user_id=cl.user_id) `
`following = cl.user_following(user_id=cl.user_id)`

Trace:
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/friendships/xxxxxxx/following/?max_id=&count=10000&rank_token=xxxxxxx_51a0f7a3-1955-40b8-985e-86af526efdf5&search_surface=follow_list_page&query=&enable_groups=true

**Comment by adw0rd** [comment]
@Laura-Ag @bueroingleuering try `cl.user_following_gql` or https://api.lamadava.com/docs

**Comment by isakurbanov744** [comment]
Please provide with updates for solutions.

**Comment by Laura-Ag** [comment]
Neither cl.user_following_gql works.

**Comment by Laura-Ag** [comment]
Any other ideas, please?

**Comment by adw0rd** [comment]
`cl.user_following_v1`?

**Comment by isakurbanov744** [comment]
Doesn't work for me, even if it works, I can't retrieve all of the followings.

**Comment by claell** [comment]
Probably unrelated, but I have problems as well:
`instagrapi.exceptions.ClientBadRequestError: Unknown ({'message': '', 'response': <Response [400]>, 'status': 'fail'})`

Possibly due to many requests? I'll try the `_v1` function.

**Comment by claell** [comment]
Hm, `_v1` gives me the same error.

Before, I execute `user_followers`, which works fine. If I put the `user_following` function before that, I still get the same error. The numbers for the account are currently 96 followers vs. 137 following. So not sure whether this can already be too much and cause some limit error?

**Comment by Laura-Ag** [comment]
Hello,

still not fixed. Any ideas?

**Comment by Gonoshift** [comment]
Just stumbled on this. 
`user_followers `seems to work but not `user_following `or `user_following_v1`.
It yields a `requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/friendships... etc`

**Comment by LFZDavid** [comment]
Hello, 
I have try with `user_following_gql` and it works for me. Hope it will for you

**Comment by xx7Ahmed7xx** [comment]
I tried it but gave me:ClientJSONDecodeError('JSONDecodeError Expecting value: line 1 column 1 (char 0) while

**Comment by subzeroid** [comment]
I rechecked this against the current code/release and could not reproduce it anymore.

Current behavior:

- authenticated `Client.user_following(...)` uses the private mobile `friendships/{user_id}/following/` path first;
- it only falls back to public GraphQL if the private request fails;
- first-page requests no longer send an empty `max_id`;
- pagination works across pages.

Verification on current `master` / `instagrapi 2.9.1`:

```text
pytest tests/regression/test_user.py::{following regression tests}
4 passed

pytest tests/live/test_user.py::ClientFollowingLiveTestCase::test_user_following_uses_private_api_live \
       tests/live/test_user.py::ClientFollowingLiveTestCase::test_user_following_v1_chunk_paginates_two_pages
2 passed in 61.10s
```

The live check used the `instagram` target account and confirmed both private API lookup and cursor pagination.

Closing this as stale/currently passing. If this still fails for a specific account or target on `instagrapi >= 2.9.1`, please open a fresh issue with the exact response JSON/status from `last_json` and whether it fails on `user_following_v1`, `user_following_gql`, or only the wrapper.

**Comment by subzeroid** [comment]
Closed as stale/currently passing on instagrapi 2.9.1 with regression and live coverage.
