### ISSUE TITLE
[BUG] Login Error using User and Password

### ISSUE THREAD

**Issue by YanSym** [adw0rd/instagrapi#1086]
Hello everyone,

I'm getting errors when logging into multiple accounts using the *login()* method (user and password login), and I can only log into one account with the *login_by_session_id* method.

Is there a way to avoid this error?
Here is the stack trace:

```bash
ConnectionError HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/contact_point_prefill/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f642e566fb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
   File "/home/ozyon/Documents/client code/CLIENT NAME/insta extractor/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
     conn = connection.create_connection(
   File "/home/ozyon/Documents/client code/CLIENT NAME/insta extractor/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File "/home/ozyon/Documents/client code/CLIENT NAME/insta extractor/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
     httplib_response = self._make_request(
   File "/home/ozyon/Documents/client code/CLIENT NAME/insta extractor/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
     self._validate_conn(conn)
   File "/home/ozyon/Documents/client code/CLIENT NAME/insta extractor/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
     conn.connect()
   File "/home/ozyon/Documents/client code/CLIENT NAME/insta extractor/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
     self.sock = conn = self._new_conn()
   File "/home/ozyon/Documents/client code/CLIENT NAME/insta extractor/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
     raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f642e566fb0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File "/home/ozyon/Documents/client codes/CLIENT NAME/insta extractor/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
     resp = conn.urlopen(
   File "/home/ozyon/Documents/client code/CLIENT NAME/insta extractor/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
     retries = retries.increment(
   File "/home/ozyon/Documents/client code/CLIENT NAME/insta extractor/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
     raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/contact_point_prefill/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f642e566fb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))



Thank you very much!

**Comment by adw0rd** [comment]
@YanSym your IP address (proxy/vpn) is banned by instagram
