### ISSUE TITLE
[BUG] UnknownError: The username you entered doesn't appear to belong to an account. Please check your username and try again.

### ISSUE THREAD

**Issue by BinendraWije** [adw0rd/instagrapi#1100]
Hi guys!

I've run into this error and from my limited knowledge on instagrapi usage (and python)  I've tried to :

1. remove cookies 
2. replace the device settings
3. reset internet connection
 
but the issue below still pops up. 

Traceback (most recent call last):
  File "I:/backup/pyprojects/instanature/medialiketest.py", line 68, in <module>
    loaded_settings = my_bot.load_settings('./dump.json')
  File "I:\backup\pyprojects\instanature\venv\lib\site-packages\instagrapi\mixins\auth.py", line 563, in load_settings
    self.set_settings(json.load(fp))
  File "C:\Users\Billy\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Billy\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Billy\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Billy\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\backup\pyprojects\instanature\venv\lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "I:\backup\pyprojects\instanature\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:/backup/pyprojects/instanature/medialiketest.py", line 76, in <module>
    my_bot.login("username", "password")
  File "I:\backup\pyprojects\instanature\venv\lib\site-packages\instagrapi\mixins\auth.py", line 391, in login
    logged = self.private_request("accounts/login/", data, login=True)
  File "I:\backup\pyprojects\instanature\venv\lib\site-packages\instagrapi\mixins\private.py", line 447, in private_request
    raise e
  File "I:\backup\pyprojects\instanature\venv\lib\site-packages\instagrapi\mixins\private.py", line 434, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "I:\backup\pyprojects\instanature\venv\lib\site-packages\instagrapi\mixins\private.py", line 354, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: The username you entered doesn't appear to belong to an account. Please check your username and try again.

Would really appreciate some assistance. 

Thanks

**Comment by adw0rd** [comment]
https://github.com/adw0rd/instagrapi/issues?q=The+username+you+entered+doesn%27t+appear
