### ISSUE TITLE
[BUG] Relogin doesn't work

### ISSUE THREAD

**Issue by claell** [adw0rd/instagrapi#1108]
**Describe the bug**
As written on https://github.com/adw0rd/instagrapi/discussions/743#discussioncomment-4601080, relogin doesn't work for me for some reason.

**Traceback**
Full output (first three lines are from my code):
```
Logging in.
Relogin required.
Relogging in.
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\auth.py", line 813, in parse_authorization
    return json.loads(base64.b64decode(b64part))
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 302, in _send_private_request
    response.raise_for_status()
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/feed/timeline/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Ellsel\Desktop\Instagram tools\interact_to_get_followers.py", line 29, in login_if_required
    cl.get_timeline_feed()
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\auth.py", line 215, in get_timeline_feed
    return self.private_request(
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 451, in private_request
    raise e
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 438, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 327, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 302, in _send_private_request
    response.raise_for_status()
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/feed/timeline/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Ellsel\Desktop\Instagram tools\interact_to_get_followers.py", line 29, in login_if_required
    cl.get_timeline_feed()
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\auth.py", line 215, in get_timeline_feed
    return self.private_request(
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 451, in private_request
    raise e
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 438, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 327, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 302, in _send_private_request
    response.raise_for_status()
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/feed/reels_tray/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Ellsel\Desktop\Instagram tools\interact_to_get_followers.py", line 71, in <module>
    login_if_required(cl)
  File "c:\Users\Ellsel\Desktop\Instagram tools\interact_to_get_followers.py", line 41, in login_if_required
    login_if_required(cl, attempt_no=attempt_no+1)
  File "c:\Users\Ellsel\Desktop\Instagram tools\interact_to_get_followers.py", line 37, in login_if_required
    login(cl, relogin=True)
  File "c:\Users\Ellsel\Desktop\Instagram tools\interact_to_get_followers.py", line 23, in login
    cl.login(instagram_login_details_dict["username"],
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\auth.py", line 417, in login
    self.login_flow()
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\auth.py", line 167, in login_flow
    check_flow.append(self.get_reels_tray_feed("cold_start"))
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\auth.py", line 244, in get_reels_tray_feed
    return self.private_request("feed/reels_tray/", data)
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 451, in private_request
    raise e
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 438, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 327, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python version: 3.9.5

**Comment by claell** [comment]
Code (not complete, maybe I should create a MWE):
```
def login(cl, relogin=False):
    if not relogin:
        print("Logging in.")
    else:
        print("Relogging in.")
    # TODO: Right now, relogin gives an error.
    cl.login(instagram_login_details_dict["username"],
             instagram_login_details_dict["password"], relogin=relogin)


def login_if_required(cl, attempt_no=0):
    try:
        cl.get_timeline_feed()
    except instagrapi.exceptions.LoginRequired:
        time.sleep(random.uniform(1, 2))
        if attempt_no == 0:
            login(cl)
        elif attempt_no == 1:
            print("Relogin required.")
            # TODO: Doesn't work right now. Workaround is to delete (or not load) the settings JSON file.
            login(cl, relogin=True)
        else:
            print("Login attempts failed.")
            return
        login_if_required(cl, attempt_no=attempt_no+1)
```

**Comment by ghrlt** [comment]
You are complicating everything...

Just:
\- Load settings file, if exists
\- Try to login
      If unable to login:
          - Clear client (Just initialize it again?), in order to do a freshlogin
          - Login
          - dump settings into settings file

**Comment by claell** [comment]
You posted code on the discussion (https://github.com/adw0rd/instagrapi/discussions/743#discussioncomment-3063319) basically does the same. And I also do that. And it doesn't work.

**Comment by claell** [comment]
Now, here you suggest to reinitialize the client to do a fresh login, which is not what you do on the posted code. There you use the relogin function, which I also want to use. Maybe I got things wrong, and also relogin only works without having the settings file loaded. I thought it was meant for situations where the settings file is loaded.

**Comment by ghrlt** [comment]
Try to login on the Instagram app. Your account may have been banned/temmbanned, or your IP?

**Comment by claell** [comment]
No, I can also use the login function of Instagrapi if I delete the settings json and sign in with a clean Client. Possibly, only the specific Client was banned, though? So that I need to use a clean one?

**Comment by ghrlt** [comment]
That is exactly what it is all about.... If client with settings do not work, delete settings and retry.
We told you to do that, you told us you were, but from what you're saying, I think you are not.

**Comment by claell** [comment]
Where did you tell me to do that? And where did I tell you I was? I don't see that. I guess there was a lot of misunderstanding, then. Also, please look at your posted code example (I referenced above) where you just use relogin and don't delete the settings.

And sure, I could delete the settings, which is also what I do right now as a workaround. But that will cause Instagram to believe I'd login from a new device (probably because the uuid or other settings parameters change). So ideally, I don't want to do that. I also thought this is what the relogin function was for.

**Comment by ghrlt** [comment]
> Also, please look at your posted code example (I referenced above) where you just use relogin and don't delete the settings.

In this snippet yes, but code snippet don't do all the magic. In multiple discussions/issues, I and others, talked about deleting settings.

> And sure, I could delete the settings, which is also what I do right now as a workaround. But that will cause Instagram to believe I'd login from a new device (probably because the uuid or other settings parameters change). So ideally, I don't want to do that. I also thought this is what the relogin function was for.

That is the whole goal of it. Instagram BANNED your session, so you HAVE TO create another.

**Comment by claell** [comment]
Alright. Just note, that I didn't see anybody else suggesting deleting the settings in this case. Also, the solution in the thread that I referenced was different.

Right now, it's only speculation that IG banned the session. There might be other reasons, including a bug in the code. That's why I wrote here.

**Comment by claell** [comment]
Alright. The reason why there is no error for the normal login function in that state is because the settings are loaded. That makes the login function always return early without logging in: https://github.com/adw0rd/instagrapi/blob/f0c07e3b689e455423dfbf06d5e45a2737d3a386/instagrapi/mixins/auth.py#L368. So one explicitly needs to set `relogin` to `True`.

**Comment by claell** [comment]
Interestingly, on relogin, at least partly new data is used, not the one from the settings JSON. For example:

https://github.com/adw0rd/instagrapi/blob/f0c07e3b689e455423dfbf06d5e45a2737d3a386/instagrapi/mixins/auth.py#L380

If one looks that up, this is generated as new, not loaded from settings.

**Comment by claell** [comment]
Looking at the relevant part of the traceback again:

```
Traceback (most recent call last):
  File "c:\Users\Ellsel\Desktop\Instagram tools\interact_to_get_followers.py", line 71, in <module>
    login_if_required(cl)
  File "c:\Users\Ellsel\Desktop\Instagram tools\interact_to_get_followers.py", line 41, in login_if_required
    login_if_required(cl, attempt_no=attempt_no+1)
  File "c:\Users\Ellsel\Desktop\Instagram tools\interact_to_get_followers.py", line 37, in login_if_required
    login(cl, relogin=True)
  File "c:\Users\Ellsel\Desktop\Instagram tools\interact_to_get_followers.py", line 23, in login
    cl.login(instagram_login_details_dict["username"],
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\auth.py", line 417, in login
    self.login_flow()
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\auth.py", line 167, in login_flow
    check_flow.append(self.get_reels_tray_feed("cold_start"))
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\auth.py", line 244, in get_reels_tray_feed
    return self.private_request("feed/reels_tray/", data)
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 451, in private_request
    raise e
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 438, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 327, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required
```

I see that the error seems to raise from line 417 in auth.py. This is here: https://github.com/adw0rd/instagrapi/blob/f0c07e3b689e455423dfbf06d5e45a2737d3a386/instagrapi/mixins/auth.py#L417

That means that Instagrapi at least "thinks", it (re-)logged in successfully and starts the flow to simulate the behavior after logging in. That fails, then. Not sure why it doesn't detect a failed login attempt before. Maybe because the login succeeds and there are problems afterward?

**Comment by ghrlt** [comment]
Because it has successfully logged in. But then, it actually does a real request to instagram, which return an error since they banned the session.

**Comment by claell** [comment]
Hm, interesting. So you say you can successfully login, although the session has been banned?

**Comment by ghrlt** [comment]
a login with settings is not an API login, at least from what I know/understand. So yes, instagrapi say "ok" but then actually do an api request and Instagram say "fu" because your settings are either invalid or, banned.

I'll not reply anymore to this thread, as you are obviously not understanding on purpose.


> Just: 
> - Load settings file, if exists
> - Try to login 

> If unable to login:
> - Clear client (Just initialize it again?), in order to do a freshlogin
> - Login
> - dump settings into settings file



Do this, and you'll be fine with using this awesome library.

**Comment by claell** [comment]
What do you consider an API login? You can see here that there seems to be a request sent for logging in: https://github.com/adw0rd/instagrapi/blob/f0c07e3b689e455423dfbf06d5e45a2737d3a386/instagrapi/mixins/auth.py#L390

Feel free not to reply anymore. But look, please do not allege bad intuitions of me like you did. That is not nice style. I think, one can clearly see that I tried to understand the information that was given and questioned it because there were some logical problems. I consider that reasoning and skepticism. Not misunderstanding on purpose. It's basically the way to get to the truth, as I don't like to work just based on assumptions. That's just not my style, I hope, you can accept that.

I know that I can delete the settings. I want to know whether it is the right thing to do in this case, or whether Instagrapi has a bug.

Maybe @adw0rd can shed some light on this.

**Comment by adw0rd** [comment]
It works for me, like many others. If you have a problem, that is reproduced, then fix it and send a PR here

**Comment by subzeroid** [comment]
Closing this old login/challenge support thread as stale.

Current challenge and 2FA documentation is here:

- https://subzeroid.github.io/instagrapi/usage-guide/challenge_resolver
- https://subzeroid.github.io/instagrapi/usage-guide/totp
- https://subzeroid.github.io/instagrapi/usage-guide/best-practices

If this still reproduces on `instagrapi >= 2.9.1`, please open a fresh focused issue with sanitized current `last_json`, the exact method call, and the exact exception. Credentials, tokens, contact points, and user IDs should be redacted.
