### ISSUE TITLE
[BUG] ConnectionError:  'Connection aborted.', RemoteDisconnected('Remote end closed connection without response

### ISSUE THREAD

**Issue by jason11ac** [adw0rd/instagrapi#1184]
Hi there,

I am now all of a sudden getting this error every time I call one of the below functions:
- story_seen
- story_like
- media_like

and no matter what we do or what proxy we use (we've tested 3 different proxy options at this point), we all get the same thing. See full response below.

How do we fix this?! It's been completely rendering this library useless, thank you.

```
ConnectionError ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 293, in _send_private_request
    response = self.private.get(api_url, params=params)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/instagrapi/mixins/media.py", line 559, in user_medias_paginated_v1
    items = self.private_request(
  File "/usr/local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 447, in private_request
    self.handle_exception(self, e)
  File "/Users/jason/Instarize_2022/instarize.py", line 254, in handle_exception
    raise e
  File "/usr/local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 438, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 380, in _send_private_request
    raise ClientConnectionError(
instagrapi.exceptions.ClientConnectionError: ConnectionError ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Sleeping for 272 seconds
^CTraceback (most recent call last):
  File "/Users/jason/Instarize_2022/instarize.py", line 425, in <module>
    ultimate()
  File "/Users/jason/Instarize_2022/instarize.py", line 383, in ultimate
    sleepRandom()
  File "/Users/jason/Instarize_2022/instarize.py", line 124, in sleepRandom
    time.sleep(sl)
KeyboardInterrupt

**Comment by jason11ac** [comment]
Thank you @adw0rd but that is not the issue. Please see below the response from this curl:

```
*   Trying 157.240.11.52:443...
* Connected to i.instagram.com (157.240.11.52) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Menlo Park; O=Meta Platforms, Inc.; CN=*.i.instagram.com
*  start date: Jan  8 00:00:00 2023 GMT
*  expire date: Mar 21 23:59:59 2023 GMT
*  subjectAltName: host "i.instagram.com" matched cert's "i.instagram.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f978d812200)
> GET / HTTP/2
> Host: i.instagram.com
> user-agent: curl/7.79.1
> accept: */*
> 
< HTTP/2 301 
< content-type: text/html; charset=utf-8
< location: https://www.instagram.com/
< date: Tue, 14 Mar 2023 02:20:47 GMT
< vary: Accept-Language, Cookie
< content-language: en
< strict-transport-security: max-age=31536000
< cache-control: private, no-cache, no-store, must-revalidate
< pragma: no-cache
< expires: Sat, 01 Jan 2000 00:00:00 GMT
< x-frame-options: SAMEORIGIN
< content-security-policy: report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com https://*.facebook.com https://*.fbsbx.com https://*.giphy.com; font-src data: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://i.instagram.com/graphql_www https://graphql.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com https://*.i.instagram.com https://*.od.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://*.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com https://*.fbsbx.com; object-src 'none'; upgrade-insecure-requests
< x-content-type-options: nosniff
< x-xss-protection: 0
< x-ig-push-state: c2
< x-ig-cache-control: no-cache
< x-aed: 77
< access-control-expose-headers: X-IG-Set-WWW-Claim
< x-ig-request-elapsed-time-ms: 47
< x-ig-peak-time: 1
< set-cookie: csrftoken=Z94mGiyamVG9evpe7d0mAZTfP4zFy33p; Domain=.instagram.com; expires=Tue, 12-Mar-2024 02:20:47 GMT; Max-Age=31449600; Path=/; Secure
< set-cookie: mid=ZA_Z_wAEAAGTU70xFLmaWdTDz6a9; Domain=.instagram.com; expires=Thu, 13-Mar-2025 02:20:47 GMT; Max-Age=63072000; Path=/; Secure
< set-cookie: ig_did=83636E48-71A1-4380-8062-031AED5C48BD; Domain=.instagram.com; expires=Thu, 13-Mar-2025 02:20:47 GMT; HttpOnly; Max-Age=63072000; Path=/; Secure
< set-cookie: ig_nrcb=1; Domain=.instagram.com; expires=Wed, 13-Mar-2024 02:20:47 GMT; Max-Age=31536000; Path=/; Secure
< content-length: 0
< x-ig-origin-region: nao
< x-fb-trip-id: 382461245
< alt-svc: h3=":443"; ma=86400
< 
* Connection #0 to host i.instagram.com left intact
```


There appears to be nothing wrong...What should we try next?

This only happens when we try these functions:

story_seen
story_like
media_like

so it seems like it has something to do with "writes" as opposed to just "reading" info.

Please help us, thanks!

**Comment by adw0rd** [comment]
Cannot reproduce:

```
>>> cl.media_like(3036413532296933518)
True
```
