### ISSUE TITLE
Login failed on valid credentials 

### ISSUE THREAD

**Issue by imJunaidAfzal** [adw0rd/instagrapi#1190]
I'm trying to login with valid username and password but get an error "The username you entered doesn't appear to belong to an account"

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 313, in _send_private_request
    response.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/instagrapi/mixins/auth.py", line 403, in login
    logged = self.private_request("accounts/login/", data, login=True)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 461, in private_request
    raise e
  File "/home/ubuntu/.local/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 446, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 368, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: The username you entered doesn't appear to belong to an account. Please check your username and try again.
```

**Comment by imJunaidAfzal** [comment]
> Same here

Where you run the code, in local machine or somewhere else?

**Comment by adw0rd** [comment]
Duplicate #1183
