### ISSUE TITLE
Media archive does not work maybe?

### ISSUE THREAD

**Issue by hozgryldz** [adw0rd/instagrapi#1191]
media_archive function may be broken. I tried a few times, but failed. Below is an output.
Please advise. Thanks.

```
root@96c9c8444d6a:/bot# python
Python 3.11.2 (main, Mar 14 2023, 01:34:19) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from instagrapi import Client
>>> from pathlib import Path
>>> cl = Client()
>>> cl.load_settings(Path(f"settings/k.json"))
{'uuids':....
>>> cl.login("myusername","issecret")
True
>>> cl.media_pk_from_url("https://www.instagram.com/p/CqBhsITph4e/")
3062877389700079134
>>> cl.media_archive(3062877389700079134)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 313, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/3062877389700079134_528817151/only_me/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/media.py", line 960, in media_archive
    result = self.private_request(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 461, in private_request
    raise e
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 446, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 368, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: could not hide
>>> 
```

**Comment by hozgryldz** [comment]
Let me add the version I am using:
```

root@96c9c8444d6a:/bot# pip show instagrapi
Name: instagrapi
Version: 1.17.1
...
```

**Comment by hozgryldz** [comment]
Later on I noticed to save a post I was to use media_save. My bad. I should have waited and rechecked the documents another time.
