### ISSUE TITLE
[BUG] instagrapi.exceptions.MediaNotFound: Media not found or unavailable

### ISSUE THREAD

**Issue by sxs1316** [adw0rd/instagrapi#1217]
Hello writer, my English is not very good, the following is from the translation.
Your example:
->>> cl.story_download(cl.story_pk_from_url('https://www.instagram.com/stories/adw0rd/2581281926631793076/'))
My call:
->>> c.story_download(c.story_pk_from_url('https://www.instagram.com/stories/highlights/18235246471094746/'))

I compared the URL and found that there was something wrong with the parameter in the penultimate path.  When it was replaced by an ins user, the ins indicated that the link was damaged.

https://www.instagram.com/stories/l.ovely_kim/18006184243535317/

Destination URL：https://www.instagram.com/stories/highlights/18006184243535317/

Looking forward to your reply, Thanks♪(･ω･)ﾉ

Report an error:
Traceback (most recent call last):
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/instagrapi/mixins/media.py", line 259, in media_info
    media = self.media_info_gql(media_pk)
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/instagrapi/mixins/media.py", line 208, in media_info_gql
    raise MediaNotFound(media_pk=media_pk, **data)
instagrapi.exceptions.MediaNotFound: Not found ({'media_pk': '18235246471094746', 'shortcode_media': None})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 313, in _send_private_request
    response.raise_for_status()
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/18235246471094746/info/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/instagrapi/mixins/media.py", line 230, in media_info_v1
    result = self.private_request(f"media/{media_pk}/info/")
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 461, in private_request
    raise e
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 446, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 368, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: Media not found or unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/instagrapi/mixins/story.py", line 271, in story_download
    story = self.story_info(story_pk)
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/instagrapi/mixins/story.py", line 92, in story_info
    story = self.story_info_v1(story_pk)
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/instagrapi/mixins/story.py", line 63, in story_info_v1
    story_id = self.media_id(story_pk)
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/instagrapi/mixins/media.py", line 57, in media_id
    user = self.media_user(media_id)
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/instagrapi/mixins/media.py", line 372, in media_user
    return self.media_info(media_pk).user
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/instagrapi/mixins/media.py", line 269, in media_info
    media = self.media_info_v1(media_pk)
  File "/InsSendMessage/098f6bcd4621d373cade4e832627b4f6_venv/lib/python3.9/site-packages/instagrapi/mixins/media.py", line 235, in media_info_v1
    raise MediaNotFound(e, media_pk=media_pk, **self.last_json)
instagrapi.exceptions.MediaNotFound: Media not found or unavailable

**Comment by sxs1316** [comment]
I am a clown
