### ISSUE TITLE
I can't log in

### ISSUE THREAD

**Issue by Dandelion101** [adw0rd/instagrapi#1223]
when trying to log in, the following error is displayed
```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\ssl.p
y", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\ssl.p
y", line 1075, in _create
    self.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\ssl.p
y", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] unknown error (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='i.instagram.com', po
rt=443): Max retries exceeded with url: /api/v1/accounts/contact_point_prefill/
(Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:992)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response = self.private.post(api_url, data=data, params=params, proxies=self
.private.proxies)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='i.instagram.com', port=4
43): Max retries exceeded with url: /api/v1/accounts/contact_point_prefill/ (Cau
sed by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:992)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\inst\script\insta_bot.py", line 131, in m
ain
    cl = auth(login, password, proxy)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\inst\script\insta_bot.py", line 35, in au
th
    cl.login(username=login, password=password)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\auth.py", line 383, in login
    self.pre_login_flow()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\auth.py", line 47, in pre_login_flow
    self.set_contact_point_prefill("prefill")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\auth.py", line 150, in set_contact_point_prefill
    return self.private_request("accounts/contact_point_prefill/", data, login=T
rue)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\private.py", line 461, in private_request
    raise e
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\private.py", line 446, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\private.py", line 389, in _send_private_request
    raise ClientConnectionError("{e.__class__.__name__} {e}".format(e=e))
instagrapi.exceptions.ClientConnectionError: SSLError HTTPSConnectionPool(host='
i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/con
tact_point_prefill/ (Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c
:992)')))
```
I use a proxy (Ukraine). I have already changed the standard phone settings and changed the proxy region, there used to be the USA
Who has already faced such a problem and how can it be solved?

**Comment by adw0rd** [comment]
https://github.com/adw0rd/instagrapi/issues?q=SSLError
