### ISSUE TITLE
how to handle challenge_required

### ISSUE THREAD

**Issue by xiamoplus** [adw0rd/instagrapi#123]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/story.py", line 189, in user_stories
    return self.user_stories_gql(user_id, amount)
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/story.py", line 137, in user_stories_gql
    user = self.users_stories_gql([user_id])[0]
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/story.py", line 107, in users_stories_gql
    res = self.public_graphql_request(
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/public.py", line 197, in public_graphql_request
    body_json = self.public_request(
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/public.py", line 59, in public_request
    return self._send_public_request(url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/public.py", line 119, in _send_public_request
    return response.json() if return_json else response.text
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 173, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/user/42792406/story/?supported_capabilities_new=%5B%7B%22name%22%3A+%22SUPPORTED_SDK_VERSIONS%22%2C+%22value%22%3A+%2269.0%2C70.0%2C71.0%2C72.0%2C73.0%2C74.0%2C75.0%2C76.0%2C77.0%2C78.0%2C79.0%2C80.0%2C81.0%2C82.0%2C83.0%2C84.0%2C85.0%2C86.0%2C87.0%2C88.0%2C89.0%2C90.0%2C91.0%2C92.0%2C93.0%2C94.0%2C95.0%2C96.0%2C97.0%2C98.0%2C99.0%2C100.0%2C101.0%2C102.0%2C103.0%2C104.0%22%7D%2C+%7B%22name%22%3A+%22FACE_TRACKER_VERSION%22%2C+%22value%22%3A+%2214%22%7D%2C+%7B%22name%22%3A+%22segmentation%22%2C+%22value%22%3A+%22segmentation_enabled%22%7D%2C+%7B%22name%22%3A+%22COMPRESSION%22%2C+%22value%22%3A+%22ETC2_COMPRESSION%22%7D%2C+%7B%22name%22%3A+%22world_tracker%22%2C+%22value%22%3A+%22world_tracker_enabled%22%7D%2C+%7B%22name%22%3A+%22gyroscope%22%2C+%22value%22%3A+%22gyroscope_enabled%22%7D%5D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 293, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 203, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 293, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 203, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 173, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/user/42792406/story/?supported_capabilities_new=%5B%7B%22name%22%3A+%22SUPPORTED_SDK_VERSIONS%22%2C+%22value%22%3A+%2269.0%2C70.0%2C71.0%2C72.0%2C73.0%2C74.0%2C75.0%2C76.0%2C77.0%2C78.0%2C79.0%2C80.0%2C81.0%2C82.0%2C83.0%2C84.0%2C85.0%2C86.0%2C87.0%2C88.0%2C89.0%2C90.0%2C91.0%2C92.0%2C93.0%2C94.0%2C95.0%2C96.0%2C97.0%2C98.0%2C99.0%2C100.0%2C101.0%2C102.0%2C103.0%2C104.0%22%7D%2C+%7B%22name%22%3A+%22FACE_TRACKER_VERSION%22%2C+%22value%22%3A+%2214%22%7D%2C+%7B%22name%22%3A+%22segmentation%22%2C+%22value%22%3A+%22segmentation_enabled%22%7D%2C+%7B%22name%22%3A+%22COMPRESSION%22%2C+%22value%22%3A+%22ETC2_COMPRESSION%22%7D%2C+%7B%22name%22%3A+%22world_tracker%22%2C+%22value%22%3A+%22world_tracker_enabled%22%7D%2C+%7B%22name%22%3A+%22gyroscope%22%2C+%22value%22%3A+%22gyroscope_enabled%22%7D%5D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insta_main.py", line 175, in <module>
    print("Just tried to look for new post, but nothing new!")
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/vb_monitor/instagram-vanguard/src/Story.py", line 33, in newer_media
    newest_media = api.user_stories(account.pk)[-1]
  File "/vb_monitor/instagram-vanguard/src/MultiClient.py", line 50, in user_stories
    return self.select_api().user_stories(user_id)
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/story.py", line 195, in user_stories
    return self.user_stories_v1(user_id, amount)
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/story.py", line 162, in user_stories_v1
    reel = self.private_request(f"feed/user/{user_id}/story/", params=params)[
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 310, in private_request
    return self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 203, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required
```

How can I handle this error? I tried your example "challenge_resolvers.py" but I can't make it to work either.
Thanks in advance

**Comment by adw0rd** [comment]
Related #22
