### ISSUE TITLE
I can't log in AssertionError

### ISSUE THREAD

**Issue by Dandelion101** [adw0rd/instagrapi#1231]
I also had a ClientError with the same response, but it was resolved when I replaced the proxy. Could it be that it's about the account?

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\private.py", line 313, in _send_private_request
    response.raise_for_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.
instagram.com/api/v1/challenge/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\challenge.py", line 76, in challenge_resolve
    self._send_private_request(challenge_url[1:], params=params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\private.py", line 344, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\inst\script\insta_bot.py", line 132, in m
ain
    cl = auth(login, password, proxy)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\inst\script\insta_bot.py", line 35, in au
th
    cl.login(username=login, password=password)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\auth.py", line 434, in login
    self.login_flow()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\auth.py", line 170, in login_flow
    check_flow.append(self.get_reels_tray_feed("cold_start"))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\auth.py", line 247, in get_reels_tray_feed
    return self.private_request("feed/reels_tray/", data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\private.py", line 459, in private_request
    self.challenge_resolve(self.last_json)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\challenge.py", line 79, in challenge_resolve
    return self.challenge_resolve_contact_form(challenge_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\instagrapi\mixins\challenge.py", line 184, in challenge_resolve_contact
_form
    assert result.get("challengeType") in (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: {'message': 'Please wait a few minutes before you try again.', '
require_login': True, 'status': 'fail'}
```

**Comment by WillReynolds5** [comment]
same here

**Comment by sekoakb** [comment]
any1 solved it?

**Comment by draxisonfire** [comment]
@adw0rd give us a hint, please

**Comment by adw0rd** [comment]
> @adw0rd give us a hint, please

`time.sleep(600)`

**Comment by draxisonfire** [comment]
> `time.sleep(600)`

So i tried this and earlier even 1 week+ of pause, but it doesn't helps — i constantly get "AssertionError: {'message': 'Please wait a few minutes before you try again.', 'require_login': True, 'status': 'fail'}" when trying to get timeline feed. To be more precise, at first i get default 'login_required', my script does cl.relogin() and fails it with this AssertionError message. If i then try to relogin again and again, i'm only get this AssertionError.

I have two theories:
1. something wrong with my saved session file
2. my proxy

Сould any of this be the reason?

**Comment by adw0rd** [comment]
Instagram asks you to wait "Please wait a few minutes before you try again", wait exponentially and after a while it will unblock you

**Comment by subzeroid** [comment]
Closing this old login/challenge support thread as stale.

Current challenge and 2FA documentation is here:

- https://subzeroid.github.io/instagrapi/usage-guide/challenge_resolver
- https://subzeroid.github.io/instagrapi/usage-guide/totp
- https://subzeroid.github.io/instagrapi/usage-guide/best-practices

If this still reproduces on `instagrapi >= 2.9.1`, please open a fresh focused issue with sanitized current `last_json`, the exact method call, and the exact exception. Credentials, tokens, contact points, and user IDs should be redacted.
