### ISSUE TITLE
Photo not Uploading[BUG]

### ISSUE THREAD

**Issue by zephyr582** [adw0rd/instagrapi#1278]
**Describe the bug**
I am trying to collect instagram pictures and find which one has the most amount of likes and post it. 

**Traceback**
Photo Upload failed with the following response: <Response [403]>
Traceback (most recent call last):
  File "/Users/nicolasrulli/Desktop/MiscCode/python_projects/InstagramAutomated/file.py", line 137, in <module>
    client.photo_upload(uploadPath, caption)
  File "/Users/nicolasrulli/Desktop/MiscCode/python_projects/env/lib/python3.7/site-packages/instagrapi/mixins/photo.py", line 230, in photo_upload
    upload_id, width, height = self.photo_rupload(path, upload_id)
  File "/Users/nicolasrulli/Desktop/MiscCode/python_projects/env/lib/python3.7/site-packages/instagrapi/mixins/photo.py", line 192, in photo_rupload
    raise PhotoNotUpload(response.text, response=response, **last_json)

**Expected behavior**
It worked a day or two before today. Not sure what's going on. I saw another person say to check the file type and this image is a JPG 

EDIT: 
I am now getting this as my traceback:
Status 429: Too many requests
Ignore 429: Continue login
Traceback (most recent call last):
  File "/Users/nicolasrulli/Desktop/MiscCode/python_projects/env/lib/python3.7/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/Users/nicolasrulli/Desktop/MiscCode/python_projects/env/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nicolasrulli/Desktop/MiscCode/python_projects/InstagramAutomated/file.py", line 17, in <module>
    client.login(username, password)
  File "/Users/nicolasrulli/Desktop/MiscCode/python_projects/env/lib/python3.7/site-packages/instagrapi/mixins/auth.py", line 391, in login
    logged = self.private_request("accounts/login/", data, login=True)
  File "/Users/nicolasrulli/Desktop/MiscCode/python_projects/env/lib/python3.7/site-packages/instagrapi/mixins/private.py", line 447, in private_request
    raise e
  File "/Users/nicolasrulli/Desktop/MiscCode/python_projects/env/lib/python3.7/site-packages/instagrapi/mixins/private.py", line 434, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/Users/nicolasrulli/Desktop/MiscCode/python_projects/env/lib/python3.7/site-packages/instagrapi/mixins/private.py", line 354, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: The username you entered doesn't appear to belong to an account. Please check your username and try again.

What should I do?

**Comment by zephyr582** [comment]
> ```
> The username you entered doesn't appear to belong to an account. Please check your username and try again.
> ```

My credentials are correct. I haven't changed my username, password or edited my credentials file. 

If I type my creds into insta i get this: 
"There was a problem logging you into Instagram. Please try again soon."

Does this mean I have a temp ban from logging in?

**Comment by adw0rd** [comment]
https://github.com/adw0rd/instagrapi/issues?q=The+username+you+entered

https://github.com/adw0rd/instagrapi/discussions?discussions_q=The+username+you+entered

**Comment by zephyr582** [comment]
> https://github.com/adw0rd/instagrapi/issues?q=The+username+you+entered
> 
> https://github.com/adw0rd/instagrapi/discussions?discussions_q=The+username+you+entered

Neither of these seem to be helpful. I am new to github and using instagrapi so can you give me a bit more detail/help?
Let me know, 
Thanks!

**Comment by adw0rd** [comment]
@zephyr582 https://adw0rd.github.io/instagrapi/usage-guide/best-practices.html
