### ISSUE TITLE
[BUG]reels failing to upload

### ISSUE THREAD

**Issue by zephyr582** [adw0rd/instagrapi#1315]
**Describe the bug**
init.py and clip.py file issues

**To Reproduce**
Provide a piece of code to reproduce the problem.

**Traceback**
Traceback (most recent call last):
  File "/Users/nicolasrulli/Desktop/MiscCode/python_projects/InstagramAutomated/file.py", line 100, in <module>
    import moviepy.editor
  File "/Users/nicolasrulli/Desktop/MiscCode/python_projects/env/lib/python3.7/site-packages/moviepy/editor.py", line 48, in <module>
    import moviepy.video.fx.all as vfx
  File "/Users/nicolasrulli/Desktop/MiscCode/python_projects/env/lib/python3.7/site-packages/moviepy/video/fx/all/__init__.py", line 17, in <module>
    exec("from ..%s import %s" % (name, name))
  File "<string>", line 1
    from ..__init__ 2 import __init__ 2
                    ^
SyntaxError: invalid syntax

**Expected behavior**
reel should upload!

**Desktop (please complete the following information):**
-12.3.1
-python: 3.7.4

**Comment by chrisbuetti** [comment]
I get this error:VideoNotUpload: Unknown ({'message': '', 'response': <Response [302]>})
