### ISSUE TITLE
[Error in track_info_by_canonical_id]

### ISSUE THREAD

**Issue by notsarv** [adw0rd/instagrapi#1340]
I am trying to get track info from a reel's audio canonical id

The Error i got :
```
Traceback (most recent call last):
  File "/root/insta-dm-bot-python/b.py", line 39, in <module>
    handle_reel(message);
    ^^^^^^^^^^^^^^^^^^^^
  File "/root/insta-dm-bot-python/b.py", line 20, in handle_reel
    reel_track = client.track_info_by_canonical_id(message.clip.clips_metadata['music_canonical_id'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instagrapi/mixins/track.py", line 67, in track_info_by_canonical_id
    return extract_track(track)
           ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instagrapi/extractors.py", line 435, in extract_track
    data["cover_artwork_uri"] = data.get("cover_artwork_uri") or None
                                ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

track.py give none as parameter to extractor.py. maybe because change in instagram api.
Please give a check ....

**Comment by adw0rd** [comment]
Show what's in `message.clip.clips_metadata['music_canonical_id']`

**Comment by subzeroid** [comment]
Fixed and released.

`track_info_by_canonical_id(...)` now raises `TrackNotFound(music_canonical_id=...)` when Instagram returns a successful `clips/music/` response without `metadata.music_info.music_asset_info`, instead of passing `None` into `extract_track(...)` and raising `AttributeError`.

Releases:
- instagrapi 2.10.1: https://github.com/subzeroid/instagrapi/releases/tag/2.10.1
- instagrapi PyPI: https://pypi.org/project/instagrapi/2.10.1/
- instagrapi Codeberg mirror: https://codeberg.org/subzeroid/instagrapi/src/tag/2.10.1
- aiograpi 1.4.1 mirror: https://github.com/subzeroid/aiograpi/releases/tag/1.4.1
- aiograpi PyPI: https://pypi.org/project/aiograpi/1.4.1/
- aiograpi Codeberg mirror: https://codeberg.org/subzeroid/aiograpi/src/tag/1.4.1

PRs:
- https://github.com/subzeroid/instagrapi/pull/2643
- https://github.com/subzeroid/aiograpi/pull/342

Coverage added for both the mocked missing-asset payload and the current live missing-track canonical-id response.
