### ISSUE TITLE
[BUG] Using location_medias_top() always results in ValueError

### ISSUE THREAD

**Issue by leonardodafishy** [adw0rd/instagrapi#1366]
**Describe the bug**
Using location_medias_top() always results in ValueError: too many values to unpack (expected 2)

**To Reproduce**
medias = cl.location_medias_top(107617247320879, amount=2)

**Traceback**
Traceback (most recent call last):
  File "C:\Users\koton\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\231.9011.38\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "C:\Users\koton\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\231.9011.38\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\koton\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\231.9011.38\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\koton\PycharmProjects\Recognizance-py\location.py", line 151, in <module>
    medias_csv = hashtag_data()
                 ^^^^^^^^^^^^^^
  File "C:\Users\koton\PycharmProjects\Recognizance-py\location.py", line 60, in hashtag_data
    medias = client.location_medias_top_v1(3824034)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\koton\PycharmProjects\Recognizance-py\venv\Lib\site-packages\instagrapi\mixins\location.py", line 408, in location_medias_top_v1
    return self.location_medias_v1(location_pk, amount, tab_key="ranked")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\koton\PycharmProjects\Recognizance-py\venv\Lib\site-packages\instagrapi\mixins\location.py", line 363, in location_medias_v1
    medias, _ = self.location_medias_v1_chunk(location_pk, amount, tab_key)
    ^^^^^^^^^
ValueError: too many values to unpack (expected 2)

**Expected behavior**
Return Top posts by Location as it is described on the documentation.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python version - 3.11
 - instagrapi version - 1.17.10

**Comment by adw0rd** [comment]
Fixed instagrapi 1.19.5

```python
>>> cl.location_medias_top(107617247320879, amount=2)
[Media(pk='3166171797253638517', id='3166171797253638517_60928740961', code='CvwgHl5Kcl1', ...
```
