### ISSUE TITLE
[BUG] "We've detected automated behavior on your account"

### ISSUE THREAD

**Issue by Yqno** [adw0rd/instagrapi#1376]
**Describe the bug**
after 16 Likes i get the error "We've detected automated behavior on your account"

**To Reproduce**
Provide a piece of code to reproduce the problem.

**Traceback**
challenge_required
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 360, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/3120098763652652723_59109663105/comment/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 520, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 391, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 360, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/3120098763652652723_59109663105/comment/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 520, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 391, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

**Expected behavior**
the script should continue with liking, commenting and following 

**Screenshots**
![IMG_4168](https://github.com/adw0rd/instagrapi/assets/79216939/8db609b5-ead2-4619-b60f-f7bdec41f922)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Python version 3.11.3
 - instagrapi version 1.17.10

**Comment by sekoakb** [comment]
+1, having same issue even running below 10 times approx.

![cap](https://github.com/adw0rd/instagrapi/assets/121935816/53714b83-364e-4bcc-a299-c4cfae905150)

**Comment by alexferra** [comment]
same issue, even though Im using AI!!

**Comment by YiitWT** [comment]
Did anyone find a way to fix?

**Comment by subzeroid** [comment]
This is Instagram account-risk enforcement, not a bug that can be fixed in `instagrapi`. The report describes repeated likes/comments/follows until Instagram displays “We've detected automated behavior on your account”; that response is intentionally server-side and account-dependent.

Relevant docs:

- Best practices / rate limits: https://subzeroid.github.io/instagrapi/usage-guide/best-practices
- Common exceptions: https://subzeroid.github.io/instagrapi/exceptions

For this class of response, the safe behavior is to stop the automation, keep the same session/device/proxy identity, inspect the account manually, and reduce write-heavy actions. The library should surface the challenge/feedback response; it should not try to bypass Instagram enforcement.

Closing as not actionable as an instagrapi code bug.

**Comment by subzeroid** [comment]
Closed as Instagram account-risk enforcement, not an instagrapi defect.
