### ISSUE TITLE
[BUG] requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by k12978** [adw0rd/instagrapi#1411]
### Compensate with donations ($15 and more) for the time I spent to fix problems or send me your [Pull Request](https://github.com/adw0rd/instagrapi/pulls) with fixes

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

* Tron TRX/USDT: `TLprxuzHjXPkHYa7ZfTTt165p7Fphwy1Ee`
* Bitcoin: `bc1qmp7538hktvg2gx994hrpkmsmyjc03q29awe9ra`
* Ethereum: `0x0E674815d513d4a00F6a7Cd4A990807aB97cC70D`
* Dogecoin: `DSEXzMBYhBTwhNqzPGxVWFsTqVsTCeDejo`

**Describe the bug**
When I try to get user_medias, I get the error above and when I click the listed "unauthorized url" I am met with the following:
```
{"message":"useragent mismatch","status":"fail"}
```

**To Reproduce**
```python
import instagrapi
INSTAGRAPI = instagrapi.Client()
source_slug = <profile username>
source_id = INSTAGRAPI.user_id_from_username(source_slug)
source = INSTAGRAPI.user_medias(source_id)
```

**Traceback**
```
Traceback (most recent call last):
  File "e:\PATH\.venv\Lib\site-packages\instagrapi\mixins\private.py", line 360, in _send_private_request
    response.raise_for_status()
  File "e:\PATH\.venv\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://i.instagram.com/api/v1/feed/user/<any valid user id here>/?max_id=&count=0&rank_token=<rank token here>&ranked_content=true
```

**Expected behavior**
I expected for the list of user medias to be returned.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python version 3.11.1 (virtual environment)
 - instagrapi version 1.17.10

**Comment by arda1984** [comment]
same

**Comment by AmineMahdioui** [comment]
401 error in Instagram usually means the account can't interact with the network because it was suspended or encountered a challenge  (we suspect you are using automation, confirm its you,...)

**Comment by takeaflightwithme** [comment]
Hi folks, I got the same issue. I just started working on automating the Likes on hashtags, it work for one day, but on the second day I tried running the model and received similar error 

Traceback (most recent call last):
  File "/Users/cradmin/Desktop/PyProject/venv/lib/python3.11/site-packages/instagrapi/mixins/public.py", line 168, in _send_public_request
    response.raise_for_status()
  File "/Users/cradmin/Desktop/PyProject/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.instagram.com/explore/tags/aerialvideography/?__a=1&__d=dis

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cradmin/Desktop/PyProject/venv/lib/python3.11/site-packages/instagrapi/mixins/hashtag.py", line 421, in hashtag_medias_recent
    medias = self.hashtag_medias_recent_a1(name, amount)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cradmin/Desktop/PyProject/venv/lib/python3.11/site-packages/instagrapi/mixins/hashtag.py", line 384, in hashtag_medias_recent_a1
    return self.hashtag_medias_a1(name, amount, tab_key="edge_hashtag_to_media")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cradmin/Desktop/PyProject/venv/lib/python3.11/site-packages/instagrapi/mixins/hashtag.py", line 220, in hashtag_medias_a1
    medias, _ = self.hashtag_medias_a1_chunk(name, amount, tab_key)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cradmin/Desktop/PyProject/venv/lib/python3.11/site-packages/instagrapi/mixins/hashtag.py", line 164, in hashtag_medias_a1_chunk
    data = self.public_a1_request(
           ^^^^^^^^^^^^^^^^^^^^^^^

**Comment by diezo** [comment]
Using [ensta](https://github.com/diezo/ensta):

```py
from ensta import AutoHost, Guest

guest = Guest()  # No Login
host = AutoHost(username, password, file="session.txt")  # Requires Login

print(guest.profile("cristiano")

print(host.profile("cristiano")
print(host.follow("cristiano")
```
