### ISSUE TITLE
[BUG] Pydantic validation error

### ISSUE THREAD

**Issue by tchikl-h** [adw0rd/instagrapi#1435]
### Compensate with donations ($15 and more) for the time I spent to fix problems or send me your [Pull Request](https://github.com/adw0rd/instagrapi/pulls) with fixes

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

* Tron TRX/USDT: `TLprxuzHjXPkHYa7ZfTTt165p7Fphwy1Ee`
* Bitcoin: `bc1qmp7538hktvg2gx994hrpkmsmyjc03q29awe9ra`
* Ethereum: `0x0E674815d513d4a00F6a7Cd4A990807aB97cC70D`
* Dogecoin: `DSEXzMBYhBTwhNqzPGxVWFsTqVsTCeDejo`

**Describe the bug**
Getting a pydantic validation error when trying to get the best medias from a specific hashtag

**To Reproduce**

```python
from instagrapi import Client
from instagrapi.exceptions import LoginRequired
import logging
import json
import os.path

logger = logging.getLogger()

cl = Client()
cl.login(USERNAME, PASSWORD)
medias = cl.hashtag_medias_top('downhill', amount=5)
print(json.dumps(medias, indent = 4))

**Traceback**
Traceback (most recent call last):
  File "C:\Users\herve_5hk53qv\repo\instagrapi\examples\download_top_by_hashtag.py", line 74, in <module>
    medias = cl.hashtag_medias_top('downlhill', amount=5)
  File "C:\Users\herve_5hk53qv\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\hashtag.py", line 365, in hashtag_medias_top
    medias = self.hashtag_medias_top_a1(name, amount)
  File "C:\Users\herve_5hk53qv\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\hashtag.py", line 328, in hashtag_medias_top_a1
    return self.hashtag_medias_a1(name, amount, tab_key="edge_hashtag_to_top_posts")
  File "C:\Users\herve_5hk53qv\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\hashtag.py", line 221, in hashtag_medias_a1
    medias, _ = self.hashtag_medias_a1_chunk(name, amount, tab_key)
  File "C:\Users\herve_5hk53qv\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\hashtag.py", line 181, in hashtag_medias_a1_chunk
    media = extract_media_gql(edge["node"])
  File "C:\Users\herve_5hk53qv\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\extractors.py", line 84, in extract_media_gql
    user = extract_user_short(media["owner"])
  File "C:\Users\herve_5hk53qv\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\extractors.py", line 172, in extract_user_short
    return UserShort(**data)
  File "C:\Users\herve_5hk53qv\AppData\Local\Programs\Python\Python39\lib\site-packages\pydantic\main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 4 validation errors for UserShort
username
  Field required [type=missing, input_value={'id': '52761857721', 'pk': '52761857721'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
profile_pic_url
  Field required [type=missing, input_value={'id': '52761857721', 'pk': '52761857721'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
profile_pic_url_hd
  Field required [type=missing, input_value={'id': '52761857721', 'pk': '52761857721'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
is_private
  Field required [type=missing, input_value={'id': '52761857721', 'pk': '52761857721'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
```

**Expected behavior**
It should print a list of medias

**Comment by alexferra** [comment]
looking at the source control and having the same error, this is the issue:

before:
pydantic==1.10.9

now:
pydantic==2.0

just revert into the old version of pydantic and it works. @tchikl-h

**Comment by adw0rd** [comment]
@alexferra thanks!

**Comment by vsharm29** [comment]
I am trying to search for the music with the below code

`cl.search_music("dilawara")`

I have checked I am using the correct version of pydantic that is **pydantic==1.10.9**
I also tried to delete the virtual environment and did a fresh `pip install instagrapi` but the same issue 


```
ValidationError                           Traceback (most recent call last)
[e:\projects\instareel\instaupload.ipynb](file:///E:/projects/instareel/instaupload.ipynb) Cell 3 line 1
----> [1](vscode-notebook-cell:/e%3A/projects/instareel/instaupload.ipynb#W2sZmlsZQ%3D%3D?line=0) cl.search_music("dilawara")

File [e:\projects\instareel\demoenv\Lib\site-packages\instagrapi\mixins\fbsearch.py:57](file:///E:/projects/instareel/demoenv/Lib/site-packages/instagrapi/mixins/fbsearch.py:57), in FbSearchMixin.search_music(self, query)
     52 params = {
     53     "query": query,
     54     "browse_session_id": self.generate_uuid(),
     55 }
     56 result = self.private_request("music/audio_global_search/", params=params)
---> 57 return [extract_track(item["track"]) for item in result["items"]]

File [e:\projects\instareel\demoenv\Lib\site-packages\instagrapi\mixins\fbsearch.py:57](file:///E:/projects/instareel/demoenv/Lib/site-packages/instagrapi/mixins/fbsearch.py:57), in <listcomp>(.0)
     52 params = {
     53     "query": query,
     54     "browse_session_id": self.generate_uuid(),
     55 }
     56 result = self.private_request("music/audio_global_search/", params=params)
---> 57 return [extract_track(item["track"]) for item in result["items"]]

File [e:\projects\instareel\demoenv\Lib\site-packages\instagrapi\extractors.py:472](file:///E:/projects/instareel/demoenv/Lib/site-packages/instagrapi/extractors.py:472), in extract_track(data)
    470 items = re.findall(r"<BaseURL>(.+?)</BaseURL>", data["dash_manifest"])
    471 data["uri"] = html.unescape(items[0]) if items else None
--> 472 return Track(**data)
...
File [e:\projects\instareel\demoenv\Lib\site-packages\pydantic\main.py:341](file:///E:/projects/instareel/demoenv/Lib/site-packages/pydantic/main.py:341), in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for Track
territory_validity_periods
  field required (type=value_error.missing)
```

**Comment by boyu8266** [comment]
It seems the current JSON format returned does not include the "territory_validity_periods" value.
It will cause a validation error during parsing Track(BaseModel).

![image](https://github.com/subzeroid/instagrapi/assets/40316055/afc7fd92-6129-49cc-9b7c-928d56c430f5)

**Comment by boyu8266** [comment]
@vsharm29 

```
from instagrapi.extractors import extract_track


def custom_search_music(client: Client, query: str):
    params = {
        "query": query,
        "browse_session_id": client.generate_uuid(),
    }
    result = client.private_request("music/audio_global_search/", params=params)
    items = result['items']
    for item in items:
        item['track']['territory_validity_periods'] = {}
    return [extract_track(item["track"]) for item in result["items"]]

tracks = custom_search_music(client, "love")
tracks
```

**Comment by vsharm29** [comment]
@boyu8266 
Thanks brother it started working with your code.

**Comment by PyDevelopp** [comment]
hello? how i can fix it?
1 validation error for Account
pk
Input should be a valid string [type=string_type, input_value=56538923004, input_type=int]
For further information visit https://errors.pydantic.dev/2.5/v/string_type
