### ISSUE TITLE
[BUG] Invalid parameters error

### ISSUE THREAD

**Issue by VivatPrograms** [adw0rd/instagrapi#1478]
```
Traceback (most recent call last):
File "C:\Users\marco\AppData\Roaming\Python\Python310\site-packages\instagrapi\mixins\private.py", line 360, in _send_private_request
response.raise_for_status()
File "C:\Users\marco\AppData\Roaming\Python\Python310\site-packages
equests\models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\marco\OneDrive\Desktop\fiverr_proj (1)\fiverr_proj\pre-bot.py", line 5, in
client.login(username=username, password=password)
File "C:\Users\marco\AppData\Roaming\Python\Python310\site-packages\instagrapi\mixins\auth.py", line 403, in login
logged = self.private_request("accounts/login/", data, login=True)
File "C:\Users\marco\AppData\Roaming\Python\Python310\site-packages\instagrapi\mixins\private.py", line 535, in private_request
raise e
File "C:\Users\marco\AppData\Roaming\Python\Python310\site-packages\instagrapi\mixins\private.py", line 520, in private_request
self._send_private_request(endpoint, **kwargs)
File "C:\Users\marco\AppData\Roaming\Python\Python310\site-packages\instagrapi\mixins\private.py", line 440, in _send_private_request
raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: Invalid Parameters
```

Why do I get this error?
For context here's the code I'm running here:

```python
from instagrapi import Client
from settings import *

client = Client()
client.login(username=username, password=password)
client.dump_settings('./dump.json')
client.logout()

```

**Comment by adw0rd** [comment]
Cannot reproduce for `instagrapi 1.18.2`

```
In [1]: from instagrapi import Client

In [2]: client = Client(proxy="http://XXXXXX@45.192.145.172:5514")

In [3]: client.login(username="aurorarussell88", password="i93d8ep7hdg")
Out[3]: True

In [4]: client.dump_settings('./dump.json')
Out[4]: True

In [5]: client.logout()
Out[5]: True
```
