### ISSUE TITLE
[BUG]ClipNotUpload error persisting. 

### ISSUE THREAD

**Issue by NicoRulli** [adw0rd/instagrapi#1486]
**Describe the bug**
My code is downloading the correct files however when it comes to actually uploading clips, anything for that matter, it fails. 

**To Reproduce**
`# Started on April 12th, 2023
# Packages
from instagrapi import Client
import time
import os
import datetime 
from instagrapi.exceptions import LoginRequired
import logging

credentialsPath = "/Users/Shared/InstagramAutomated/credentials.txt"

with open(credentialsPath, "r") as f:
    USERNAME, PASSWORD = f.read().splitlines()

cl = Client()
logger = logging.getLogger()

def login_user():
    """
    Attempts to login to Instagram using either the provided session information
    or the provided username and password.
    """

    cl = Client()
    session = cl.load_settings("session.json")

    login_via_session = False
    login_via_pw = False

    if session:
        try:
            cl.set_settings(session)
            cl.login(USERNAME, PASSWORD)

            # check if session is valid
            try:
                cl.get_timeline_feed()
            except LoginRequired:
                logger.info("Session is invalid, need to login via username and password")

                old_session = cl.get_settings()

                # use the same device uuids across logins
                cl.set_settings({})
                cl.set_uuids(old_session["uuids"])

                cl.login(USERNAME, PASSWORD)
            login_via_session = True
        except Exception as e:
            logger.info("Couldn't login user using session information: %s" % e)

    if not login_via_session:
        try:
            logger.info("Attempting to login via username and password. username: %s" % USERNAME)
            if cl.login(USERNAME, PASSWORD):
                login_via_pw = True
        except Exception as e:
            logger.info("Couldn't login user using username and password: %s" % e)

    if not login_via_pw and not login_via_session:
        raise Exception("Couldn't login user with either password or session")

login_user()

start = time.time()
print("Code is running and being timed. Please wait....")

file_path = '/Users/Shared/InstagramAutomated/runFile.txt'
x = datetime.datetime.now()
with open(file_path, 'w') as file:
    content = f"File ran at {x}"
    file.write(content)
file.close()

usernames = [
    "hannesribbner",
    "teamlyonfish",
    "captnickstanczyk",
    "ariatunafishing",
    "fv_whiskeybusiness",
    "highlymigratoryfishing",
    "joevt_fishing",
    "reeladdictioniiisportfishing",
    "almcglashan",
    "dennis_verreet",
    "david_lassley",
    "high_seas_hawaii",
    "bhagz_fishing",

]
print('Successful Login')

ids = []
id_dict = {}

PKDict = {}
PKList = []
max_likes = 0

primaryKeysInFile = []

def create_user_id_list(usernames):
    for i in usernames:
        ids.append(cl.user_id_from_username(i))

def create_user_id_dict(usernames):
    for i in range(len(usernames)):
        id_dict[usernames[i]] = ids[i]

def collect_like_count():
    media = []
    for i in ids:
        media += cl.user_medias(i, 9)
        for i in range(len(media)):
            media_dict = media[i].dict()
            likeCount = media_dict['like_count']
            PKDict[media_dict['pk']] = likeCount
    

def most_liked_PK():
    max_likes = 0
    
    # print('Collecting max likes...')
    for i,v in PKDict.items():
        if v > max_likes:
            max_likes = v
    
    mostLikedPK = 0
    for i,v in PKDict.items():
        if max_likes == v:
            mostLikedPK = i
    
    return mostLikedPK

primaryKeyPath = "/Users/Shared/InstagramAutomated/primarykeys.txt"

def prevent_repost(mostLikedPK):
    with open(primaryKeyPath, "r") as f:
        primaryKeysInFile = f.read().splitlines()
    
    sorted_dict = {k: v for k, v in sorted(PKDict.items(), key=lambda item: item[1])}

    newDict = {}
    for i,v in sorted_dict.items():
        if i not in primaryKeysInFile:
            newDict[i] = v
    
    sorted_dict = {k: v for k, v in sorted(newDict.items(), key=lambda item: item[1])}

    mostLikedPK = list(newDict)[-1]

    with open(primaryKeyPath, "a") as f:
        f.write(str(mostLikedPK))
        f.write('\n')
        f.close()

    return mostLikedPK

create_user_id_list(usernames)
print('1')
create_user_id_dict(usernames)
print('2')
collect_like_count()
print('3')
Mlpk = most_liked_PK()
print('4')
Mlpk = prevent_repost(Mlpk)
print('5')

media_type = cl.media_info(Mlpk).dict()['media_type']

product_type = cl.media_info(Mlpk).dict()['product_type']

m = cl.media_info(Mlpk)

url = m.video_url

downloadPath = "/Users/Shared/InstagramAutomated/downloadedPosts"

print("media type: " + str(media_type))
print("Attempting to download...")
p = ''
files = os.listdir(downloadPath)

if media_type == 1:                                  #picture
    cl.photo_download(Mlpk, downloadPath)
    

if media_type == 2 and product_type == 'clips':
    p = cl.clip_download(Mlpk,downloadPath)          #Reel

if media_type == 2 and product_type == 'feed':       #Video
    # cl.video_download(MLPK, downloadPath)
    p = cl.video_download_by_url(m.video_url)

if media_type == 2 and product_type == 'igtv':       #IGTV
    # cl.igtv_download(MLPK,downloadPath)
    p = cl.igtv_download_by_url(m.video_url)

if media_type == 8:                                  #Album
    # cl.album_download(MLPK, downloadPath)
    p = downloadPath + '/' + files[1]
    cl.album_download(Mlpk,downloadPath)

poster = "@" + str(cl.media_user(Mlpk).dict()['username'])
location = cl.media_info(Mlpk).dict()['location']

if location != None:
    location = str(location['name'])
    caption = "Check out this post by " + poster + " out near " + location + "! \nTag your Friends and comment below! \n . \n . \n . \n . \n . \n . \n . \n . \n #billfish #bluemarlin #sailfish #centerconsole #simrad #furuno #sailfishing #fishing #gamefish #sportfishing #pelagicgirl #pelagicworldwide #fishingteam #tuna #bluefin #jigging #trolling #offshore #swordfish #panamafishing #spearfishing #bahamasfishing #catchandcook #saltlife #catchoftheday #pescasub #floridawildlife #floridakeys"

else:
    caption = f"Check out this post by {poster}! \nTag your Friends and comment below! \n . \n . \n . \n . \n . \n . \n . \n . \n #billfish #bluemarlin #sailfish #centerconsole #simrad #furuno #sailfishing #fishing #gamefish #sportfishing #pelagicgirl #pelagicworldwide #fishingteam #tuna #bluefin #jigging #trolling #offshore #swordfish #panamafishing #spearfishing #bahamasfishing #catchandcook #saltlife #catchoftheday #pescasub #floridawildlife #floridakeys"

print()
print("Attempting to Upload...")

if media_type == 1:                                  #picture
    p = downloadPath + '/' + files[1]
    print('pic',p)
    cl.photo_upload(p, caption)

if media_type == 2 and product_type == 'clips':      #Reel
    print('****clip****', p)
    cl.clip_upload(p, caption)

if media_type == 2 and product_type == 'feed':       #Video 
    print('video', p)
    cl.video_upload(p, caption)

if media_type == 2 and product_type == 'igtv':       #IGTV
    print('igtv', p)
    cl.igtv_upload(p, caption)
    
if media_type == 8:                                  #Album
    print('album',p)
    cl.album_upload(p, caption)

os.remove(p)

print("File Deleted")

cl.logout()
end = time.time()
t = end - start
print(f"Ran in: {t.__round__(2)} seconds")`

Above is my entire code. 

**Traceback**
Attempting to Upload...
****clip**** /Users/Shared/InstagramAutomated/downloadedPosts/ariatunafishing_2995272891689440277.mp4
Analyzing CLIP file "/Users/Shared/InstagramAutomated/downloadedPosts/ariatunafishing_2995272891689440277.mp4"
Generating thumbnail "/Users/Shared/InstagramAutomated/downloadedPosts/ariatunafishing_2995272891689440277.mp4.jpg"...
Traceback (most recent call last):
  File "/Users/Shared/InstagramAutomated/file2.py", line 230, in <module>
    cl.clip_upload(p, caption)
  File "/Users/nicolasrulli/Library/Python/3.9/lib/python/site-packages/instagrapi/mixins/clip.py", line 144, in clip_upload
    raise ClipNotUpload(response=self.last_response, **self.last_json)
instagrapi.exceptions.ClipNotUpload: Unknown ({'response': None})

**Expected behavior**
the clip isn't being uploaded after giving it the correct code and being downloaded the way OP said. 

PS: 
I know @adw0rd closed my previous post about this issue, however I did what was suggested and I have the same error which leads me to believe that it is a bug and it isn't on my end.

**Comment by NicoRulli** [comment]
my entire code is up on my page. 
Feel free to test along with your own username and password in a credentials.txt file

**Comment by adw0rd** [comment]
This code has a lot of your extra business logic, the paths of which I don’t have and other things, it’s impossible to read it, you didn’t even bother to format it

Put a maximum of 10 lines of code, locate the problem and then I will find the time to reproduce the problem for you, most likely the problem is in your code and improper use of the library

**Comment by NicoRulli** [comment]
I'm back. 
Here is my code. I got rid of as much as possible and will attempt to explain it to the best of my ability. 
I have a primary key of a known instagram reel. I then get the media type and product type. 
I then create a file path of where I want the post to get downloaded. 
I give the clip_download function the required parameters being primary key and path. 

it downloads just fine. 

I then create a valid path to the file that was just downloaded. 
files is a list of all the files in the downloadedPosts folder. 
to create the upload path, I add a / and pick the 0th file in the folder * and checked that it is the correct file, which it is*
I then run the upload function with the file path and a caption. 

`Mlpk = 2935933286516376579

media_type = cl.media_info(Mlpk).dict()['media_type']

product_type = cl.media_info(Mlpk).dict()['product_type']

m = cl.media_info(Mlpk)
downloadPath = "/Users/Shared/InstagramAutomated/downloadedPosts"

if media_type == 2 and product_type == 'clips':
    cl.clip_download(Mlpk, downloadPath)

files = os.listdir(downloadPath)

upload = downloadPath + '/' + files[0]

if media_type == 2 and product_type == 'clips':      #Reel
    cl.clip_upload(upload, 'test')`



I still end up with this error:
Analyzing CLIP file "/Users/Shared/InstagramAutomated/downloadedPosts/fv_whiskeybusiness_2935933286516376579.mp4"
Generating thumbnail "/Users/Shared/InstagramAutomated/downloadedPosts/fv_whiskeybusiness_2935933286516376579.mp4.jpg"...
Traceback (most recent call last):
  File "/Users/Shared/InstagramAutomated/test.py", line 80, in <module>
    cl.clip_upload(upload, 'test')
  File "/Users/nicolasrulli/Library/Python/3.9/lib/python/site-packages/instagrapi/mixins/clip.py", line 144, in clip_upload
    raise ClipNotUpload(response= self.last_response, **self.last_json)
instagrapi.exceptions.ClipNotUpload: Unknown ({'response': None})

As you can see, I am giving it all of the correct information and using the code properly. 
yet, this error still occurs. not only with clipUpload. but other upload functions. 
It is getting to the point where the thumbnail is created, but not able to upload it. 

The only thing occurring before the code I just pasted is logging in and importing the necessary packages. 
I rewrote 11 lines of code to remove any potential error on my end and the error is still happening. 
If you see any obvious issues then let me know. If not, then there must be a bug. 

If you suggest me to try a different upload method then I will do as you suggest. however, based on the repository it seems I am doing everything correctly. the upload function solely requests a path which I am giving it. I don't know how I can go wrong when the clip_upload function begins to run then fails within itself on line 144

**Comment by adw0rd** [comment]
Your code makes unnecessary calls, try this one:

```
pk = 2935933286516376579

media = cl.media_info(pk)
folder = "/Users/Shared/InstagramAutomated/downloadedPosts"

if media.media_type == 2 and media.product_type == 'clips':
    # upload_path = cl.clip_download(pk, folder=folder)
    upload_path = cl.clip_download_by_url(m.video_url, folder=folder)
    cl.clip_upload(upload_path, 'test')
```

**Comment by NicoRulli** [comment]
I just ran that and got the same error. 
here is my code:
```
Mlpk = 2935933286516376579


m = cl.media_info(Mlpk)
downloadPath = "/Users/Shared/InstagramAutomated/downloadedPosts"

if m.media_type == 2 and m.product_type == 'clips':
    # upload_path = cl.clip_download(pk, folder=folder)
    upload_path = cl.clip_download_by_url(m.video_url, folder=downloadPath)
    cl.clip_upload(upload_path, 'test')

print('done')
```

**Comment by adw0rd** [comment]
Try another instagram account, I don't know any other reason why instagram won't let you upload the clip

**Comment by NicoRulli** [comment]
I need to make another one.
but I'll give it a shot and reply here.

**Comment by NicoRulli** [comment]
Made a new account and it isn't working, same error.

**Comment by adw0rd** [comment]
what version of instagrapi?

share the created account, I will check on it

**Comment by NicoRulli** [comment]
I just ran pip3 show instagrapi and it says version 1.18.2
And what do you mean by share? The user and pass? or just the user?

**Comment by adw0rd** [comment]
username, password (or sessionid) and your proxy

**Comment by NicoRulli** [comment]
Where do i find the proxy? 
And is there a way to privately send all of this?

**Comment by adw0rd** [comment]
> Where do i find the proxy?

If you don't have a proxy, then you don't need one

> And is there a way to privately send all of this?

https://t.me/m11k4

**Comment by NicoRulli** [comment]
I just sent a message

**Comment by NicoRulli** [comment]
Have you had a chance to look into this?

**Comment by adw0rd** [comment]
I answered in private messages, you can send a summary of our discussion here

**Comment by florifull** [comment]
Same issue. Fixed BadPassword issue by using local sessions and now just getting this when trying to upload things.

**Comment by subzeroid** [comment]
Fixed in https://github.com/subzeroid/instagrapi/commit/5fe2f0fbd4ce5a63f324572e415108031e386239 and released in https://github.com/subzeroid/instagrapi/releases/tag/2.5.15.

This updates the standard Reel/clip upload flow to the current Instagram Android request shape: upload settings preflight before rupload, the current upload-name format, rupload params, and segment headers. The fix is included in https://github.com/subzeroid/instagrapi/pull/2458 and was covered by mock regression tests plus a live Reel upload/delete check.

Closing this as fixed for the stale standard Reel upload flow.
