### ISSUE TITLE
[BUG] ClipNotUpload

### ISSUE THREAD

**Issue by florifull** [adw0rd/instagrapi#1530]
Was able to bypass BadPassword issues via sessions, but still getting ClipNotUpload errors.

<-----STARTING POSTING SEQUENCE----->
Analyzing CLIP file "C:\Users\Administrator\Desktop\withpassword\downloads\174C4DDE788E56BCE5424582D4D071B3_video_dashinit.mp4"
Generating thumbnail "C:\Users\Administrator\Desktop\withpassword\downloads\174C4DDE788E56BCE5424582D4D071B3_video_dashinit.mp4.jpg"...
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\withpassword\src\poster.py", line 62, in main
    media = api.clip_upload(
            ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\instagrapi\mixins\clip.py", line 144, in clip_upload
    raise ClipNotUpload(response=self.last_response, **self.last_json)
instagrapi.exceptions.ClipNotUpload: login_required

**Comment by rickturner2001** [comment]
The error is on line 144 in `clip.py`

```python
self.request_log(response)
if response.status_code != 200:
    raise ClipNotUpload(response=self.last_response, **self.last_json)
```

As you can see, the request is being logged. It might be a good idea to activate your logger at the `DEBUG` level to access the request payload. 

Keep us updated


Also, could you show give us a little bit more context regarding the code you're trying to execute?

**Comment by rickturner2001** [comment]
on an unrelated note, what are clips? Are clips Reels?

**Comment by adw0rd** [comment]
> on an unrelated note, what are clips? Are clips Reels?

Yes

**Comment by subzeroid** [comment]
Fixed in https://github.com/subzeroid/instagrapi/commit/5fe2f0fbd4ce5a63f324572e415108031e386239 and released in https://github.com/subzeroid/instagrapi/releases/tag/2.5.15.

This updates the standard Reel/clip upload flow to the current Instagram Android request shape: upload settings preflight before rupload, the current upload-name format, rupload params, and segment headers. The fix is included in https://github.com/subzeroid/instagrapi/pull/2458 and was covered by mock regression tests plus a live Reel upload/delete check.

Closing this as fixed for the stale standard Reel upload flow.
