### ISSUE TITLE
429 Client Error: Please wait a few minutes before you try again

### ISSUE THREAD

**Issue by Aleexxen** [adw0rd/instagrapi#154]
Hi, I'm trying to log in but i get this error:
requests.exceptions.HTTPError: 429 Client Error: - for url: https://i.instagram.com/api/v1/accounts/contact_point_prefill/

I just downloaded the library and didn't change anything. This is my first login.
The account doesn't have 2 factor auth. And my username and password are exactly correct. I'm using this code to test:

```
from instagrapi import Client

cl = Client()
cl.login('login', 'password')
```

Maybe I should change something in the device or browser settings?

As I understand it, the problem is in the class PreLoginFlowMixin the process stops at a function self.set_contact_point_prefill("prefill"). I don't quite understand what this means. As far as I know, at the first login, the program tries to log in publicly as _v1. Perhaps the problem is that the default settings for the browser are not the same as my browser.
I would be grateful for any help, I have been sitting with this problem for a long time 

User agent for public requests as I think: ('User-Agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15'). I don't know if it is important

The full traceback is:

```
Status 429: Too many requests
Traceback (most recent call last):
  File "F:\PyCharmProjects\Diplom2\venv\lib\site-packages\instagrapi\mixins\private.py", line 183, in _send_private_request
    response.raise_for_status()
  File "F:\PyCharmProjects\Diplom2\venv\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: - for url: https://i.instagram.com/api/v1/accounts/contact_point_prefill/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\PyCharmProjects\Diplom2\main.py", line 4, in <module>
    cl.login('my_login', 'my_password')
  File "F:\PyCharmProjects\Diplom2\venv\lib\site-packages\instagrapi\mixins\auth.py", line 326, in login
    self.pre_login_flow()
  File "F:\PyCharmProjects\Diplom2\venv\lib\site-packages\instagrapi\mixins\auth.py", line 35, in pre_login_flow
    self.set_contact_point_prefill("prefill")
  File "F:\PyCharmProjects\Diplom2\venv\lib\site-packages\instagrapi\mixins\auth.py", line 134, in set_contact_point_prefill
    return self.private_request("accounts/contact_point_prefill/", data, login=True)
  File "F:\PyCharmProjects\Diplom2\venv\lib\site-packages\instagrapi\mixins\private.py", line 316, in private_request
    raise e
  File "F:\PyCharmProjects\Diplom2\venv\lib\site-packages\instagrapi\mixins\private.py", line 303, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "F:\PyCharmProjects\Diplom2\venv\lib\site-packages\instagrapi\mixins\private.py", line 244, in _send_private_request
    raise PleaseWaitFewMinutes(e, response=e.response, **last_json)
instagrapi.exceptions.PleaseWaitFewMinutes: Please wait a few minutes before you try again.

Process finished with exit code 1
```

**Comment by adw0rd** [comment]
@Aleexxen I researched this question, the instagram application simply ignores this error and continues to log in
