### ISSUE TITLE
instagrapi.exceptions.ClientConnectionError

### ISSUE THREAD

**Issue by PrantaChakraborty** [adw0rd/instagrapi#1553]
**Whenever I try to call the Instagram API, it shows the error. Though I'm using proxy**

**To Reproduce**
`user_media = client.user_medias_v1(user_id=ig_user_id, amount=5)`

**Traceback**
```shell
[2023-08-23 22:48:17,549: ERROR/ForkPoolWorker-1] ConnectionError HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/feed/user/377795485/?max_id=&count=5&rank_token=60853666950_a8c7ca38-3a63-4fb5-af4d-14dfb9a1fdd1&ranked_content=true (Caused by ProtocolError('Connection aborted.', BadStatusLine('\x00[Ãµ´Òß$')))
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('\x00[Ãµ´Òß$'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 874, in urlopen
    return self.urlopen(
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 874, in urlopen
    return self.urlopen(
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 874, in urlopen
    return self.urlopen(
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/feed/user/377795485/?max_id=&count=5&rank_token=60853666950_a8c7ca38-3a63-4fb5-af4d-14dfb9a1fdd1&ranked_content=true (Caused by ProtocolError('Connection aborted.', BadStatusLine('\x00[Ãµ´Òß$')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 346, in _send_private_request
    response = self.private.get(
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/feed/user/377795485/?max_id=&count=5&rank_token=60853666950_a8c7ca38-3a63-4fb5-af4d-14dfb9a1fdd1&ranked_content=true (Caused by ProtocolError('Connection aborted.', BadStatusLine('\x00[Ãµ´Òß$')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/instagrapi/mixins/media.py", line 636, in user_medias_paginated_v1
    items = self.private_request(
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 542, in private_request
    raise e
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 527, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/pranta/Documents/django-project/venv/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 468, in _send_private_request
    raise ClientConnectionError("{e.__class__.__name__} {e}".format(e=e))
instagrapi.exceptions.ClientConnectionError: ConnectionError HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/feed/user/377795485/?max_id=&count=5&rank_token=60853666950_a8c7ca38-3a63-4fb5-af4d-14dfb9a1fdd1&ranked_content=true (Caused by ProtocolError('Connection aborted.', BadStatusLine('\x00[Ãµ´Òß$')))
``` 

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Python version 3.10.12
 - instagrapi version 1.19.7
 - moveipy version 1.0.3

**Comment by adw0rd** [comment]
The problem is not instagrapi, but at the network level, try another proxy
