### ISSUE TITLE
Possible SSL bug on stories

### ISSUE THREAD

**Issue by riccardolunardi** [adw0rd/instagrapi#170]
I don't know if this is just me (maybe exceeding the rate limit) or if it's a bug raise by either SSL or the story class.
Did it happen to you, too? Or it's just me?
Thanks

### **Traceback**

```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 352, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 932, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 354, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query/?variables=%7B%22reel_ids%22%3A%5B42792406%5D%2C%22p
recomposed_overlay%22%3Afalse%7D&query_hash=303a4ae99711322310f25250d988f3b7 (Caused by SSLError(OSError(24, 'Too many open files')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/public.py", line 100, in _send_public_request
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query/?variables=%7B%22reel_ids%22%3A%5B42792406%5D%2C%22preco
mposed_overlay%22%3Afalse%7D&query_hash=303a4ae99711322310f25250d988f3b7 (Caused by SSLError(OSError(24, 'Too many open files')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/story.py", line 191, in user_stories
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/story.py", line 139, in user_stories_gql
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/story.py", line 109, in users_stories_gql
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/public.py", line 203, in public_graphql_request
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/public.py", line 85, in public_request
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/public.py", line 65, in public_request
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/public.py", line 157, in _send_public_request
instagrapi.exceptions.ClientConnectionError: SSLError HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query/?variables=%7B%22reel_ids%22%3A%
5B42792406%5D%2C%22precomposed_overlay%22%3Afalse%7D&query_hash=303a4ae99711322310f25250d988f3b7 (Caused by SSLError(OSError(24, 'Too many open files')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 352, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 932, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 354, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/feed/user/42792406/story/?supported_capabilities_new=%5B%7B%2
2name%22%3A+%22SUPPORTED_SDK_VERSIONS%22%2C+%22value%22%3A+%2269.0%2C70.0%2C71.0%2C72.0%2C73.0%2C74.0%2C75.0%2C76.0%2C77.0%2C78.0%2C79.0%2C80.0%2C81.0%2C82.0%2C83.0%2C84.0%2C85.0%2C86.0%2C8
7.0%2C88.0%2C89.0%2C90.0%2C91.0%2C92.0%2C93.0%2C94.0%2C95.0%2C96.0%2C97.0%2C98.0%2C99.0%2C100.0%2C101.0%2C102.0%2C103.0%2C104.0%22%7D%2C+%7B%22name%22%3A+%22FACE_TRACKER_VERSION%22%2C+%22va
lue%22%3A+%2214%22%7D%2C+%7B%22name%22%3A+%22segmentation%22%2C+%22value%22%3A+%22segmentation_enabled%22%7D%2C+%7B%22name%22%3A+%22COMPRESSION%22%2C+%22value%22%3A+%22ETC2_COMPRESSION%22%7
D%2C+%7B%22name%22%3A+%22world_tracker%22%2C+%22value%22%3A+%22world_tracker_enabled%22%7D%2C+%7B%22name%22%3A+%22gyroscope%22%2C+%22value%22%3A+%22gyroscope_enabled%22%7D%5D (Caused by SSL
Error(OSError(24, 'Too many open files')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/private.py", line 178, in _send_private_request
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/feed/user/42792406/story/?supported_capabilities_new=%5B%7B%22nam
e%22%3A+%22SUPPORTED_SDK_VERSIONS%22%2C+%22value%22%3A+%2269.0%2C70.0%2C71.0%2C72.0%2C73.0%2C74.0%2C75.0%2C76.0%2C77.0%2C78.0%2C79.0%2C80.0%2C81.0%2C82.0%2C83.0%2C84.0%2C85.0%2C86.0%2C87.0%
2C88.0%2C89.0%2C90.0%2C91.0%2C92.0%2C93.0%2C94.0%2C95.0%2C96.0%2C97.0%2C98.0%2C99.0%2C100.0%2C101.0%2C102.0%2C103.0%2C104.0%22%7D%2C+%7B%22name%22%3A+%22FACE_TRACKER_VERSION%22%2C+%22value%
22%3A+%2214%22%7D%2C+%7B%22name%22%3A+%22segmentation%22%2C+%22value%22%3A+%22segmentation_enabled%22%7D%2C+%7B%22name%22%3A+%22COMPRESSION%22%2C+%22value%22%3A+%22ETC2_COMPRESSION%22%7D%2C
+%7B%22name%22%3A+%22world_tracker%22%2C+%22value%22%3A+%22world_tracker_enabled%22%7D%2C+%7B%22name%22%3A+%22gyroscope%22%2C+%22value%22%3A+%22gyroscope_enabled%22%7D%5D (Caused by SSLErro
r(OSError(24, 'Too many open files')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insta_main.py", line 195, in <module>
    if new.result():
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/vb_monitor/instagram-vanguard/src/Story.py", line 36, in newer_media
    newest_media = api.user_stories(account.pk)[-1]
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/story.py", line 197, in user_stories
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/story.py", line 164, in user_stories_v1
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/private.py", line 321, in private_request
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/private.py", line 308, in private_request
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/private.py", line 260, in _send_private_request
instagrapi.exceptions.ClientConnectionError: SSLError HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/feed/user/42792406/story/?supported_capab
ilities_new=%5B%7B%22name%22%3A+%22SUPPORTED_SDK_VERSIONS%22%2C+%22value%22%3A+%2269.0%2C70.0%2C71.0%2C72.0%2C73.0%2C74.0%2C75.0%2C76.0%2C77.0%2C78.0%2C79.0%2C80.0%2C81.0%2C82.0%2C83.0%2C84
.0%2C85.0%2C86.0%2C87.0%2C88.0%2C89.0%2C90.0%2C91.0%2C92.0%2C93.0%2C94.0%2C95.0%2C96.0%2C97.0%2C98.0%2C99.0%2C100.0%2C101.0%2C102.0%2C103.0%2C104.0%22%7D%2C+%7B%22name%22%3A+%22FACE_TRACKER
_VERSION%22%2C+%22value%22%3A+%2214%22%7D%2C+%7B%22name%22%3A+%22segmentation%22%2C+%22value%22%3A+%22segmentation_enabled%22%7D%2C+%7B%22name%22%3A+%22COMPRESSION%22%2C+%22value%22%3A+%22E
TC2_COMPRESSION%22%7D%2C+%7B%22name%22%3A+%22world_tracker%22%2C+%22value%22%3A+%22world_tracker_enabled%22%7D%2C+%7B%22name%22%3A+%22gyroscope%22%2C+%22value%22%3A+%22gyroscope_enabled%22%
7D%5D (Caused by SSLError(OSError(24, 'Too many open files')))
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 26, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 36, in <module>
    apt_pkg.init_system()
apt_pkg.Error: E:Error reading the Tuple table

Original exception was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 352, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 932, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 354, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query/?variables=%7B%22reel_ids%22%3A%5B42792406%5D%2C%22p
recomposed_overlay%22%3Afalse%7D&query_hash=303a4ae99711322310f25250d988f3b7 (Caused by SSLError(OSError(24, 'Too many open files')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/public.py", line 100, in _send_public_request
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query/?variables=%7B%22reel_ids%22%3A%5B42792406%5D%2C%22preco
mposed_overlay%22%3Afalse%7D&query_hash=303a4ae99711322310f25250d988f3b7 (Caused by SSLError(OSError(24, 'Too many open files')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/story.py", line 191, in user_stories
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/story.py", line 139, in user_stories_gql
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/story.py", line 109, in users_stories_gql
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/public.py", line 203, in public_graphql_request
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/public.py", line 85, in public_request
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/public.py", line 65, in public_request
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/public.py", line 157, in _send_public_request
instagrapi.exceptions.ClientConnectionError: SSLError HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query/?variables=%7B%22reel_ids%22%3A%
5B42792406%5D%2C%22precomposed_overlay%22%3Afalse%7D&query_hash=303a4ae99711322310f25250d988f3b7 (Caused by SSLError(OSError(24, 'Too many open files')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 352, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 932, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 354, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/feed/user/42792406/story/?supported_capabilities_new=%5B%7B%2
2name%22%3A+%22SUPPORTED_SDK_VERSIONS%22%2C+%22value%22%3A+%2269.0%2C70.0%2C71.0%2C72.0%2C73.0%2C74.0%2C75.0%2C76.0%2C77.0%2C78.0%2C79.0%2C80.0%2C81.0%2C82.0%2C83.0%2C84.0%2C85.0%2C86.0%2C8
7.0%2C88.0%2C89.0%2C90.0%2C91.0%2C92.0%2C93.0%2C94.0%2C95.0%2C96.0%2C97.0%2C98.0%2C99.0%2C100.0%2C101.0%2C102.0%2C103.0%2C104.0%22%7D%2C+%7B%22name%22%3A+%22FACE_TRACKER_VERSION%22%2C+%22va
lue%22%3A+%2214%22%7D%2C+%7B%22name%22%3A+%22segmentation%22%2C+%22value%22%3A+%22segmentation_enabled%22%7D%2C+%7B%22name%22%3A+%22COMPRESSION%22%2C+%22value%22%3A+%22ETC2_COMPRESSION%22%7
D%2C+%7B%22name%22%3A+%22world_tracker%22%2C+%22value%22%3A+%22world_tracker_enabled%22%7D%2C+%7B%22name%22%3A+%22gyroscope%22%2C+%22value%22%3A+%22gyroscope_enabled%22%7D%5D (Caused by SSL
Error(OSError(24, 'Too many open files')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/private.py", line 178, in _send_private_request
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/feed/user/42792406/story/?supported_capabilities_new=%5B%7B%22nam
e%22%3A+%22SUPPORTED_SDK_VERSIONS%22%2C+%22value%22%3A+%2269.0%2C70.0%2C71.0%2C72.0%2C73.0%2C74.0%2C75.0%2C76.0%2C77.0%2C78.0%2C79.0%2C80.0%2C81.0%2C82.0%2C83.0%2C84.0%2C85.0%2C86.0%2C87.0%
2C88.0%2C89.0%2C90.0%2C91.0%2C92.0%2C93.0%2C94.0%2C95.0%2C96.0%2C97.0%2C98.0%2C99.0%2C100.0%2C101.0%2C102.0%2C103.0%2C104.0%22%7D%2C+%7B%22name%22%3A+%22FACE_TRACKER_VERSION%22%2C+%22value%
22%3A+%2214%22%7D%2C+%7B%22name%22%3A+%22segmentation%22%2C+%22value%22%3A+%22segmentation_enabled%22%7D%2C+%7B%22name%22%3A+%22COMPRESSION%22%2C+%22value%22%3A+%22ETC2_COMPRESSION%22%7D%2C
+%7B%22name%22%3A+%22world_tracker%22%2C+%22value%22%3A+%22world_tracker_enabled%22%7D%2C+%7B%22name%22%3A+%22gyroscope%22%2C+%22value%22%3A+%22gyroscope_enabled%22%7D%5D (Caused by SSLErro
r(OSError(24, 'Too many open files')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insta_main.py", line 195, in <module>
    if new.result():
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/vb_monitor/instagram-vanguard/src/Story.py", line 36, in newer_media
    newest_media = api.user_stories(account.pk)[-1]
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/story.py", line 197, in user_stories
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/story.py", line 164, in user_stories_v1
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/private.py", line 321, in private_request
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/private.py", line 308, in private_request
  File "/usr/local/lib/python3.8/dist-packages/instagrapi-1.7.0-py3.8.egg/instagrapi/mixins/private.py", line 260, in _send_private_request
instagrapi.exceptions.ClientConnectionError: SSLError HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/feed/user/42792406/story/?supported_capab
ilities_new=%5B%7B%22name%22%3A+%22SUPPORTED_SDK_VERSIONS%22%2C+%22value%22%3A+%2269.0%2C70.0%2C71.0%2C72.0%2C73.0%2C74.0%2C75.0%2C76.0%2C77.0%2C78.0%2C79.0%2C80.0%2C81.0%2C82.0%2C83.0%2C84
.0%2C85.0%2C86.0%2C87.0%2C88.0%2C89.0%2C90.0%2C91.0%2C92.0%2C93.0%2C94.0%2C95.0%2C96.0%2C97.0%2C98.0%2C99.0%2C100.0%2C101.0%2C102.0%2C103.0%2C104.0%22%7D%2C+%7B%22name%22%3A+%22FACE_TRACKER
_VERSION%22%2C+%22value%22%3A+%2214%22%7D%2C+%7B%22name%22%3A+%22segmentation%22%2C+%22value%22%3A+%22segmentation_enabled%22%7D%2C+%7B%22name%22%3A+%22COMPRESSION%22%2C+%22value%22%3A+%22E
TC2_COMPRESSION%22%7D%2C+%7B%22name%22%3A+%22world_tracker%22%2C+%22value%22%3A+%22world_tracker_enabled%22%7D%2C+%7B%22name%22%3A+%22gyroscope%22%2C+%22value%22%3A+%22gyroscope_enabled%22%
7D%5D (Caused by SSLError(OSError(24, 'Too many open files')))
root@VanguardCageV2:/vb_monitor/instagram-vanguard# e%22%3A+%22SUPPORTED_SDK_VERSIONS%22%2C+%22value%22%3A+%2269.0%2C70.0%2C71.0%2C72.0%2C73.0%2C74.0%2C75.0%2C76.0%2C77.0%2C78.0%2C79.0%2C80
.0%2C81.0%2C82.0%2C83.0%2C84.0%2C85.0%2C86.0%2C87.0%2C88.0%2C89.0%2C90.0%2C91.0%2C92.0%2C93.0%2C94.0%2C95.0%2C96.0%2C97.0%2C98.0%2C99.0%2C100.0%2C101.0%2C102.0%2C103.0%2C104.0%22%7D%2C+%7B%
22name%22%3A+%22FACE_TRACKER_VERSION%22%2C+%22value%22%3A+%2214%22%7D%2C+%7B%22name%22%3A+%22segmentation%22%2C+%22value%22%3A+%22segmentation_enabled%22%7D%2C+%7B%22name%22%3A+%22COMPRESSI
ON%22%2C+%22value%22%3A+%22ETC2_COMPRESSION%22%7D%2C+%7B%22name%22%3A+%22world_tracker%22%2C+%22value%22%3A+%22world_tracker_enabled%22%7D%2C+%7B%22name%22%3A+%22gyroscope%22%2C+%22value%22
%3A+%22gyroscope_enabled%22%7D%5D (Caused by SSLError(OSError(24, 'Too many open files')))
bash: syntax error near unexpected token `Caused'```

**Comment by adw0rd** [comment]
@riccardolunardi Too many file descriptors are open, I'll see if they are not closing properly in the instagrapi

And I advise you to increase them in your system

**Comment by adw0rd** [comment]
I closed all file descriptors, if the error persists, then only for local reasons (see your ulimits or reduce the number of concurrent requests)
