### ISSUE TITLE
[BUG] Pydantic throws error on story upload.

### ISSUE THREAD

**Issue by xIvan0ff** [adw0rd/instagrapi#1881]
**Describe the bug**
Pydantic says that '_is_paid_partnership_' field is required in order to post a story.

**To Reproduce**
```python
client = Client()
client.login('xxx', 'xxx')

story = client.photo_upload_to_story('FAQS.png')
print(story)
```

**Traceback**
```
Traceback (most recent call last):
  File "\test.py", line 8, in <module>
    story = client.photo_upload_to_story('FAQS.png')
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\photo.py", line 417, in photo_upload_to_story
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Story
is_paid_partnership
  Field required [type=missing, input_value={'links': [], 'mentions':...], 'clips_metadata': {}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

```
**Expected behavior**
Should not give errors.

**Desktop (please complete the following information):**
 - OS: Python
 - Python version 3.10.5
 - instagrapi version 2.1.1

**Comment by tajbowness** [comment]
Similar issue:

https://github.com/subzeroid/instagrapi/issues/1851#issue-2204514201

**Comment by subzeroid** [comment]
Closing this as fixed in current releases.

This was the same `Story.is_paid_partnership` validation failure discussed in #1851. Current `master` defines `Story.is_paid_partnership` with a default value of `False`, so a story payload without that field no longer raises the reported Pydantic "Field required" error. I also verified the current model accepts a valid minimal `Story` payload without explicitly passing `is_paid_partnership`.
