### ISSUE TITLE
Json error in user_info()

### ISSUE THREAD

**Issue by AsianZeus** [adw0rd/instagrapi#201]
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/instagrapi/mixins/user.py", line 260, in user_info
    user = self.user_info_gql(user_id)
  File "/opt/homebrew/lib/python3.9/site-packages/instagrapi/mixins/user.py", line 213, in user_info_gql
    return self.user_info_by_username_gql(self.username_from_user_id_gql(user_id))
  File "/opt/homebrew/lib/python3.9/site-packages/instagrapi/mixins/user.py", line 139, in user_info_by_username_gql
    return extract_user_gql(self.public_a1_request(f"/{username!s}/")["user"])
  File "/opt/homebrew/lib/python3.9/site-packages/instagrapi/mixins/public.py", line 166, in public_a1_request
    response = self.public_request(
  File "/opt/homebrew/lib/python3.9/site-packages/instagrapi/mixins/public.py", line 65, in public_request
    return self._send_public_request(url, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/instagrapi/mixins/public.py", line 125, in _send_public_request
    return response.json() if return_json else response.text
  File "/opt/homebrew/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by adw0rd** [comment]
@AsianZeus Instagram has blocked you, try user_info_v1() instead user_info()

**Comment by adw0rd** [comment]
user_info_gql works fine for me:

```
cl.user_info_gql(cl.user_id).full_name
'Mikhail Andreev'
```
