### ISSUE TITLE
KeyError: 'media_type' when call cl.story_delete

### ISSUE THREAD

**Issue by adw0rd** [adw0rd/instagrapi#228]
```
cl = Client(set1)
a = cl.story_delete(2605174909241363149)

Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\public.py", line 125, in _send_public_request
    return response.json() if return_json else response.text
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\media.py", line 237, in media_info
    media = self.media_info_gql(media_pk)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\media.py", line 182, in media_info_gql
    data = self.public_graphql_request(
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\public.py", line 203, in public_graphql_request
    body_json = self.public_request(
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\public.py", line 72, in public_request
    raise e
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\public.py", line 65, in public_request
    return self._send_public_request(url, **kwargs)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\public.py", line 129, in _send_public_request
    raise ClientLoginRequired(e, response=response)
instagrapi.exceptions.ClientLoginRequired: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\media.py", line 241, in media_info
    media = self.media_info_gql(media_pk)  # retry
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\media.py", line 191, in media_info_gql
    return extract_media_gql(data["shortcode_media"])
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\extractors.py", line 80, in extract_media_gql
    if media["media_type"] == 2 and not media.get("product_type"):
KeyError: 'media_type'
```

**Comment by adw0rd** [comment]
Fixed in 1.7.18
