### ISSUE TITLE
LoginRequired: login_required Error

### ISSUE THREAD

**Issue by adw0rd** [adw0rd/instagrapi#255]
### Discussed in https://github.com/adw0rd/instagrapi/discussions/254

<div type='discussions-op-text'>

<sup>Originally posted by **kunal52** July  8, 2021</sup>
When calling auth/login this exception will occured instagrapi.exceptions.LoginRequired: login_required .
However I will received login success email in my mailbox. 

```
INFO:     contact@brtracker.com [429] POST https://i.instagram.com/api/v1/accounts/contact_point_prefill/ (169.3.0.30.135, Xiaomi capricorn)
WARNING:  Status 429: Too many requests
INFO:     contact@brtracker.com [200] POST https://i.instagram.com/api/v1/accounts/login/ (169.3.0.30.135, Xiaomi capricorn)
INFO:     contact@brtracker.com [403] POST https://i.instagram.com/api/v1/feed/timeline/ (169.3.0.30.135, Xiaomi capricorn)
INFO:     172.17.0.1:58156 - "GET /auth/login HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "./routers/auth.py", line 21, in auth_login
    result = cl.login(
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/auth.py", line 378, in login
    self.login_flow()
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/auth.py", line 159, in login_flow
    check_flow.append(self.get_timeline_feed([chance and "is_pull_to_refresh"]))
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/auth.py", line 215, in get_timeline_feed
    return self.private_request(
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 321, in private_request
    raise e
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 308, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 209, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required
```</div>

**Comment by adw0rd** [comment]
Duplicate #252
