### ISSUE TITLE
login_required error

### ISSUE THREAD

**Issue by EsmaeiliSina** [adw0rd/instagrapi#260]
Hi @adw0rd.
I had the login_required error and read the previous issues and updated, but the problem still exists for me.
instagrapi=1.8.3

```
Traceback (most recent call last):
  File "\mixins\public.py", line 125, in _send_public_request
    return response.json() if return_json else response.text
  File "\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\mixins\hashtag.py", line 422, in hashtag_medias_recent
    raise e
  File "\mixins\hashtag.py", line 419, in hashtag_medias_recent
    medias = self.hashtag_medias_recent_a1(name, amount)
  File "\mixins\hashtag.py", line 381, in hashtag_medias_recent_a1
    return self.hashtag_medias_a1(name, amount, tab_key="edge_hashtag_to_media")
  File "\mixins\hashtag.py", line 216, in hashtag_medias_a1
    medias, _ = self.hashtag_medias_a1_chunk(name, amount, tab_key)
  File "\mixins\hashtag.py", line 160, in hashtag_medias_a1_chunk
    data = self.public_a1_request(
  File "\mixins\public.py", line 166, in public_a1_request
    response = self.public_request(
  File "\mixins\public.py", line 72, in public_request
    raise e
  File "\mixins\public.py", line 65, in public_request
    return self._send_public_request(url, **kwargs)
  File "\mixins\public.py", line 129, in _send_public_request
    raise ClientLoginRequired(e, response=response)
instagrapi.exceptions.ClientLoginRequired: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\mixins\private.py", line 219, in _send_private_request
    response.raise_for_status()
  File "\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/tags/%D9%85%D8%B1%D8%A8%D8%A7/sections/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sina\Desktop\new api\test.py", line 30, in <module>
    media = cl.hashtag_medias_recent(name=hashtags[c],amount=10)
  File "\mixins\hashtag.py", line 427, in hashtag_medias_recent
    medias = self.hashtag_medias_recent_v1(name, amount)
  File "\mixins\hashtag.py", line 399, in hashtag_medias_recent_v1
    return self.hashtag_medias_v1(name, amount, tab_key="recent")
  File "\mixins\hashtag.py", line 295, in hashtag_medias_v1
    medias, _ = self.hashtag_medias_v1_chunk(name, amount, tab_key)
  File "\instagrapi\mixins\hashtag.py", line 252, in hashtag_medias_v1_chunk
    result = self.private_request(
  File "\instagrapi\mixins\private.py", line 361, in private_request
    raise e
  File "\instagrapi\mixins\private.py", line 348, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "\instagrapi\mixins\private.py", line 244, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required
```

**Comment by adw0rd** [comment]
@EsmaeiliSina Show your code, I want to understand what you called to get the error

**Comment by adw0rd** [comment]
Works fine:

```
from instagrapi import Client
cl = Client()
cl.login(USERNAME, PASSWORD)

cl.hashtag_medias_recent('مربا')
[Media(pk=2615495199761215566, id='2615495199761215566_34691246705', code='CRMGwbVgbBO', taken_at=datetime.datetime(2021, 7, 11, 13, 49, 6, tzinfo=datetime.timezone.utc), media_type=8, product_type='carousel_container', thumbnail_url=None, location=None, user=UserShort(pk=34691246705, username='hanoot__', full_name='♥️حانوت♥️', profile_pic_url=HttpUrl('https://instagram.frix7-1.fna.fbcdn.net/v/t51.2885-19/s150x150/209531285_534467271079583_7227134077474859908_n.jpg?_nc_ht=instagram.frix7-1.fna.fbcdn.net&_nc_ohc=Hm4zKgnnKGIAX9F3tcH&edm=AMKDjl4BAAAA&ccb=7-4&oh=98aeb9796373b833e8b16aeaf5e58327&oe=60F1872C&_nc_sid=1fe099', scheme='https', host='instagram.frix7-1.fna.fbcdn.net', tld='net', host_type='domain', path='/v/t51.2885-19/s150x150/209531285_534467271079583_7227134077474859908_n.jpg', query='_nc_ht=instagram.frix7-1.fna.fbcdn.net&_nc_ohc=Hm4zKgnnKGIAX9F3tcH&edm=AMKDjl4BAAAA&ccb=7-4&oh=98aeb9796373b833e8b16aeaf5e58327&oe=60F1872C&_nc_sid=1fe099'), profile_pic_url_hd=None, stories=[]), comment_count=0, like_count=0, has_liked=False, caption_text='ایده بگیریم ♥️🌸🌸\n\nچند نمونه از چیدمان میز صبحانه🍧🥃🍷🌼\nعزیزان لایک و کامنت یادتون نره 🙏♥️♥️\n\n#چیدمان#صبحانه #اشپزی \n#مربا خانگی#میز صبحانه\n#چای#کدبانو #باسلیقه \n#اشپزخانه#ظرف زیبا\n#دکوراسیون', usertags=[], video_url=None, view_count=0, video_duration=0.0, title='', resources=[Resource(pk=2615495195482933271, video_url=None, thumbnail_url=HttpUrl('https://instagram.frix7-1.fna.fbcdn.net/v/t51.2885-15/e35/214287372_307853177734950_5348023541013661169_n.jpg?_nc_ht=instagram.frix7-1.fna.fbcdn.net&_nc_cat=106&_nc_ohc=fx3BuY0XZlEAX91bssZ&edm=AMKDjl4BAAAA&ccb=7-4&oh=05badcc16cea42fa4b512dba6ef01e8d&oe=60F267CB&_nc_sid=1fe099&ig_cache_key=MjYxNTQ5NTE5NTQ4MjkzMzI3MQ%3D%3D.2-ccb7-4', scheme='https', host='instagram.frix7-1.fna.fbcdn.net', tld='net', host_type='domain', path='/v/t51.2885-15/e35/214287372_307853177734950_5348023541013661169_n.jpg', query='_nc_ht=instagram.frix7-1.fna.fbcdn.net&_nc_cat=106&_nc_ohc=fx3BuY0XZlEAX91bssZ&edm=AMKDjl4BAAAA&ccb=7-4&oh=05badcc16cea42fa4b512dba6ef01e8d&oe=60F267CB&_nc_sid=1fe099&ig_cache_key=MjYxNTQ5NTE5NTQ4MjkzMzI3MQ%3D%3D.2-ccb7-4'), media_type=1), Resource(pk=2615495195499843993, video_url=None, thumbnail_url=HttpUrl('https://instagram.frix7-1.fna.fbcdn.net/v/t51.2885-15/e35/212042511_608331950139678_6893729647972893940_n.jpg?tp=1&_nc_ht=instagram.frix7-1.fna.fbcdn.net&_nc_cat=106&_nc_ohc=uJORs5IjaksAX9nUaQa&edm=AMKDjl4BAAAA&ccb=7-4&oh=72e41c6369e6f24f8784c44e524db764&oe=60F299F1&_nc_sid=1fe099&ig_cache_key=MjYxNTQ5NTE5NTQ5OTg0Mzk5Mw%3D%3D.2-ccb7-4', scheme='https', host='instagram.frix7-1.fna.fbcdn.net', tld='net', host_type='domain', path='/v/t51.2885-15/e35/212042511_608331950139678_6893729647972893940_n.jpg', query='tp=1&_nc_ht=instagram.frix7-1.fna.fbcdn.net&_nc_cat=106&_nc_ohc=uJORs5IjaksAX9nUaQa&edm=AMKDjl4BAAAA&ccb=7-4&oh=72e41c6369e6f24f8784c44e524db764&oe=60F299F1&_nc_sid=1fe099&ig_cache_key=MjYxNTQ5NTE5NTQ5OTg0Mzk5Mw%3D%3D.2-ccb7-4'), media_type=1), Resource(pk=2615495195525025923, video_url=None, thumbnail_url=HttpUrl('https://instagram.frix7-1.fna.fbcdn.net/v/t51.2885-15/e35/213771574_959121734663510_4437157017166462256_n.jpg?tp=1&_nc_ht=instagram.frix7-1.fna.fbcdn.net&_nc_cat=102&_nc_ohc=tiws0FE3a28AX_W1zQL&edm=AMKDjl4BAAAA&ccb=7-4&oh=a06d9a175ec9d8ad507a463c3cdd8b0b&oe=60F24D1E&_nc_sid=1fe099&ig_cache_key=MjYxNTQ5NTE5NTUyNTAyNTkyMw%3D%3D.2-ccb7-4', scheme='https', host='instagram.frix7-1.fna.fbcdn.net', tld='net', host_type='domain', path='/v/t51.2885-15/e35/213771574_959121734663510_4437157017166462256_n.jpg', query='tp=1&_nc_ht=instagram.frix7-1.fna.fbcdn.net&_nc_cat=102&_nc_ohc=tiws0FE3a28AX_W1zQL&edm=AMKDjl4BAAAA&ccb=7-4&oh=a06d9a175ec9d8ad507a463c3cdd8b0b&oe=60F24D1E&_nc_sid=1fe099&ig_cache_key=MjYxNTQ5NTE5NTUyNTAyNTkyMw%3D%3D.2-ccb7-4'), media_type=1)]),
...
```
