### ISSUE TITLE
KeyError: 'graphql' on hashtag_medias_top call

### ISSUE THREAD

**Issue by jdiaz-kindalab** [adw0rd/instagrapi#285]
Hi, I'm getting this error while calling at hashtag_medias_top. Even with this error, the function seems to be working fine but it's adding some noise to my logs.

This is how I'm using the library:

```
from instagrapi import Client

cl.login(instagram_username, instagram_password)
hashtag = cl.hashtag_medias_top('somehash', amount=20)
```

And I'm getting this output in the console

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/instagrapi/mixins/hashtag.py", line 354, in hashtag_medias_top
    medias = self.hashtag_medias_top_a1(name, amount)
  File "/usr/local/lib/python3.9/site-packages/instagrapi/mixins/hashtag.py", line 316, in hashtag_medias_top_a1
    return self.hashtag_medias_a1(name, amount, tab_key="edge_hashtag_to_top_posts")
  File "/usr/local/lib/python3.9/site-packages/instagrapi/mixins/hashtag.py", line 216, in hashtag_medias_a1
    medias, _ = self.hashtag_medias_a1_chunk(name, amount, tab_key)
  File "/usr/local/lib/python3.9/site-packages/instagrapi/mixins/hashtag.py", line 160, in hashtag_medias_a1_chunk
    data = self.public_a1_request(
  File "/usr/local/lib/python3.9/site-packages/instagrapi/mixins/public.py", line 178, in public_a1_request
    raise e
  File "/usr/local/lib/python3.9/site-packages/instagrapi/mixins/public.py", line 170, in public_a1_request
    return response["graphql"]
KeyError: 'graphql'
```

Thanks!

**Comment by adw0rd** [comment]
Instagram has recently stopped giving a "graphql" response for authorized users.
In version 1.12.12, I take this into account for hashtags
