### ISSUE TITLE
challenge_required error login to any account on any ip

### ISSUE THREAD

**Issue by klaytonpaiva** [adw0rd/instagrapi#331]
**Describe the bug**
Any account that logs in, even using another IP or VPN, reports the challenge_required error and asks you to confirm your identity.
In accounts where instagrapi was used, I can login and logout by browsing after verifying the account, but when I use the instagrapi login, it accuses challenge_required

**To Reproduce**
from instagrapi import Client

cl = Client()
cl.login('username', 'pass')# username e password instagram

user_id = cl.user_id_from_username("adw0rd")
medias = cl.user_medias(user_id, 20)

**Traceback**
Traceback (most recent call last):
  File "C:\Users\Klayton\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 255, in _send_private_request
    response.raise_for_status()
  File "C:\Users\Klayton\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Klayton\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 385, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\Klayton\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 285, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Klayton\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 255, in _send_private_request
    response.raise_for_status()
  File "C:\Users\Klayton\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Klayton\Desktop\Bot\BotInstagram\BotInstaMont\exemplo_login.py", line 4, in <module>
    cl.login('felipealvespereira29', '7ZTUEZtklmKz')
  File "C:\Users\Klayton\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\auth.py", line 383, in login
    logged = self.private_request("accounts/login/", data, login=True)
  File "C:\Users\Klayton\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 402, in private_request
    return self._send_private_request(endpoint, **kwargs)
  File "C:\Users\Klayton\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 285, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

**Expected behavior**
Until 12/08/2021 it worked normally.

**Screenshots**
![echallenge_required 1](https://user-images.githubusercontent.com/37090194/129453069-55d3e1e5-31fb-4f38-b908-24e9588e13ae.jpg)
![echallenge_required 2](https://user-images.githubusercontent.com/37090194/129453104-2678964a-34e0-49d6-8dcf-fb934fd6e35a.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Python version [e.g. 3.9]
 - instagrapi version [e.g. 1.9.14"]

**Additional context**
I've updated instagrapi, I've already looked for help to solve it but I couldn't.

NOTE: Using Google translator.

**Comment by Jammy108** [comment]
Also getting this, a loop of endless challenge_required errors.

**Comment by New-dev0** [comment]
Same for me 🙁

**Comment by elmissouri16** [comment]
similar situation for me to accounts start getting challenge required lot even if change proxies while back was fine but recently start happening lot

**Comment by adw0rd** [comment]
Fixed in 1.9.18

**Comment by New-dev0** [comment]
Thanks adw0rd 🥳 👍
