### ISSUE TITLE
Get posts by location is not working it shows login _required 

### ISSUE THREAD

**Issue by dheeraj009joshi** [adw0rd/instagrapi#332]
**Describe the bug**
i am want to get posts for  location but that shows login required but i am already loged in 

**To Reproduce**

usernamee=[]
medias = cl.location_medias_top(21657666681,50)
print(type(medias))
print(medias)
for data in medias:
    item=data.json()
    print(type(item))
    i=json.loads(item)
    print(type(i))
    usernamee.append(i["user"]["username"])

**Traceback**
valid credentials.json
Traceback (most recent call last):
  File "c:\Users\dell\Desktop\ig_api\instagrapi\instagrapi\mixins\private.py", line 255, in _send_private_request
    response.raise_for_status()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/location_search/?latitude=33.9529897803&longitude=-83.3747935295

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\dell\Desktop\ig_api\instagrapi\location.py", line 71, in <module>
    medias = cl.location_medias_top(21657666681,50)
  File "c:\Users\dell\Desktop\ig_api\instagrapi\instagrapi\mixins\location.py", line 250, in location_medias_top
    return self.location_medias_top_a1(location_pk, amount, sleep)
  File "c:\Users\dell\Desktop\ig_api\instagrapi\instagrapi\mixins\location.py", line 225, in location_medias_top_a1
    return self.location_medias_a1(
  File "c:\Users\dell\Desktop\ig_api\instagrapi\instagrapi\mixins\location.py", line 192, in location_medias_a1
    medias.append(self.media_info_gql(node["id"]))
  File "c:\Users\dell\Desktop\ig_api\instagrapi\instagrapi\mixins\media.py", line 188, in media_info_gql
    data["shortcode_media"]["location"] = self.location_complete(
  File "c:\Users\dell\Desktop\ig_api\instagrapi\instagrapi\mixins\location.py", line 75, in location_complete
    venue = self.location_search(location.lat, location.lng)[0]
  File "c:\Users\dell\Desktop\ig_api\instagrapi\instagrapi\mixins\location.py", line 41, in location_search
    result = self.private_request("location_search/", params=params)
  File "c:\Users\dell\Desktop\ig_api\instagrapi\instagrapi\mixins\private.py", line 398, in private_request
    raise e
  File "c:\Users\dell\Desktop\ig_api\instagrapi\instagrapi\mixins\private.py", line 385, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "c:\Users\dell\Desktop\ig_api\instagrapi\instagrapi\mixins\private.py", line 280, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required

**Expected behavior**
i simply expect to get the posts for that specific location id

**Screenshots**
![image](https://user-images.githubusercontent.com/73873399/129568322-a22c98dc-4c07-4ea0-b009-39b0f00a27ae.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 21.04]
 - Python version [e.g. 3.8.3]=3.9.5
 - instagrapi version [e.g. 1.9.3, not "latest"]
 - moveipy version if used
 - imagemagick version if used

**Additional context**

**Comment by adw0rd** [comment]
@dheeraj009joshi use instagrapi 1.9.19 and `cl.inject_sessionid_to_public()`

**Comment by dheeraj009joshi** [comment]
hlw @adw0rd plz show me a demo so i can do this actually i am not sure how and where to use cl.inject_sessionid_to_public() this method

**Comment by adw0rd** [comment]
@dheeraj009joshi released 1.11.0 with private-api methods for location:

![image](https://user-images.githubusercontent.com/546889/130287270-024cad2d-f1de-47bf-8519-22c19cd4b9f9.png)
