### ISSUE TITLE
[BUG] Error graphql in hashtag_info()

### ISSUE THREAD

**Issue by jrvilda** [adw0rd/instagrapi#364]
**Describe the bug**

Error getting hashtag_info object

**To Reproduce**
    tag= cl.hashtag_info("sssss")
    print(json.dumps(tag.dict(), indent=4, sort_keys=True))

**Traceback**
'graphql'
Traceback (most recent call last):
  File "\.venv\lib\site-packages\instagrapi\mixins\hashtag.py", line 106, in hashtag_info
    hashtag = self.hashtag_info_a1(name)
  File "\.venv\lib\site-packages\instagrapi\mixins\hashtag.py", line 37, in hashtag_info_a1
    data = self.public_a1_request(f"/explore/tags/{name}/", params=params)
  File "\.venv\lib\site-packages\instagrapi\mixins\public.py", line 184, in public_a1_request
    raise e
  File "\.venv\lib\site-packages\instagrapi\mixins\public.py", line 176, in public_a1_request
    return response["graphql"]
KeyError: 'graphql'

**Desktop (please complete the following information):**
 - OS: windows 10
 - Python version 3.7
 - instagrapi version 1.12.16
 - graphql-core 3.1.6

**Comment by adw0rd** [comment]
@jrvilda this is not an error, I am internal information that is published to cl.logger (which is output to stdout by default)

![image](https://user-images.githubusercontent.com/546889/132101732-0e1de853-b0e0-4055-834c-86529a64d73f.png)

After the traceback is displayed, you can access the "tag"

**Comment by adw0rd** [comment]
I hide these debug tracebacks so as not to confuse users 
instagrapi 1.12.17
