### ISSUE TITLE
[BUG] Media not found or unavailable (media_info)

### ISSUE THREAD

**Issue by Soneji** [adw0rd/instagrapi#373]
When I run `cl.media_info(2655230362137838000, False)` it does this. Not sure why

```py
>> cl.media_info(2655230362137838000, False)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/public.py", line 129, in _send_public_request
    self.last_public_json = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/media.py", line 237, in media_info
    media = self.media_info_gql(media_pk)
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/media.py", line 182, in media_info_gql
    data = self.public_graphql_request(
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/public.py", line 209, in public_graphql_request
    body_json = self.public_request(
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/public.py", line 73, in public_request
    raise e  # Stop retries
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/public.py", line 71, in public_request
    return self._send_public_request(url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/public.py", line 135, in _send_public_request
    raise ClientLoginRequired(e, response=response)
instagrapi.exceptions.ClientLoginRequired: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/media.py", line 241, in media_info
    media = self.media_info_gql(media_pk)  # retry
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/media.py", line 186, in media_info_gql
    raise MediaNotFound(media_pk=media_pk, **data)
instagrapi.exceptions.MediaNotFound: Unknown ({'media_pk': 2655230362137838000, 'shortcode_media': None})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 271, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/2655230362137838000/info/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/media.py", line 208, in media_info_v1
    result = self.private_request(f"media/{media_pk}/info/")
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 416, in private_request
    raise e
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 403, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 327, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: Media not found or unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/media.py", line 247, in media_info
    media = self.media_info_v1(media_pk)
  File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/media.py", line 213, in media_info_v1
    raise MediaNotFound(e, media_pk=media_pk, **self.last_json)
instagrapi.exceptions.MediaNotFound: Media not found or unavailable
```

**Comment by adw0rd** [comment]
@Soneji does the post exist? provide a link to it

**Comment by adw0rd** [comment]
@Soneji 

```
from instagrapi.utils import InstagramIdCodec

>>> InstagramIdCodec.encode(2655230362137838000)
'CTZRfJEDsGw'
```

https://www.instagram.com/p/CTZRfJEDsGw/

![image](https://user-images.githubusercontent.com/546889/133161779-9e8e9fd1-705d-4059-809c-d098188bc57b.png)

**Comment by Soneji** [comment]
![image](https://user-images.githubusercontent.com/12625848/133162477-358aff3e-ff5b-47f0-99de-7c9b7949bbd0.png)
Maybe the issue is the ​/media​/pk_from_url endpoint then...
What should "https://www.instagram.com/p/CTZRfJEDsE7/" generate?

**Comment by adw0rd** [comment]
I do not understand what exactly confuses you?
pk is obtained from code by decoding, nothing else

https://github.com/adw0rd/instagrapi/blob/master/instagrapi/utils.py#L12
