### ISSUE TITLE
 anonymous access 

### ISSUE THREAD

**Issue by 89z** [adw0rd/instagrapi#383]
I read here [1] that anonymous access is supported, but I dont think it is. Using this program:

~~~py
from instagrapi import Client
cl = Client()
cl.media_info(1787135824035452364).dict()
~~~

I get this result:

~~~
Traceback (most recent call last):
  File "C:\python\lib\site-packages\instagrapi\mixins\public.py", line 129, in _send_public_request
    self.last_public_json = response.json()
  File "C:\python\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python\lib\site-packages\instagrapi\mixins\media.py", line 240, in media_info
    raise e
  File "C:\python\lib\site-packages\instagrapi\mixins\media.py", line 237, in media_info
    media = self.media_info_gql(media_pk)
  File "C:\python\lib\site-packages\instagrapi\mixins\media.py", line 182, in media_info_gql
    data = self.public_graphql_request(
  File "C:\python\lib\site-packages\instagrapi\mixins\public.py", line 209, in public_graphql_request
    body_json = self.public_request(
  File "C:\python\lib\site-packages\instagrapi\mixins\public.py", line 73, in public_request
    raise e  # Stop retries
  File "C:\python\lib\site-packages\instagrapi\mixins\public.py", line 71, in public_request
    return self._send_public_request(url, **kwargs)
  File "C:\python\lib\site-packages\instagrapi\mixins\public.py", line 135, in _send_public_request
    raise ClientLoginRequired(e, response=response)
instagrapi.exceptions.ClientLoginRequired: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python\lib\site-packages\instagrapi\mixins\private.py", line 270, in _send_private_request
    response.raise_for_status()
  File "C:\python\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/media/1787135824035452364/info/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Desktop\ig.py", line 6, in <module>
    cl.media_info(1787135824035452364).dict()
  File "C:\python\lib\site-packages\instagrapi\mixins\media.py", line 247, in media_info
    media = self.media_info_v1(media_pk)
  File "C:\python\lib\site-packages\instagrapi\mixins\media.py", line 214, in media_info_v1
    raise e
  File "C:\python\lib\site-packages\instagrapi\mixins\media.py", line 208, in media_info_v1
    result = self.private_request(f"media/{media_pk}/info/")
  File "C:\python\lib\site-packages\instagrapi\mixins\private.py", line 415, in private_request
    raise e
  File "C:\python\lib\site-packages\instagrapi\mixins\private.py", line 402, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\python\lib\site-packages\instagrapi\mixins\private.py", line 295, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required
~~~

1. https://github.com/adw0rd/instagrapi#features

**Comment by adw0rd** [comment]
It's not bug.

```
  File "C:\python\lib\site-packages\instagrapi\mixins\private.py", line 295, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required
```

Instagram requires you to log in, you need to do this
