### ISSUE TITLE
Doesn't work with pyinstaller

### ISSUE THREAD

**Issue by trashmit** [adw0rd/instagrapi#39]
Probably a minor issue but something that will help me and alot of others in the long term.

Basically i tried to turn a program of mine that uses this module to an exe using pyinstaller but it doesn't work, i did some testing and using a script to just try to login to instagram with this module doesn't work when used with pyinstaller. I was getting an ImportError in both cases.

I was looking around for solutions and came across this issue https://github.com/explosion/spaCy/issues/5035 and it was fixed by someone creating a hook for the module and wondering if any of you could make one for this module. 

Thanks

**Comment by adw0rd** [comment]
If something does not work in pyinstaller, then it should be solved there. The instagrapi library itself is working correctly

**Comment by trashmit** [comment]
still trying to fix,

`Traceback (most recent call last):
  File "downloader.py", line 1, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "instagrapi\__init__.py", line 12, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "instagrapi\photo.py", line 13, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "instagrapi\extractors.py", line 4, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "instagrapi\types.py", line 6, in <module>
  File "pydantic\main.py", line 262, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 315, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 284, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 362, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 538, in pydantic.fields.ModelField.populate_validators
  File "pydantic\validators.py", line 595, in find_validators
  File "pydantic\dataclasses.py", line 77, in pydantic.dataclasses.is_builtin_dataclass
ModuleNotFoundError: No module named 'dataclasses'` 

is the error i am getting in the exe, it works completely fine in idle ;(

**Comment by mikebgrep** [comment]
> Probably a minor issue but something that will help me and alot of others in the long term.
> 
> Basically i tried to turn a program of mine that uses this module to an exe using pyinstaller but it doesn't work, i did some testing and using a script to just try to login to instagram with this module doesn't work when used with pyinstaller. I was getting an ImportError in both cases.
> 
> I was looking around for solutions and came across this issue [explosion/spaCy#5035](https://github.com/explosion/spaCy/issues/5035) and it was fixed by someone creating a hook for the module and wondering if any of you could make one for this module.
> 
> Thanks

You manage to find solution I also have a problem with pyinstaller
