### ISSUE TITLE
instagrapi.exceptions.RateLimitError

### ISSUE THREAD

**Issue by 89z** [adw0rd/instagrapi#394]
Using this program:

~~~py
from instagrapi import Client
cl = Client()
cl.login('srpen6', 'PASSWORD')
~~~

I get this result:

~~~
Status 429: Too many requests
Ignore 429: Continue login
Traceback (most recent call last):
  File "C:\python\lib\site-packages\instagrapi\mixins\private.py", line 270, in _send_private_request
    response.raise_for_status()
  File "C:\python\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Desktop\ig.py", line 4, in <module>
    cl.login('srpen6', 'PASSWORD')
  File "C:\python\lib\site-packages\instagrapi\mixins\auth.py", line 387, in login
    logged = self.private_request("accounts/login/", data, login=True)
  File "C:\python\lib\site-packages\instagrapi\mixins\private.py", line 415, in private_request
    raise e
  File "C:\python\lib\site-packages\instagrapi\mixins\private.py", line 402, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\python\lib\site-packages\instagrapi\mixins\private.py", line 314, in _send_private_request
    raise RateLimitError(**last_json)
instagrapi.exceptions.RateLimitError: Please wait a few minutes before you try again.
~~~

**Comment by adw0rd** [comment]
RateLimitError - read this https://github.com/adw0rd/instagrapi/discussions/299
