### ISSUE TITLE
Error 429 following followers 

### ISSUE THREAD

**Issue by jaimecoj** [adw0rd/instagrapi#40]
I get error 429. Any way to bypass it? Tried using proxy but same error.

Code:
```
from instagrapi import Client
import sys

cl = Client()
cl.set_proxy("http://XXXXX:XXXXX")
print("Logging in...")
cl.login(sys.argv[1], sys.argv[2])
print("Getting followerws of "+sys.argv[3])
follow_id = cl.user_id_from_username(sys.argv[3])

to_follow = cl.user_followers_v1(follow_id)
count = 0
for tf_id, tf_data in to_follow.items():
    count += 1
    print("Following user "+tf_data.username+" "+str(count)+"/"+str(len(to_follow)))
    cl.user_follow(tf_id)
```

Log:
```
Logging in...
Getting followerws of XXXXX
Status 429: Too many requests
Traceback (most recent call last):
  File "C:\Users\Jaime\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instagrapi\private.py", line 181, in _send_private_request
    response.raise_for_status()
  File "C:\Users\Jaime\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg + "\nBody: "+self.text, response=self)
requests.exceptions.HTTPError: 429 Client Error: - for url: https://i.instagram.com/api/v1/friendships/XXXXX/followers/?max_id=&rank_token=XXXXX
Body: {"message": "Please wait a few minutes before you try again.", "status": "fail"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\follow2.py", line 11, in <module>
    to_follow = cl.user_followers_v1(follow_id)
  File "C:\Users\Jaime\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instagrapi\user.py", line 230, in user_followers_v1
    result = self.private_request(
  File "C:\Users\Jaime\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instagrapi\private.py", line 313, in private_request
    raise e
  File "C:\Users\Jaime\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instagrapi\private.py", line 300, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\Jaime\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instagrapi\private.py", line 242, in _send_private_request
    raise PleaseWaitFewMinutes(e, response=e.response, **last_json)
instagrapi.exceptions.PleaseWaitFewMinutes: Please wait a few minutes before you try again.
```

**Comment by adw0rd** [comment]
You make requests too often, add timeouts in cycle. You exceed your Instagram limits.
And wait few minutes)
