### ISSUE TITLE
ModuleNotFoundError: No module named 'instagrapi.mixins' Trying to deploy on heroku

### ISSUE THREAD

**Issue by mikebgrep** [adw0rd/instagrapi#45]
I am trying to deploy on heroku its install put return me this error.Any advice

Traceback (most recent call last):
  File "after_loop.py", line 1, in <module>
    from instagrapi import Client
  File "/app/.heroku/python/lib/python3.6/site-packages/instagrapi/__init__.py", line 4, in <module>
    from instagrapi.mixins.auth import LoginMixin
ModuleNotFoundError: No module named 'instagrapi.mixins'

**Comment by alimardani1994** [comment]
I am getting this error too. 
from instagrapi import client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\instagrapi\__init__.py", line 4, in <module>
    from instagrapi.mixins.auth import LoginMixin

**Comment by adw0rd** [comment]
Fix it today

**Comment by mikebgrep** [comment]
Still showing the error in heroku.

**Comment by adw0rd** [comment]
Fixed `pip install instagrapi==1.3.2`
