### ISSUE TITLE
Error installing module

### ISSUE THREAD

**Issue by daVinci13** [adw0rd/instagrapi#5]
```
pip install instagrapi
Collecting instagrapi
  Using cached instagrapi-1.1.6.tar.gz (43 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\neman\\AppData\\Local\\Temp\\pip-install-qsq4ll05\\instagrapi\\setup.py'"'"'; __file__='"'"'C:\\Users\\neman\\AppData\\Local\\Temp\\pip-install-qsq4ll05\\instagrapi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\neman\AppData\Local\Temp\pip-pip-egg-info-53fxevhp'
         cwd: C:\Users\neman\AppData\Local\Temp\pip-install-qsq4ll05\instagrapi\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\neman\AppData\Local\Temp\pip-install-qsq4ll05\instagrapi\setup.py", line 13, in <module>
        install_requires=[item.strip() for item in open(
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\neman\\AppData\\Local\\Temp\\pip-install-qsq4ll05\\instagrapi\\requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by adw0rd** [comment]
Fixed
