### ISSUE TITLE
[BUG] How to handle exception on user has turned off comments for this post

### ISSUE THREAD

**Issue by Chuckler22** [adw0rd/instagrapi#506]
### Compensate with donations ($10 and more) for the time I spent to fix problems or send  me your [Pull Request](https://github.com/adw0rd/instagrapi/pulls) with fixes

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

* Bitcoin: 3KHgnvNNWio6wyQ71cgNeBQojXStxzkzfd
* Ethereum: 0x6e644c6b975B47801072b07a9a57DDfEC10DE74F
* https://paypal.me/adw0rd
* For Russia: СБП, Qiwi и тп: **+79118107609**

**Describe the bug**
When attempting to comment on a post where the author has turned off comments, the system throws an exception and can't recover (or at least I don't know how to). 

**To Reproduce**
Attempt to post a comment to a post where the author has turned off comments for the post. 

**Traceback**
See Below. 

**Expected behavior**
I'm using try, except, finally to attempt to carry on regardless of this error, but that doesn't work. 
```
                try:
                    cl.media_comment(str(x[1]),str(x[2]))
                except Exception:
                    sys.excepthook = handle_exception
                    if __name__ == "__main__":
                        raise RuntimeError("Test unhandled")
                finally:
                    pass
```

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 21.04].  _PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"_
 - Python version [e.g. 3.8.3]. _Python 3.7.12_
 - instagrapi version [e.g. 1.9.3, not "latest"].  _instagrapi             1.15.20_
 - moveipy version if used. _not used_
 - imagemagick version if used. _not used_

**Additional context**

Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/2xxxxxxxxxxxxx774/comment/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insta.py", line 168, in update_comments
    cl.media_comment(str(x[1]),str(x[2]))
  File "/usr/local/lib/python3.7/site-packages/instagrapi/mixins/comment.py", line 98, in media_comment
    self.with_action_data(data),
  File "/usr/local/lib/python3.7/site-packages/instagrapi/mixins/private.py", line 445, in private_request
    raise e
  File "/usr/local/lib/python3.7/site-packages/instagrapi/mixins/private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/instagrapi/mixins/private.py", line 336, in _send_private_request
    % (message, last_json.get("feedback_message")),
instagrapi.exceptions.FeedbackRequired: feedback_required: xxxxxxxxxx has turned off comments for this post.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insta.py", line 204, in <module>
    update_comments()
  File "insta.py", line 172, in update_comments
    raise RuntimeError("Test unhandled")
RuntimeError: Test unhandled

**Comment by Chuckler22** [comment]
Oh, here is my handle_exception:
```
logger = logging.getLogger(__name__)
handler = logging.StreamHandler(stream=sys.stdout)
logger.addHandler(handler)

def handle_exception(exc_type, exc_value, exc_traceback):
    if issubclass(exc_type, KeyboardInterrupt):
        sys.__excepthook__(exc_type, exc_value, exc_traceback)
        return

    logger.error("Uncaught exception", exc_info=(exc_type, exc_value, exc_traceback))
```

**Comment by adw0rd** [comment]
https://adw0rd.github.io/instagrapi/usage-guide/handle_exception.html
