### ISSUE TITLE
[BUG] Challenge required Error

### ISSUE THREAD

**Issue by DartkronX** [adw0rd/instagrapi#509]
Hey,
I followed the tutorial and uploaded some Reels to my instagram without any problem until I got a challenge exception

```Traceback (most recent call last):
  File "C:\python3.9.4\lib\site-packages\instagrapi-1.16.7-py3.9.egg\instagrapi\mixins\private.py", line 298, in _send_private_request
  File "C:\python3.9.4\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/configure_to_clips/?video=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Tiktok\script\Instagram\TikTokMain.py", line 78, in <module>
    media = cl.clip_upload(
  File "C:\python3.9.4\lib\site-packages\instagrapi-1.16.7-py3.9.egg\instagrapi\mixins\clip.py", line 191, in clip_upload
  File "C:\python3.9.4\lib\site-packages\instagrapi-1.16.7-py3.9.egg\instagrapi\mixins\clip.py", line 171, in clip_upload
  File "C:\python3.9.4\lib\site-packages\instagrapi-1.16.7-py3.9.egg\instagrapi\mixins\clip.py", line 267, in clip_configure
  File "C:\python3.9.4\lib\site-packages\instagrapi-1.16.7-py3.9.egg\instagrapi\mixins\private.py", line 449, in private_request
  File "C:\python3.9.4\lib\site-packages\instagrapi-1.16.7-py3.9.egg\instagrapi\mixins\private.py", line 330, in _send_private_request
instagrapi.exceptions.ChallengeRequired: challenge_required
```

After reading some user guids I added these to my code
```
from instagrapi.exceptions import (
    BadPassword, ReloginAttemptExceeded, ChallengeRequired,
    SelectContactPointRecoveryForm, RecaptchaChallengeForm,
    FeedbackRequired, PleaseWaitFewMinutes, LoginRequired
)


def handle_exception(client, e):
    if isinstance(e, BadPassword):
        client.logger.exception(e)
        client.set_proxy(self.next_proxy().href)
        if client.relogin_attempt > 0:
            self.freeze(str(e), days=7)
            raise ReloginAttemptExceeded(e)
        client.settings = self.rebuild_client_settings()
        return self.update_client_settings(client.get_settings())
    elif isinstance(e, LoginRequired):
        client.logger.exception(e)
        client.relogin()
        return self.update_client_settings(client.get_settings())
    elif isinstance(e, ChallengeRequired):
        api_path = json_value(client.last_json, "challenge", "api_path")
        if api_path == "/challenge/":
            client.set_proxy(self.next_proxy().href)
            client.settings = self.rebuild_client_settings()
        else:
            try:
                client.challenge_resolve(client.last_json)
            except ChallengeRequired as e:
                self.freeze('Manual Challenge Required', days=2)
                raise e
            except (ChallengeRequired, SelectContactPointRecoveryForm, RecaptchaChallengeForm) as e:
                self.freeze(str(e), days=4)
                raise e
            self.update_client_settings(client.get_settings())
        return True
    elif isinstance(e, FeedbackRequired):
        message = client.last_json["feedback_message"]
        if "This action was blocked. Please try again later" in message:
            self.freeze(message, hours=12)
            # client.settings = self.rebuild_client_settings()
            # return self.update_client_settings(client.get_settings())
        elif "We restrict certain activity to protect our community" in message:
            # 6 hours is not enough
            self.freeze(message, hours=12)
        elif "Your account has been temporarily blocked" in message:
            """
            Based on previous use of this feature, your account has been temporarily
            blocked from taking this action.
            This block will expire on 2020-03-27.
            """
            self.freeze(message)
    elif isinstance(e, PleaseWaitFewMinutes):
        self.freeze(str(e), hours=1)
    raise e

def get_code_from_email(username):
    mail = imaplib.IMAP4_SSL("outlook.office365.com")
    mail.login("ctechunlimitedltd@outlook.com", "Stealer1946")
    mail.select("inbox")
    result, data = mail.search(None, "(UNSEEN)")
    assert result == "OK", "Error1 during get_code_from_email: %s" % result
    ids = data.pop().split()
    for num in reversed(ids):
        mail.store(num, "+FLAGS", "\\Seen")  # mark as read
        result, data = mail.fetch(num, "(RFC822)")
        assert result == "OK", "Error2 during get_code_from_email: %s" % result
        msg = email.message_from_string(data[0][1].decode())
        payloads = msg.get_payload()
        if not isinstance(payloads, list):
            payloads = [msg]
        code = None
        for payload in payloads:
            body = payload.get_payload(decode=True).decode()
            if "<div" not in body:
                continue
            match = re.search(">([^>]*?({u})[^<]*?)<".format(u=username), body)
            if not match:
                continue
            print("Match from email:", match.group(1))
            match = re.search(r">(\d{6})<", body)
            if not match:
                print('Skip this email, "code" not found')
                continue
            code = match.group(1)
            if code:
                return code
    return False




def challenge_code_handler(username, choice):
    if choice == ChallengeChoice.SMS:
        return get_code_from_sms(username)
    elif choice == ChallengeChoice.EMAIL:
        return get_code_from_email(username)
    return False
    
    
def change_password_handler(username):
    # Simple way to generate a random string
    chars = list("abcdefghijklmnopqrstuvwxyz1234567890!&£@#")
    password = "".join(random.sample(chars, 8))
    return password    


cl.handle_exception = handle_exception
cl.challenge_code_handler = challenge_code_handler
cl.change_password_handler = change_password_handler
```
And now i am getting this 

```
Status 429: Too many requests
Traceback (most recent call last):
  File "C:\python3.9.4\lib\site-packages\instagrapi-1.16.7-py3.9.egg\instagrapi\mixins\private.py", line 298, in _send_private_request
  File "C:\python3.9.4\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://i.instagram.com/api/v1/accounts/contact_point_prefill/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python3.9.4\lib\site-packages\instagrapi-1.16.7-py3.9.egg\instagrapi\mixins\private.py", line 432, in private_request
  File "C:\python3.9.4\lib\site-packages\instagrapi-1.16.7-py3.9.egg\instagrapi\mixins\private.py", line 365, in _send_private_request
instagrapi.exceptions.PleaseWaitFewMinutes: Please wait a few minutes before you try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Tiktok\script\Instagram\TikTokMain.py", line 122, in <module>
    cl.login("toptrendingeverything", "Stealer1946")
  File "C:\python3.9.4\lib\site-packages\instagrapi-1.16.7-py3.9.egg\instagrapi\mixins\auth.py", line 374, in login
  File "C:\python3.9.4\lib\site-packages\instagrapi-1.16.7-py3.9.egg\instagrapi\mixins\auth.py", line 47, in pre_login_flow
  File "C:\python3.9.4\lib\site-packages\instagrapi-1.16.7-py3.9.egg\instagrapi\mixins\auth.py", line 147, in set_contact_point_prefill
  File "C:\python3.9.4\lib\site-packages\instagrapi-1.16.7-py3.9.egg\instagrapi\mixins\private.py", line 441, in private_request
  File "F:\Tiktok\script\Instagram\TikTokMain.py", line 95, in handle_exception
    self.freeze(str(e), hours=1)
NameError: name 'self' is not defined
```

My main Objective is to solve the "instagrapi.exceptions.ChallengeRequired: challenge_required"
and continue uploading to my reels.

Though that adding challenge handler and exception handler would solve that for me but it did not ):

Anything helps !

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Python version [e.g. 3.9.4]
 - instagrapi version [1.9.3latest]
 - moveipy version if used
 - imagemagick version if used

**Comment by Chuckler22** [comment]
Just FYI although you have removed your password from the post, anyone who subscribed to the library still received it by email. 

Suggest you change your outlook.com password.
