### ISSUE TITLE
Captions missing after clip.upload() [BUG]

### ISSUE THREAD

**Issue by joarleymoraes** [adw0rd/instagrapi#521]
**Describe the bug**
Captions missing after `clip.upload()` 

**To Reproduce**
``` 
ig_client = Client(username, password)
ig_client.clip_upload(
    path=video_filename, caption=caption, thumbnail=thumbnail_filename
)
``` 

**Traceback**
No errors

**Expected behavior**
The caption is present in the post posted.

**Desktop
 -  Ubuntu bullseye
 - Python 3.8
 - instagrapi 1.16.10
 - moveipy 1.0.3

**Comment by alb-ctrl** [comment]
just to add to this, media_edit and media_comment work well with post like pictures but when trying to comment or edit the caption on reels this error shows up 

`Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/home/pi/.local/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/2742494361234120835_51177434259/edit_media/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/postGenerator.py", line 41, in editMedia
    "#reels"
  File "/home/pi/.local/lib/python3.7/site-packages/instagrapi/mixins/media.py", line 353, in media_edit
    self.with_default_data(data),
  File "/home/pi/.local/lib/python3.7/site-packages/instagrapi/mixins/private.py", line 445, in private_request
    raise e
  File "/home/pi/.local/lib/python3.7/site-packages/instagrapi/mixins/private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/instagrapi/mixins/private.py", line 336, in _send_private_request
    % (message, last_json.get("feedback_message")),
instagrapi.exceptions.FeedbackRequired: feedback_required: None`

**Comment by adw0rd** [comment]
works fine after `cl.load_settings`

![image](https://user-images.githubusercontent.com/546889/149563410-69924f18-c9d7-4634-bdd4-8aacb555942f.png)

![image](https://user-images.githubusercontent.com/546889/149563162-26c17464-58be-40ce-9a23-0bbaf3c50216.png)

cannot reproduce

**Comment by adw0rd** [comment]
@joarleymoraes give me your session

**Comment by chrisbuetti** [comment]
happening to me as well
