### ISSUE TITLE
[BUG] status 400 on commenting

### ISSUE THREAD

**Issue by blackgyana** [adw0rd/instagrapi#525]
Catch this error while trying to comment:

400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/2743063074784662421_266319242/comment/
Traceback (most recent call last):
  File "C:\Users\Alex\Desktop\parse\venv\lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Users\Alex\Desktop\parse\venv\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/2743063074784662421_266319242/comment/
Status 400: Empty response message. Maybe enabled Two-factor auth?

**Comment by adw0rd** [comment]
@blackgyana cannot reproduce 
![image](https://user-images.githubusercontent.com/546889/149571755-f99f7217-b008-4e1a-97b7-c6dce8e54d0f.png)
