### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ognjensold** [adw0rd/instagrapi#543]
### Compensate with donations ($10 and more) for the time I spent to fix problems or send  me your [Pull Request](https://github.com/adw0rd/instagrapi/pulls) with fixes

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

* Bitcoin: 3KHgnvNNWio6wyQ71cgNeBQojXStxzkzfd
* Ethereum: 0x6e644c6b975B47801072b07a9a57DDfEC10DE74F
* https://paypal.me/adw0rd
* For Russia: СБП, Qiwi и тп: **+79118107609**

**Describe the bug**
Uploading a video to story isn't working.

**To Reproduce**
`link = base[0]
    base.pop(0)
    urllib.request.urlretrieve(link, f"videoTikTok/post.mp4")
    db.update({"tiktoks": base}, User.id == "list")
    media = cl.video_upload_to_story(f"videoTikTok/post.mp4")`

**Traceback**
Analizing video file "videoTikTok\post.mp4"
Generating thumbnail "videoTikTok\post.mp4.jpg"...
Unhandled exception in internal background task 'spamTiktok'.
Traceback (most recent call last):
  File "C:\Users\ogiga\PycharmProjects\movieBot\venv\lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Python39\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/configure_to_story/?video=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ogiga\PycharmProjects\movieBot\venv\lib\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\ogiga\PycharmProjects\movieBot\mainscript.py", line 219, in spamTiktok
    media = cl.video_upload_to_story(f"videoTikTok/post.mp4")
  File "C:\Users\ogiga\PycharmProjects\movieBot\venv\lib\site-packages\instagrapi\mixins\video.py", line 446, in video_upload_to_story
    raise e
  File "C:\Users\ogiga\PycharmProjects\movieBot\venv\lib\site-packages\instagrapi\mixins\video.py", line 423, in video_upload_to_story
    configured = self.video_configure_to_story(
  File "C:\Users\ogiga\PycharmProjects\movieBot\venv\lib\site-packages\instagrapi\mixins\video.py", line 772, in video_configure_to_story
    return self.private_request("media/configure_to_story/?video=1", self.with_default_data(data))
  File "C:\Users\ogiga\PycharmProjects\movieBot\venv\lib\site-packages\instagrapi\mixins\private.py", line 445, in private_request
    raise e
  File "C:\Users\ogiga\PycharmProjects\movieBot\venv\lib\site-packages\instagrapi\mixins\private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\ogiga\PycharmProjects\movieBot\venv\lib\site-packages\instagrapi\mixins\private.py", line 354, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: server processing error: VideoSourceError

**Expected behavior**
Upload the story to instagram.

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Python version 3.9
 - instagrapi version ~ 1.16.13
 - moveipy 1.0.3
 - imagemagick version if used

**Comment by adw0rd** [comment]
@ognjensold read this https://github.com/adw0rd/instagrapi/issues?q=VideoSourceError

VideoSourceError - this means the Instagram server does not understand your video format, you need to prepare the video before uploading it
