### ISSUE TITLE
VideoSourceError

### ISSUE THREAD

**Issue by dheeraj009joshi** [adw0rd/instagrapi#596]
**Describe the bug**
We are downloading the videos with the same library, then we uploading it to the Instagram with the same script. Its throwing same video source error

**To Reproduce**

```python
import  json
import os
import pytz
import shutil
import time
# from datetime import datetime,timedelta
import datetime
from time import strftime, strptime
from  instagrapi import  Client
# ACCOUNT_USERNAME = 'name'
# ACCOUNT_PASSWORD = 'Qwerty@123'
# ACCOUNT_USERNAME = 'laxmijoshi275'
# ACCOUNT_PASSWORD = '2345678'
# IG_CREDENTIAL = ACCOUNT_USERNAME
cl = None
def write_file(data, filename):
    fh = open(filename, "w")
    try:
        fh.write(json.dumps(data))
    finally:
        fh.close()
def read_file(filename):
    fh = open(filename, "r")
    return json.load(fh)
accounts={
    'pranika_dhakshu_fan':'Qwerty@123',
    'laxmijoshi275':"2345678"#in this  username  and pass
    
}   
time =datetime.datetime.now()
print(time)
houss=datetime.timedelta(hours=12)
main_time=time-houss
fan_usernames=['pranika_dhakshu_fan','laxmijoshi275']#add username  here
celevraty_account=[]
map_ing={
    'pranika_dhakshu_fan':'pranikadhakshu',
    'laxmijoshi275':'dheeraj_jooo'#add dict of  target and fan account 
}

caption={
    'pranika_dhakshu_fan':'this  is caption  of  @pranika_dhakshu_fan  #pranika_dhakshu_fan',
    'laxmijoshi275':'this  is caption  of  @plaxmijoshi275  #laxmijoshi275'#add dict of  caption 
}

for name in fan_usernames:
    IG_CREDENTIAL = name
    print(name) #to show  which account  is continue  running
    cl=Client()
    try:
        cl.login(username=name,password=accounts[name]) 
        print(f'ligin  {name}') 
    except Exception as e :
        print(e)
        print(" Plz... check the above exception and solve it  then  try  again ")  
   
    user_id=cl.user_id_from_username(map_ing[name])
    media_start=cl.user_medias(user_id,5)
    medias=[]
    for  i in media_start:
        medias.append(i.json())
    name=name +"-"  
    for js in medias:
        ja=json.loads(js)
        ff=datetime.datetime.strptime(ja['taken_at'],'%Y-%m-%dT%H:%M:%S+00:00')
        if ff>main_time:
            os.mkdir(f"{name}")
            files=os.listdir(name)#this  err  is  because  i put the  same  name  of  them  folder  as  the session  name 
            all_paths=[]
            for file in files:
                if file.endswith(('.jpg', '.png', 'jpeg')):
                    all_paths.append(file)
            if ja["media_type"] == 1:
                try:
                    print("in photo")
                    cl.photo_download(ja['pk'],name)
                    files=os.listdir(name)
                    all_paths=[]
                    for file in files:

                        if file.endswith(('.jpg', '.png', 'jpeg')):
                            all_paths.append(file)
                    cl.photo_upload(f'{name}/{all_paths[0]}',caption[name.replace("-","")])#caption yes  i am  getting that  from the  post  itself ohk  will  create  a map also
                    shutil.rmtree(name)
                except Exception as e:
                    print(e)
                    shutil.rmtree(name)
                    

                    
                
            elif ja["media_type"] == 2 and ja["product_type"] == 'feed':
                try:
                    print("in video")
                    cl.video_download(ja['pk'],name)
                    files=os.listdir(name)
                    all_paths=[]
                    for file in files:
                        if file.endswith(('.jpg', '.png', 'jpeg','.mp4')):
                            all_paths.append(file)
                    print(all_paths)
                    print(all_paths[0])
                    cl.video_upload(f'{name}/{all_paths[0]}',caption[name.replace("-","")])
                    shutil.rmtree(name)
                except Exception as e:
                    print(e)
                    shutil.rmtree(name)

                
            elif ja["media_type"] == 8:
                shutil.rmtree(name)
                
                
            elif ja["media_type"] == 2 and ja["product_type"] == 'clips':
                try:
                    print("in reels")
                    cl.clip_download(ja['pk'],name)
                    files=os.listdir(name)
                    all_paths=[]
                    for file in files:
                        if file.endswith(('.jpg', '.png', 'jpeg','.mp4')):
                            all_paths.append(file)
                    print(all_paths)
                    print(all_paths[0])
                    cl.clip_upload(f'{name}/{all_paths[0]}',caption[name.replace("-","")])
                    shutil.rmtree(name)  
                except Exception as e:
                    print(e)
                    shutil.rmtree(name)  
            cl.logout()  
        else:
            print("media  is old ")
```
        

**Traceback**

**Expected behavior**

```
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/configure/?video=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\dell\Desktop\fan_page\times.py", line 103, in <module>
    cl.video_upload(f'{name}/{all_paths[0]}',caption[name.replace("-","")])
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\video.py", line 290, in video_upload
    raise e
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\video.py", line 271, in video_upload
    configured = self.video_configure(
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\video.py", line 365, in video_configure
    return self.private_request(
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 445, in private_request
    raise e
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\instagrapi\mixins\private.py", line 354, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: server processing error: VideoSourceError
```
**Screenshots**

![image](https://user-images.githubusercontent.com/73873399/156598991-1e293bdf-57da-4497-82ab-bf045850d063.png)
**Desktop (please complete the following information):**
 - OS: windows
 - Python version 3.9.5
 - instagrapi version 1.16.14
 - moveipy version if used
 - imagemagick version if used

**Additional context**

**Comment by adw0rd** [comment]
Cannot reproduce, try this code:

```python
from instagrapi import Client

cl = Client()
cl.login(username, password)

path = cl.clip_download(cl.media_pk_from_url('https://www.instagram.com/p/CaMYnNZIJCA/'), folder='/tmp')
media = cl.clip_upload(path, 'Test caption')
```

![image](https://user-images.githubusercontent.com/546889/156730023-4f904ebd-8334-49c7-ba6b-16b7a3a0fc0b.png)
