### ISSUE TITLE
handle delta_acknowledge_approved challenge step

### ISSUE THREAD

**Issue by 4bo** [adw0rd/instagrapi#630]
after doing some ```user_info_by_username_v1```, i get this error:
```
api_1    | Traceback (most recent call last):
...
api_1    |     user = client.user_info_by_username_v1(username)
api_1    |   File "/usr/local/lib/python3.9/site-packages/instagrapi/mixins/user.py", line 166, in user_info_by_username_v1
api_1    |     raise e
api_1    |   File "/usr/local/lib/python3.9/site-packages/instagrapi/mixins/user.py", line 160, in user_info_by_username_v1
api_1    |     result = self.private_request(f"users/{username}/usernameinfo/")
api_1    |   File "/usr/local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 443, in private_request
api_1    |     self.challenge_resolve(self.last_json)
api_1    |   File "/usr/local/lib/python3.9/site-packages/instagrapi/mixins/challenge.py", line 78, in challenge_resolve
api_1    |     return self.challenge_resolve_simple(challenge_url)
api_1    |   File "/usr/local/lib/python3.9/site-packages/instagrapi/mixins/challenge.py", line 425, in challenge_resolve_simple
api_1    |     raise ChallengeUnknownStep(f'ChallengeResolve: Unknown step_name "{step_name}" for "{self.username}" in challenge resolver: {self.last_json}')
api_1    | instagrapi.exceptions.ChallengeUnknownStep: ChallengeResolve: Unknown step_name "delta_acknowledge_approved" for "None" in challenge resolver: {'step_name': 'delta_acknowledge_approved', 'flow_render_type': 3, 'bloks_action': 'com.instagram.challenge.navigation.take_challenge', 'cni': 17871057902674702, 'challenge_context': '{"step_name": "delta_acknowledge_approved", "cni": 17871057902674702, "is_stateless": false, "challenge_type_enum": "GENERIC_PHISHED", "present_as_modal": false}', 'challenge_type_enum_str': 'GENERIC_PHISHED', 'status': 'ok'}

**Comment by bhavincb** [comment]
i'm getting same error while doing relogin.

```
Traceback (most recent call last):
  File "E:\Freelancing\upwork\createdsystems(instagram service)\instagram-service\apps\tasks\management\commands\run_tasks.py", line 84, in handle
    api = InstaClient(service)
  File "E:\Freelancing\upwork\createdsystems(instagram service)\instagram-service\apps\utils\instagra_api.py", line 239, in __init__
    self.client.relogin()
  File "E:\Freelancing\upwork\createdsystems(instagram service)\venv\lib\site-packages\instagrapi\mixins\auth.py", line 459, in relogin
    return self.login(self.username, self.password, relogin=True)
  File "E:\Freelancing\upwork\createdsystems(instagram service)\venv\lib\site-packages\instagrapi\mixins\auth.py", line 372, in login
    self.pre_login_flow()
  File "E:\Freelancing\upwork\createdsystems(instagram service)\venv\lib\site-packages\instagrapi\mixins\auth.py", line 47, in pre_login_flow
    self.set_contact_point_prefill("prefill")
  File "E:\Freelancing\upwork\createdsystems(instagram service)\venv\lib\site-packages\instagrapi\mixins\auth.py", line 147, in set_contact_point_prefill
    return self.private_request("accounts/contact_point_prefill/", data, login=True)
  File "E:\Freelancing\upwork\createdsystems(instagram service)\venv\lib\site-packages\instagrapi\mixins\private.py", line 443, in private_request
    self.challenge_resolve(self.last_json)
  File "E:\Freelancing\upwork\createdsystems(instagram service)\venv\lib\site-packages\instagrapi\mixins\challenge.py", line 78, in challenge_resolve
    return self.challenge_resolve_simple(challenge_url)
  File "E:\Freelancing\upwork\createdsystems(instagram service)\venv\lib\site-packages\instagrapi\mixins\challenge.py", line 425, in challenge_resolve_simple
    raise ChallengeUnknownStep(f'ChallengeResolve: Unknown step_name "{step_name}" for "{self.username}" in challenge resolver: {self.last_json}')
instagrapi.exceptions.ChallengeUnknownStep: ChallengeResolve: Unknown step_name "delta_acknowledge_approved" for "username" in challenge resolver: {'step_name': 'delta_acknowledge_approved', 'flow_render_type': 3, 'bloks_action': 'com.instagram.challenge.navigation.take_challenge', 'cni': 17857910783727728, 'challenge_context': '{"step_name": "delta_acknowledge_approved", "cni": 17857910783727728, "is_stateless": false, "challenge_type_enum": "GENERIC_PHISHED", "present_as_modal": false}', 'challenge_type_enum_str': 'GENERIC_PHISHED', 'status': 'ok'}
```

**Comment by subzeroid** [comment]
Implemented, mirrored, and released.

Instagrapi:
- PR: https://github.com/subzeroid/instagrapi/pull/2672
- Release: https://github.com/subzeroid/instagrapi/releases/tag/2.16.2
- PyPI: https://pypi.org/project/instagrapi/2.16.2/

Aiograpi mirror:
- PR: https://github.com/subzeroid/aiograpi/pull/368
- Release: https://github.com/subzeroid/aiograpi/releases/tag/1.10.2
- PyPI: https://pypi.org/project/aiograpi/1.10.2/

`delta_acknowledge_approved` is now treated as an acknowledgement-style challenge step, the same as `delta_login_review` and `scraping_warning`: the resolver posts `{"choice": "0"}` to the challenge URL and returns success instead of raising `ChallengeUnknownStep`. Regression coverage was added in both libraries for the reported `GENERIC_PHISHED` payload.
