### ISSUE TITLE
[BUG] Fake checkpoint_required reponse

### ISSUE THREAD

**Issue by ali-zahedi** [adw0rd/instagrapi#648]
Hi, 
I'm using the last version of the package, currently, I'm getting a fake checkpoint_required response, the reason I'm calling it fake is, that if I retry to call API again, The success response will be returned (randomly).
here is an example of a situation, you can see the first request raised checkpoint_required but the second is True.
P.S: Not matter which API has been called, all of them raise this issue randomly. seems Instagram changing its pattern or API call structures.
![Screen Shot 2022-04-25 at 12 29 56 PM](https://user-images.githubusercontent.com/5299864/165062630-fbb5b1cd-474e-4f87-962d-648184566b8d.png)
The first call raised the checkpoint_required error, the second call called immediately after the first one, returning True (exact same account)
Thanks in advance.

```
>>> c_new = Client(proxy="********")

>>> c_new.login(username='username1', password='passw1')
Status 429: Too many requests
Ignore 429: Continue login
Traceback (most recent call last):
  File "/Users/aliali/ownCloud/Project/python/accountsservice/venv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/Users/aliali/ownCloud/Project/python/accountsservice/venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/timeline/
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/aliali/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Users/aliali/ownCloud/Project/python/accountsservice/venv/lib/python3.8/site-packages/instagrapi/mixins/auth.py", line 418, in login
    self.login_flow()
  File "/Users/aliali/ownCloud/Project/python/accountsservice/venv/lib/python3.8/site-packages/instagrapi/mixins/auth.py", line 168, in login_flow
    check_flow.append(self.get_timeline_feed(["cold_start_fetch"]))
  File "/Users/aliali/ownCloud/Project/python/accountsservice/venv/lib/python3.8/site-packages/instagrapi/mixins/auth.py", line 215, in get_timeline_feed
    return self.private_request(
  File "/Users/aliali/ownCloud/Project/python/accountsservice/venv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 445, in private_request
    raise e
  File "/Users/aliali/ownCloud/Project/python/accountsservice/venv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/Users/aliali/ownCloud/Project/python/accountsservice/venv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 354, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: checkpoint_required
>>> c_new.login(username='username1', password='passw1')
Status 429: Too many requests
Ignore 429: Continue login
True
```

**Comment by adw0rd** [comment]
@ali-zahedi submit your PR with improvements
