### ISSUE TITLE
[BUG] ClientForbiddenError (403) error

### ISSUE THREAD

**Issue by nickrinaldi88** [adw0rd/instagrapi#651]
**Describe the bug**
I'm receiving a ClientForbiddenError when trying to send a message to some public users. 

**To Reproduce**
```
from instagrapi import Client

ACCOUNT_USERNAME='ig_user'
ACCOUNT_PASSWORD='ig_pass'

cl = Client()
cl.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)

val = cl.user_id_from_username('rinaldi.photos')

cl.direct_send("test", val)
```

**Traceback**
```Traceback (most recent call last):

  File "/Users/Nick/opt/anaconda3/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()

  File "/Users/Nick/opt/anaconda3/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/direct_v2/threads/broadcast/text/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/var/folders/7c/301d7hc14vg6jjtbwrc6_4yc0000gn/T/ipykernel_28246/1324187445.py", line 1, in <cell line: 1>
    cl.direct_send("test", val)

  File "/Users/Nick/opt/anaconda3/lib/python3.8/site-packages/instagrapi/mixins/direct.py", line 252, in direct_send
    result = self.private_request(

  File "/Users/Nick/opt/anaconda3/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 445, in private_request
    raise e

  File "/Users/Nick/opt/anaconda3/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)

  File "/Users/Nick/opt/anaconda3/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 326, in _send_private_request
    raise ClientForbiddenError(e, response=e.response, **last_json)

ClientForbiddenError: {"action":"item_ack","status_code":"403","payload":{"client_context":"6800035695240551997","message":"We're sorry, but something went wrong. Please try again."},"status":"fail"}
```

**Expected behavior**
I expected that the user_ids I provide to the `direct_send` method will receive the message I provide in the first argument.

**Desktop (please complete the following information):**
 - OS: [macOS Monterrey 12.2.1]
 - Python 3.8.3
 - instagrapi 1.16.16

**Additional context**

It's not clear in the docs why this error is occurring. I understand what a 403 error is, but how can I be authorized to send a message through the library? I believed I needed to log in through
```
ACCOUNT_USERNAME=ig_user
ACCOUNT_PASSWORD=ig_pass

cl = Client()
cl.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)
```
and I'm good to go.

**Comment by nickrinaldi88** [comment]
UPDATE:

It seems like this error occurs when I try to send messages through either 1. iteration, or 2. sending a standalone string. For example:

```
user_id_list = ["123", "456"]

for id in user_id_list:
    cl.send_direct("test", id)

```
and 

```
val = cl.user_id_from_username('rinaldi.photos')
cl.send_direct("test", val)
```

will both through the error. Simply passing in the list of id's, however, like so:

```
cl.send_direct("test", user_id_list)
```

works fine. However, it seems to start a message thread of all the user's in the list, when my goal is messages users individually.

**Comment by adw0rd** [comment]
```
for id in user_id_list:
    cl.direct_send("test", [id])
```
