### ISSUE TITLE
Fail on login when sms verification required [BUG]

### ISSUE THREAD

**Issue by ghrlt** [adw0rd/instagrapi#668]
**Describe the bug**
Basically title, I try to login but Instagram require challenge, it fail with below traceback and I have to manually connect to Instagram and pass a sms code verification.
Then it's working without problem

**To Reproduce**

```py
client = instagrapi.Client()
client.challenge_code_handler = handleCodeChallenge # is a function requesting a code from input, then returning it

client.login("username", "password")
```
**Traceback**

```
Traceback (most recent call last):
  File "C:\Users\Gaëtan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Users\Gaëtan\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/reels_tray/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gaëtan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\Gaëtan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 330, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\_Dev\_Python\_Instagram\MyAppName\app.py", line 390, in <module>
    i = App()
  File "E:\_Dev\_Python\_Instagram\MyAppName\app.py", line 116, in __init__
    self.client.login(self.username, self.password)
  File "C:\Users\Gaëtan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\auth.py", line 418, in login
    self.login_flow()
  File "C:\Users\Gaëtan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\auth.py", line 167, in login_flow
    check_flow.append(self.get_reels_tray_feed("cold_start"))
  File "C:\Users\Gaëtan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\auth.py", line 244, in get_reels_tray_feed
    return self.private_request("feed/reels_tray/", data)
  File "C:\Users\Gaëtan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 443, in private_request
    self.challenge_resolve(self.last_json)
  File "C:\Users\Gaëtan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\challenge.py", line 78, in challenge_resolve
    return self.challenge_resolve_simple(challenge_url)
  File "C:\Users\Gaëtan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\challenge.py", line 425, in challenge_resolve_simple
    raise ChallengeUnknownStep(f'ChallengeResolve: Unknown step_name "{step_name}" for "{self.username}" in challenge resolver: {self.last_json}')
instagrapi.exceptions.ChallengeUnknownStep: ChallengeResolve: Unknown step_name "submit_phone" for "MyInstagramUsername" in challenge resolver: {'step_name': 'submit_phone', 'step_data': {'phone_number': 'MyPhoneNumber'}, 'flow_render_type': 3, 'bloks_action': 'com.instagram.challenge.navigation.take_challenge', 'cni': 17904593372559348, 'challenge_context': '{"step_name": "submit_phone", "cni": 17904593372559348, "is_stateless": false, "challenge_type_enum": "SMS", "present_as_modal": false}', 'challenge_type_enum_str': 'SMS', 'status': 'ok'}

```
**Expected behavior**

Should handle it, a priori through client.challenge_code_handler set function

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.10.1
 - instagrapi version: 1.16.16
 - moveipy version if used N/A
 - imagemagick version if used N/A

**Comment by adw0rd** [comment]
@ghrlt 2fa via SMS not implemented. You can help Instagrapi: make this functionality and send us a PR

**Comment by muners** [comment]
If asked for 2fa via SMS or Email, how can I avoid it?

Is it possible to respond on the smartphone app that I was able to log in to?

**Comment by ghrlt** [comment]
It would depend on the challenge type

Le jeu. 25 août 2022, 08:57, satoshi murakami ***@***.***> a
écrit :
