### ISSUE TITLE
[BUG] HTTPError: 500 Server Error / ClientError: Unknown Server Error

### ISSUE THREAD

**Issue by zmotan** [adw0rd/instagrapi#678]
**Describe the bug**
When I try to post on Instagram I get some wierd error I didn't find in documentation. It worked the first time and now its not working anymore even when I try to post it with an example code. EDIT: typo

**To Reproduce**
```
    async def igpost(self, ctx, *message):
        if ctx.message.attachments:
            photo = igcl.photo_download_by_url(url=ctx.message.attachments[0].url, folder="C:/ZmotanBOT/data", filename="temppostpic")
            igcl.photo_upload(path=photo,
                              location=Location(name="zmotan.com", lat=46.057661, lng=14.505980),
                              usertags=[Usertag(user=igzmotaninfo, x=0.5, y=0.5)],
                              caption=message)
            return
        else:
            print("no pic")
```

**Traceback**
```
Ignoring exception in command igpost:
Traceback (most recent call last):
  File "C:\Users\WORK\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Users\WORK\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://i.instagram.com/api/v1/media/configure/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\WORK\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\ZmotanBOT\cogs\IG.py", line 49, in igpost
    igcl.photo_upload(path=photo,
  File "C:\Users\WORK\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\photo.py", line 234, in photo_upload
    if self.photo_configure(
  File "C:\Users\WORK\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\photo.py", line 310, in photo_configure
    return self.private_request("media/configure/", self.with_default_data(data))
  File "C:\Users\WORK\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\private.py", line 445, in private_request
    raise e
  File "C:\Users\WORK\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\WORK\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\private.py", line 374, in _send_private_request
    raise ClientError(e, response=e.response, **last_json)
instagrapi.exceptions.ClientError: Unknown Server Error.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\WORK\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\WORK\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\WORK\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientError: Unknown Server Error.
```

**Expected behavior**
Should upload the photo from attachment as a post.

**Screenshots**
![Screenshot_87](https://user-images.githubusercontent.com/36111999/170059540-b0b4486b-d86f-44be-b3c0-cfe4c7dc9064.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version 3.8.2
 - instagrapi version  1.16.17
 - moveipy version 1.0.3
 - imagemagick version 7.1.0

Thanks in advance!

Best regards,
zmotan

**Comment by zmotan** [comment]
Thank you for your time and answer, I will do few tests in next few days and will post an update.

Best regards,
Z

**Comment by ghrlt** [comment]
From my experience, if your photo is not a JPEG or WEBP file, it will not work, thus might trigger such error.

Make sure to convert any .png to .jpg first ;)

**Comment by zmotan** [comment]
> From my experience, if your photo is not a JPEG or WEBP file, it will not work, thus might trigger such error.
> 
> Make sure to convert any .png to .jpg first ;)

Thank you for clearing that out, I believe this might be the root of the problem.

Cheers 🍻
