### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by oralunal** [adw0rd/instagrapi#696]
I got this error when i try to login via proxy.

```
INFO:     85.104.48.133:14398 - "POST /auth/login HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/instagrapi-rest-main/./routers/auth.py", line 32, in auth_login
    result = cl.login(
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/auth.py", line 418, in login
    self.login_flow()
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/auth.py", line 167, in login_flow
    check_flow.append(self.get_reels_tray_feed("cold_start"))
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/auth.py", line 244, in get_reels_tray_feed
    return self.private_request("feed/reels_tray/", data)
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 443, in private_request
    self.challenge_resolve(self.last_json)
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/challenge.py", line 78, in challenge_resolve
    return self.challenge_resolve_simple(challenge_url)
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/challenge.py", line 364, in challenge_resolve_simple
    self._send_private_request(challenge_url, {"choice": "0"})
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 300, in _send_private_request
    self.last_json = last_json = response.json()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by subzeroid** [comment]
Current releases include the documented 2FA login path and improved JSON error handling around login/challenge responses.

Docs:

- https://subzeroid.github.io/instagrapi/usage-guide/totp
- https://subzeroid.github.io/instagrapi/exceptions

Closing this old 2FA/proxy report as stale. If the current release still fails, please open a fresh focused issue with sanitized `last_json`, proxy context, and the exact exception.
