### ISSUE TITLE
Can't even launch my script

### ISSUE THREAD

**Issue by Nekyuuu** [adw0rd/instagrapi#726]
```
nekyuu@nekyuu:~$ python3 "/home/nekyuu/sss.py"
Status 429: Too many requests
Ignore 429: Continue login
Logged
Traceback (most recent call last):
  File "/home/nekyuu/sss.py", line 9, in <module>
    medias = cl.hashtag_medias_top('house', amount=100)
  File "/home/nekyuu/.local/lib/python3.10/site-packages/instagrapi/mixins/hashtag.py", line 360, in hashtag_medias_top
    medias = self.hashtag_medias_top_a1(name, amount)
  File "/home/nekyuu/.local/lib/python3.10/site-packages/instagrapi/mixins/hashtag.py", line 323, in hashtag_medias_top_a1
    return self.hashtag_medias_a1(name, amount, tab_key="edge_hashtag_to_top_posts")
  File "/home/nekyuu/.local/lib/python3.10/site-packages/instagrapi/mixins/hashtag.py", line 220, in hashtag_medias_a1
    medias, _ = self.hashtag_medias_a1_chunk(name, amount, tab_key)
  File "/home/nekyuu/.local/lib/python3.10/site-packages/instagrapi/mixins/hashtag.py", line 164, in hashtag_medias_a1_chunk
    data = self.public_a1_request(
  File "/home/nekyuu/.local/lib/python3.10/site-packages/instagrapi/mixins/public.py", line 173, in public_a1_request
    response = self.public_request(
  File "/home/nekyuu/.local/lib/python3.10/site-packages/instagrapi/mixins/public.py", line 72, in public_request
    return self._send_public_request(url, **kwargs)
  File "/home/nekyuu/.local/lib/python3.10/site-packages/instagrapi/mixins/public.py", line 106, in _send_public_request
    expected_length = int(response.headers.get("Content-Length"))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

After Login

**Comment by adw0rd** [comment]
You have an old version of instagrapi, upgrade to instagrapi==1.16.20
