### ISSUE TITLE
Error 403 while uploading photo

### ISSUE THREAD

**Issue by samuelbraun04** [adw0rd/instagrapi#745]
### Discussed in https://github.com/adw0rd/instagrapi/discussions/744

<div type='discussions-op-text'>

<sup>Originally posted by **diegogurr** June 23, 2022</sup>
After 1 week of posting photos (every 4 hours,using crontab) without problems now it says 'Photo Upload failed with the following response : <Response [403]>
My code for publishing:
```
def publishPost(path,description):
    try:
        cl.photo_upload(path,description)
    except LoginRequired:
        cl.relogin()
        cl.dump_settings(s_path)
```
What could be the problem? How can I solve this?</div>

I'm getting the same error out of no where. My full traceback:

```
Traceback (most recent call last):
  File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/media/configure_sidecar/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samuelbraun04/instagramBot/sidecars.py", line 228, in sidecar
    bot.album_upload(files, str(open(CAPTIONS_PATH+CONJOINER+caption, "r", encoding='utf-8').read()))
  File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/album.py", line 217, in album_upload
    raise e
  File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/album.py", line 206, in album_upload
    configured = (configure_handler or self.album_configure)(
  File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/album.py", line 285, in album_configure
    return self.private_request(
  File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 445, in private_request
    raise e
  File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 323, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samuelbraun04/instagramBot/sidecars.py", line 230, in sidecar
    bot.photo_upload(files[0], str(open(CAPTIONS_PATH+CONJOINER+caption, "r", encoding='utf-8').read()))
  File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/photo.py", line 230, in photo_upload
    upload_id, width, height = self.photo_rupload(path, upload_id)
  File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/photo.py", line 192, in photo_rupload
    raise PhotoNotUpload(response.text, response=response, **last_json)
instagrapi.exceptions.PhotoNotUpload: login_required
```

**Comment by naisukhy** [comment]
> ### Discussed in #744
> 
> Originally posted by **diegogurr** June 23, 2022 After 1 week of posting photos (every 4 hours,using crontab) without problems now it says 'Photo Upload failed with the following response : <Response [403]> My code for publishing:
> 
> ```
> def publishPost(path,description):
>     try:
>         cl.photo_upload(path,description)
>     except LoginRequired:
>         cl.relogin()
>         cl.dump_settings(s_path)
> ```
> 
> What could be the problem? How can I solve this?
> 
> I'm getting the same error out of no where. My full traceback:
> 
> ```
> Traceback (most recent call last):
>   File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
>     response.raise_for_status()
>   File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/media/configure_sidecar/
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/samuelbraun04/instagramBot/sidecars.py", line 228, in sidecar
>     bot.album_upload(files, str(open(CAPTIONS_PATH+CONJOINER+caption, "r", encoding='utf-8').read()))
>   File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/album.py", line 217, in album_upload
>     raise e
>   File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/album.py", line 206, in album_upload
>     configured = (configure_handler or self.album_configure)(
>   File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/album.py", line 285, in album_configure
>     return self.private_request(
>   File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 445, in private_request
>     raise e
>   File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 432, in private_request
>     self._send_private_request(endpoint, **kwargs)
>   File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 323, in _send_private_request
>     raise LoginRequired(response=e.response, **last_json)
> instagrapi.exceptions.LoginRequired: login_required
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/samuelbraun04/instagramBot/sidecars.py", line 230, in sidecar
>     bot.photo_upload(files[0], str(open(CAPTIONS_PATH+CONJOINER+caption, "r", encoding='utf-8').read()))
>   File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/photo.py", line 230, in photo_upload
>     upload_id, width, height = self.photo_rupload(path, upload_id)
>   File "/home/samuelbraun04/.local/lib/python3.9/site-packages/instagrapi/mixins/photo.py", line 192, in photo_rupload
>     raise PhotoNotUpload(response.text, response=response, **last_json)
> instagrapi.exceptions.PhotoNotUpload: login_required
> ```

Did your account got temporarily or permanently terminated?

**Comment by subzeroid** [comment]
Closing this old support thread as Instagram account/session/rate-limit enforcement rather than a specific instagrapi defect.

These states are usually account, proxy, device, session, action-pattern, or server-side trust decisions. The current guidance is documented here:

- https://subzeroid.github.io/instagrapi/usage-guide/best-practices
- https://subzeroid.github.io/instagrapi/usage-guide/handle_exception
- https://subzeroid.github.io/instagrapi/usage-guide/interactions

If a current release returns a new structured response that should be mapped to a typed exception, please open a fresh focused issue with sanitized `last_json` and the exact method call.
