### ISSUE TITLE
ERROR in media edit

### ISSUE THREAD

**Issue by hossein-mohseni** [adw0rd/instagrapi#746]
**Describe the bug**
an unknown Error show's up when I edit a video caption

**Traceback**
```
Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/2844284733890771643_45801961780/edit_media/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\myuser\OneDrive\Desktop\rTEST.py", line 101, in <module>
    Thread(target=refresh(i)).start()
  File "c:\Users\myuser\OneDrive\Desktop\rTEST.py", line 68, in refresh
    cl.media_edit(media_id=p_id, caption=""""There comes a time when you have to choose between turning the page and closing the book.
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\media.py", line 351, in media_edit
    result = self.private_request(
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 445, in private_request
    raise e
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 354, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: Sorry, this comment is too long
```

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Python version [3.10]
 - instagrapi version [latest]

**Additional context**
what should i do? 
i searched every ware but didn't find the solution

**Comment by adw0rd** [comment]
@hossein-mohseni this is not a bug, please read carefully

`instagrapi.exceptions.UnknownError: Sorry, this comment is too long`

Your comment is too long

**Comment by hossein-mohseni** [comment]
> @hossein-mohseni this is not a bug, please read carefully
> 
> `instagrapi.exceptions.UnknownError: Sorry, this comment is too long`
> 
> Your comment is too long

But the captain is just about 5 line and i have 10 comments only!

**Comment by adw0rd** [comment]
@hossein-mohseni This is a response from the instagram server, you should reduce your caption (comment for post)
