### ISSUE TITLE
[BUG] Two-factor authentication required

### ISSUE THREAD

**Issue by Mertozturkk** [adw0rd/instagrapi#751]
I generated codes using verification code generator
like this

>  code = cl.totp_generate_code(seed)
> "123456"
> 
> cl.totp_enable(code)
> ["1234 5678", "1234 5678", "1234 5678", "1234 5678", "1234 5678"]

then i tried login with verification code but its returned fail

```
recovery_codes = ["1234 5678", "1234 5678", "1234 5678", "1234 5678", "1234 5678"]


cl = Client()


cl.login(mail, password,verification_code=recovery_codes[0])
```

```
Traceback (most recent call last):
  File "/home/mert/Documents/code/bots/instagrapi_bot/venv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/home/mert/Documents/code/bots/instagrapi_bot/venv/lib/python3.8/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mert/Documents/code/bots/instagrapi_bot/venv/lib/python3.8/site-packages/instagrapi/mixins/auth.py", line 391, in login
    logged = self.private_request("accounts/login/", data, login=True)
  File "/home/mert/Documents/code/bots/instagrapi_bot/venv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 445, in private_request
    raise e
  File "/home/mert/Documents/code/bots/instagrapi_bot/venv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/mert/Documents/code/bots/instagrapi_bot/venv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 348, in _send_private_request
    raise TwoFactorRequired(**last_json)
instagrapi.exceptions.TwoFactorRequired: Two-factor authentication required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mert/Documents/code/bots/instagrapi_bot/venv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/home/mert/Documents/code/bots/instagrapi_bot/venv/lib/python3.8/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/two_factor_login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mert/Documents/code/bots/instagrapi_bot/venv/lib/python3.8/site-packages/instagrapi/mixins/auth.py", line 413, in login
    logged = self.private_request("accounts/two_factor_login/", data, login=True)
  File "/home/mert/Documents/code/bots/instagrapi_bot/venv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 445, in private_request
    raise e
  File "/home/mert/Documents/code/bots/instagrapi_bot/venv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/mert/Documents/code/bots/instagrapi_bot/venv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 354, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: Invalid Parameters
python-BaseException

Process finished with exit code 1

```

How can i fix it ?

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com

**Comment by spygency1** [comment]
Hello 👋
 It's my pleasure to serve you, how can I help you?
