### ISSUE TITLE
BUG] user_friendships_v1 Invalid user list

### ISSUE THREAD

**Issue by 11philip22** [adw0rd/instagrapi#760]
When using `user_friendships_v1` I get the response:
```json
{
	"message": "Invalid user list",
	"status": "fail"
}
```
With this traceback
```python
Traceback (most recent call last):
  File "C:\Users\Philip\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\221.5591.52\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Python310\lib\site-packages\instagrapi\mixins\user.py", line 310, in user_friendships_v1
    result = self.private_request(
  File "C:\Python310\lib\site-packages\instagrapi\mixins\private.py", line 445, in private_request
    raise e
  File "C:\Python310\lib\site-packages\instagrapi\mixins\private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Python310\lib\site-packages\instagrapi\mixins\private.py", line 354, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: Invalid user list
```
![image](https://user-images.githubusercontent.com/26529935/178153023-8744b158-e667-4394-bb66-ef3e756430af.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/26529935/178153008-f26771d6-f1f1-41c0-b404-75da36779721.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.10
 - instagrapi version:  1.16.20

**Comment by 11philip22** [comment]
I have created a pull request with an fix https://github.com/adw0rd/instagrapi/pull/761

**Comment by adw0rd** [comment]
@11philip22 thanks!
