### ISSUE TITLE
[BUG] instagrapi.exceptions.UnknownError: server processing error: VideoSourceVideoStreamCheckException

### ISSUE THREAD

**Issue by JackhammerYT** [adw0rd/instagrapi#770]
**Describe the bug**
Every time i try to upload a video i get the following error: instagrapi.exceptions.UnknownError: server processing error: VideoSourceVideoStreamCheckException I tried Uploading from Different Accounts and I tried uploading Different Media still No resolution

**To Reproduce**
`from instagrapi import Client

c = Client()
c.login("user id","passwd")

c.video_upload("D:/Videos/2022-04-06_11-52-02.mp4", "test")`

**Traceback**
`Traceback (most recent call last):
  File "D:\python\test.py", line 6, in <module>
    c.video_upload("D:/Videos/2022-04-06_11-52-02.mp4", "test")
  File "D:\Python 3.10.2\lib\site-packages\instagrapi\mixins\video.py", line 290, in video_upload
    raise e
  File "D:\Python 3.10.2\lib\site-packages\instagrapi\mixins\video.py", line 271, in video_upload
    configured = self.video_configure(
  File "D:\Python 3.10.2\lib\site-packages\instagrapi\mixins\video.py", line 365, in video_configure
    return self.private_request(
  File "D:\Python 3.10.2\lib\site-packages\instagrapi\mixins\private.py", line 445, in private_request
    raise e
  File "D:\Python 3.10.2\lib\site-packages\instagrapi\mixins\private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "D:\Python 3.10.2\lib\site-packages\instagrapi\mixins\private.py", line 354, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: server processing error: VideoSourceVideoStreamCheckException`

**Expected behavior**
The video gets uploaded to instagram

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Python version 3.10.2
 - instagrapi version 1.16.20
 - moveipy version 1.0.3

**Comment by stramanu** [comment]
the same to me too..

**Comment by adw0rd** [comment]
Perhaps your video is not suitable for Instagram format. Download any video from instagram and see what format it is, convert your video to this format and you will be successful

Related #393

**Comment by stramanu** [comment]
I think I understand what the problem is. It is not about the format. I realized that Instagram blocked me temporarily. In fact, I can no longer do any action. it is strange, also because I have not done any strange or too fast operations, such as bots. I don't know...

**Comment by stramanu** [comment]
@adw0rd do you have an example of the ffmpeg command to correctly convert a video for instagram?

**Comment by adw0rd** [comment]
> @adw0rd do you have an example of the ffmpeg command to correctly convert a video for instagram?

No

**Comment by stramanu** [comment]
ok, I have found the solution to my case.
It is precisely about the format of the video.
At this link you will find the prerequisites for the video format:
[](https://docs.ayrshare.com/additional-info/image-and-video-requirements#video-2)

Here is the ffmpeg command I use to convert my videos:
`ffmpeg -y -i "input.mp4" -t 00:00:50 -vf "scale=1080:700:force_original_aspect_ratio=decrease,pad=1080:700:-1:-1:color=black" -r 25 -c:v h264 -crf 18 -c:a aac -b:a 128k -ac 2 -ar 44100 -pix_fmt yuv420p -max_muxing_queue_size 1024 -preset ultrafast "output.mp4"`

**Comment by JackhammerYT** [comment]
@stramanu that helps a lot thanks!

closing this issue
