### ISSUE TITLE
[BUG] 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/reels_tray/

### ISSUE THREAD

**Issue by GildedHonour** [adw0rd/instagrapi#783]
The example from README
```
from instagrapi import Client

cl = Client()
cl.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)

user_id = cl.user_id_from_username("adw0rd")
medias = cl.user_medias(user_id, 20)
```

===>

```
% python test1.py

Enter code (6 digits) for gremli350@fastmail.com (ChallengeChoice.EMAIL): 353703
Code entered "353703" for gremli350@fastmail.com (0 attempts by 5 seconds)
Enter password for gremli350@fastmail.com: lML0XLLAoWkxMMWvBtQU
Password entered "lML0XLLAoWkxMMWvBtQU" for gremli350@fastmail.com (0 attempts by 5 seconds)
Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/reels_tray/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 330, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://i.instagram.com/api/v1/bloks/apps/com.instagram.challenge.navigation.take_challenge/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.10/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/instag_api1.py", line 7, in <module>
    cl.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/auth.py", line 418, in login
    self.login_flow()
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/auth.py", line 167, in login_flow
    check_flow.append(self.get_reels_tray_feed("cold_start"))
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/auth.py", line 244, in get_reels_tray_feed
    return self.private_request("feed/reels_tray/", data)
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 443, in private_request
    self.challenge_resolve(self.last_json)
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/challenge.py", line 78, in challenge_resolve
    return self.challenge_resolve_simple(challenge_url)
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/challenge.py", line 421, in challenge_resolve_simple
    return self.bloks_change_password(pwd, self.last_json['challenge_context'])
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/bloks.py", line 46, in bloks_change_password
    return self.bloks_action("com.instagram.challenge.navigation.take_challenge", data)
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/bloks.py", line 21, in bloks_action
    result = self.private_request(f"bloks/apps/{action}/", self.with_default_data(data))
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 445, in private_request
    raise e
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/user1/.local/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 317, in _send_private_request
    self.last_json = last_json = response.json()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] Oops, an error occurred.
: 0
```

**Comment by EricMyhrer** [comment]
You ever get a fix on this?

**Comment by subzeroid** [comment]
I cannot reproduce this on the current code.

The original traceback was a login/checkpoint flow from 2022: `feed/reels_tray/` returned `challenge_required`, then the old challenge resolver hit a Bloks challenge endpoint that returned a non-JSON 500 response. That is an account/session trust challenge during login, not a `user_medias()` defect.

Current verification: `get_reels_tray_feed("cold_start")` returns `status="ok"`, and the README-style media fetch works when using a known user id: `user_medias("25025320", 5)` returned 5 media objects. Current regression checks for challenge handling and non-JSON private responses also pass.

Docs:
Best practices: https://subzeroid.github.io/instagrapi/usage-guide/best-practices.html
Challenge resolver: https://subzeroid.github.io/instagrapi/usage-guide/challenge_resolver.html
Handle exceptions: https://subzeroid.github.io/instagrapi/usage-guide/handle_exception.html
Media usage: https://subzeroid.github.io/instagrapi/usage-guide/media.html

If this still happens on the latest release, treat it as a fresh account/session challenge report: include the current instagrapi version, sanitized `last_json`, whether the account can log in and pass the same checkpoint in the official app, and whether the same saved settings/proxy are reused between runs. Closing this old report as fixed/stale on the current API behavior.
