### ISSUE TITLE
[BUG] Internal Server Error for url: https://i.instagram.com/api/v1/accounts/login/

### ISSUE THREAD

**Issue by idobhh** [adw0rd/instagrapi#838]
**Describe the bug**
When I log in to a verified Instagram user with 2FA (2FA configured to authentication app), I get a 500 Server Error.
It keeps happening all the time I try to log in with this account, and it works fine with other "normal" (not verified) users.

**To Reproduce**
```
c = instagrapi.Client()
c.login("username", "password", False, "123456")
```

**Traceback**
```
Traceback (most recent call last):
  File "C:\SomeFolder\venv\lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\SomeFolder\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://i.instagram.com/api/v1/accounts/login/
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\SomeFolder\venv\lib\site-packages\instagrapi\mixins\auth.py", line 391, in login
    logged = self.private_request("accounts/login/", data, login=True)
  File "C:\SomeFolder\venv\lib\site-packages\instagrapi\mixins\private.py", line 447, in private_request
    raise e
  File "C:\SomeFolder\venv\lib\site-packages\instagrapi\mixins\private.py", line 434, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\SomeFolder\venv\lib\site-packages\instagrapi\mixins\private.py", line 374, in _send_private_request
    raise ClientError(e, response=e.response, **last_json)
instagrapi.exceptions.ClientError: 500 Server Error: Internal Server Error for url: https://i.instagram.com/api/v1/accounts/login/
```
**Versions**
 - Python version 3.9.6
 - instagrapi version 1.16.27

**Comment by subzeroid** [comment]
Closing this old login/challenge support thread as stale.

Current challenge and 2FA documentation is here:

- https://subzeroid.github.io/instagrapi/usage-guide/challenge_resolver
- https://subzeroid.github.io/instagrapi/usage-guide/totp
- https://subzeroid.github.io/instagrapi/usage-guide/best-practices

If this still reproduces on `instagrapi >= 2.9.1`, please open a fresh focused issue with sanitized current `last_json`, the exact method call, and the exact exception. Credentials, tokens, contact points, and user IDs should be redacted.
