### ISSUE TITLE
[BUG] Get ClientJSONDecodeError when try login with 2fa

### ISSUE THREAD

**Issue by hittiks** [adw0rd/instagrapi#856]
I'm trying to login without 2fa code:
`cl.login(login, password, relogin=True)`
And when get 2fa required exception trying to login with 2fa code:
cl.login(login, password, relogin=True, verification_code=str(code))

And so get in traceback html code (1) and after get this:
`Traceback (most recent call last):
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\private.py", line 300, in _send_private_request
    self.last_json = last_json = response.json()
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/Skyline/Desktop/ig-userbot/main.py", line 305, in <module>
    main()
  File "c:/Users/Skyline/Desktop/ig-userbot/main.py", line 293, in main
    res = load_from_file()
  File "c:/Users/Skyline/Desktop/ig-userbot/main.py", line 112, in load_from_file
    res = relogin()
  File "c:/Users/Skyline/Desktop/ig-userbot/main.py", line 65, in relogin
    cl.login(login, password, relogin=True, verification_code=str(code))
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\auth.py", line 418, in login
    self.login_flow()
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\auth.py", line 167, in login_flow
    check_flow.append(self.get_reels_tray_feed("cold_start"))
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\auth.py", line 244, in get_reels_tray_feed
    return self.private_request("feed/reels_tray/", data)
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\private.py", line 445, in private_request
    self.challenge_resolve(self.last_json)
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\challenge.py", line 78, in challenge_resolve
    return self.challenge_resolve_simple(challenge_url)
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\challenge.py", line 364, in challenge_resolve_simple
    self._send_private_request(challenge_url, {"choice": "0"})
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\private.py", line 310, in _send_private_request
    raise ClientJSONDecodeError(
instagrapi.exceptions.ClientJSONDecodeError: JSONDecodeError Expecting value: line 1 column 1 (char 0) while opening https://i.instagram.com/challenge/?next=/api/challenge/`

(1) I place in file:
[temp.txt](https://github.com/adw0rd/instagrapi/files/9411269/temp.txt)

I have not any idea for solving this

**Comment by hittiks** [comment]
[temp2.txt](https://github.com/adw0rd/instagrapi/files/9411310/temp2.txt)
I don't know why, but github can not upload two files in 1 comment

**Comment by subzeroid** [comment]
Current releases include the documented 2FA login path and newer Bloks two-factor helpers.

Docs: https://subzeroid.github.io/instagrapi/usage-guide/totp

Closing this old 2FA report as covered by the current API. If the current release still fails for a specific 2FA payload, please open a fresh focused issue with sanitized response details.
