### ISSUE TITLE
[BUG] challenge email problem

### ISSUE THREAD

**Issue by Mertozturkk** [adw0rd/instagrapi#880]
```
def get_code_from_email(username):
    mail = imaplib.IMAP4_SSL("imap.gmail.com")
    mail.login(email, password)
    mail.select("inbox")
    result, data = mail.search(None, "(UNSEEN)")
    assert result == "OK", "Error1 during get_code_from_email: %s" % result
    ids = data.pop().split()
    for num in reversed(ids):
        mail.store(num, "+FLAGS", "\\Seen")  # mark as read
        result, data = mail.fetch(num, "(RFC822)")
        assert result == "OK", "Error2 during get_code_from_email: %s" % result
        msg = email.message_from_string(data[0][1].decode())
        payloads = msg.get_payload()
        if not isinstance(payloads, list):
            payloads = [msg]
        code = None
        for payload in payloads:
            body = payload.get_payload(decode=True).decode()
            if "<div" not in body:
                continue
            match = re.search(">([^>]*?({u})[^<]*?)<".format(u=username), body)
            if not match:
                continue
            print("Match from email:", match.group(1))
            match = re.search(r">(\d{6})<", body)
            if not match:
                print('Skip this email, "code" not found')
                continue
            code = match.group(1)
            if code:
                return code
    return False


def get_code_from_sms(username):
    while True:
        code = input(f"Enter code (6 digits) for {username}: ").strip()
        if code and code.isdigit():
            return code
    return None


def challenge_code_handler(username, choice):
    if choice == ChallengeChoice.SMS:
        return get_code_from_sms(username)
    elif choice == ChallengeChoice.EMAIL:
        return get_code_from_email(username)
    return False


def change_password_handler(username):
    # Simple way to generate a random string
    chars = list("abcdefghijklmnopqrstuvwxyz1234567890!&£@#")
    password = "".join(random.sample(chars, 10))
    return password


cl = Client()
cl.challenge_code_handler = challenge_code_handler
cl.login(email, password)

```
i trying this code but i cant pass this error. BTW i I enabled POP and IMAP on gmail

```
Traceback (most recent call last):
  File "/home/mert/Documents/instagrapi_bot/venv/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/home/mert/Documents/instagrapi_bot/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mert/Documents/instagrapi_bot/venv/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 434, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/mert/Documents/instagrapi_bot/venv/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 330, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mert/Documents/instagrapi_bot/venv/lib/python3.11/site-packages/instagrapi/mixins/auth.py", line 391, in login
    logged = self.private_request("accounts/login/", data, login=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mert/Documents/instagrapi_bot/venv/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 445, in private_request
    self.challenge_resolve(self.last_json)
  File "/home/mert/Documents/instagrapi_bot/venv/lib/python3.11/site-packages/instagrapi/mixins/challenge.py", line 78, in challenge_resolve
    return self.challenge_resolve_simple(challenge_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mert/Documents/instagrapi_bot/venv/lib/python3.11/site-packages/instagrapi/mixins/challenge.py", line 425, in challenge_resolve_simple
    raise ChallengeUnknownStep(f'ChallengeResolve: Unknown step_name "{step_name}" for "{self.username}" in challenge resolver: {self.last_json}')
instagrapi.exceptions.ChallengeUnknownStep: ChallengeResolve: Unknown step_name "select_contact_point_recovery" for "mailname@gmail.com" in challenge resolver: {'step_name': 'select_contact_point_recovery', 'step_data': {'choice': '2', 'hl_co_enabled': False, 'sigp_to_hl': False}, 'flow_render_type': 3, 'bloks_action': 'com.instagram.challenge.navigation.take_challenge', 'nonce_code': 'pc6t7DQqzn', 'user_id': 55472128738, 'cni': 17842344260848739, 'challenge_context': '{"step_name": "select_contact_point_recovery", "nonce_code": "pc6t7DQqzn", "user_id": 55472128738, "cni": 17842344260848739, "is_stateless": false, "challenge_type_enum": "HACKED_LOCK", "present_as_modal": false}', 'challenge_type_enum_str': 'HACKED_LOCK', 'status': 'ok'}

Process finished with exit code 1

```

**Comment by matevz-ap** [comment]
It looks like your account was disabled ("challenge_type_enum": "HACKED_LOCK"). You input the correct code, but are then redirected to challenge page that Instagrapi can't solve. Try logging in to this account by hand and you will see whats going on. I don't think this challenge is solvable, but Instagrapi could do a better job of letting you know the type off challenge.

**Comment by Mertozturkk** [comment]
yes, instagram has blocked it and there is no email confirmation. But it tells me that I need to log in from the mobile app so that I can recover the account. Do you know anything I can do for this in instagrapi?

**Comment by matevz-ap** [comment]
I don't know what the challenge requires you to do, but as far as I know, you would need to emulate the Instagram app in order to resolve it and that is not something you can so with instagrapi.

**Comment by larscth** [comment]
I wanted to use ur code, but can't figure out what "re" is. in the function get_code_from_email in the second for function.

**Comment by Mertozturkk** [comment]
> 
You can import re library 
`import re`

**Comment by larscth** [comment]
seems that my acc also get disabled ..... 
what did you do to get your acc back ?

**Comment by Mertozturkk** [comment]
Instagram told me to log in from the mobile app to open the account but it didn't fix even though I opened the account from the mobile app. I was not very interested in the process and i opened a new account

**Comment by knekke** [comment]
same here.. resetting the password via app doesn't seem to help :/

**Comment by tinerci** [comment]
> Instagram told me to log in from the mobile app to open the account but it didn't fix even though I opened the account from the mobile app. I was not very interested in the process and i opened a new account

hocam merhaba, sorunu çözebildinizmi ? aynı sorunu bende yaşıyorumda

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
