### ISSUE TITLE
[BUG] HTTPError: 500 Server Error / ClientError: Unknown Server Error when i try to upload a story

### ISSUE THREAD

**Issue by Holanddez** [adw0rd/instagrapi#902]
**Describe the bug**
When I try to upload a story using an example from documentation I get this 500 Server Error.

**To Reproduce**
Copy the 3rd example from https://adw0rd.github.io/instagrapi/usage-guide/story.html

**Traceback**
Traceback (most recent call last):
  File "C:\VS Code trabs\IGBot\venv\lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request    
    response.raise_for_status()
  File "C:\VS Code trabs\IGBot\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://i.instagram.com/api/v1/media/configure_to_story/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\VS Code trabs\IGBot\main.py", line 21, in <module>
    cl.photo_upload_to_story(
  File "C:\VS Code trabs\IGBot\venv\lib\site-packages\instagrapi\mixins\photo.py", line 361, in photo_upload_to_story
    if self.photo_configure_to_story(
  File "C:\VS Code trabs\IGBot\venv\lib\site-packages\instagrapi\mixins\photo.py", line 622, in photo_configure_to_story
    return self.private_request("media/configure_to_story/", self.with_default_data(data))
  File "C:\VS Code trabs\IGBot\venv\lib\site-packages\instagrapi\mixins\private.py", line 447, in private_request       
    raise e
  File "C:\VS Code trabs\IGBot\venv\lib\site-packages\instagrapi\mixins\private.py", line 434, in private_request       
    self._send_private_request(endpoint, **kwargs)
  File "C:\VS Code trabs\IGBot\venv\lib\site-packages\instagrapi\mixins\private.py", line 374, in _send_private_request
    raise ClientError(e, response=e.response, **last_json)
instagrapi.exceptions.ClientError: Unknown Server Error.

**Expected behavior**
Should upload the photo as a story.

**Screenshots**
![traceback](https://user-images.githubusercontent.com/92011840/190034303-625d3a67-f3be-4ee5-903f-7c7fa07b30c2.png)
![image](https://user-images.githubusercontent.com/92011840/190034596-7eca395f-b9e6-42bb-8c3d-36089ce4ec79.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.9.7
 - instagrapi version: 1.16.29
 - moveipy version if used: 1.0.3

**Comment by italianconcerto** [comment]
I have the same problem.

**Comment by subzeroid** [comment]
I cannot reproduce this on the current code.

The original traceback was from instagrapi `1.16.29` in 2022 and failed at `media/configure_to_story/`. Current `photo_upload_to_story()` has regression coverage for the story configure/recent-story fallback path, and I rechecked the live flow now: `photo_upload_to_story(Path("examples/background.png"), ...)` uploaded a photo story, `story_info()` returned the uploaded story as `media_type=1` / `product_type="story"`, and cleanup deleted it successfully.

Current docs: https://subzeroid.github.io/instagrapi/usage-guide/story.html

If this still happens on the latest release, please open a fresh issue with the current instagrapi version, the exact story file dimensions/format, sanitized `last_json`, and whether the same account can publish the same story manually from the Instagram app. Closing this old report as fixed/stale.
