### ISSUE TITLE
[BUG] fbsearch_suggested_profiles raises "Not Elegible For Chaining" Exception

### ISSUE THREAD

**Issue by marcouderzo** [adw0rd/instagrapi#910]
As from the title, the `fbsearch_suggested_profiles()` function raises "Not Elegible For Chaining" Exception. 
Here is how to reproduce the bug:

```
import instagrapi
from instagrapi import Client

client = Client()
client.login("username", "password")
res = client.fbsearch_suggested_profiles(1234567890)
print(res)
```

Traceback:

```
Traceback (most recent call last):
  File "C:\Users\marco\AppData\Roaming\Python\Python39\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Program Files\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/fbsearch/accounts_recs/?target_user_id=53184308084&include_friendship_status=true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\marco\AppData\Roaming\Python\Python39\site-packages\instagrapi\import instagrapi.py", line 6, in <module>      
    res = client.fbsearch_suggested_profiles(53184308084)
  File "C:\Users\marco\AppData\Roaming\Python\Python39\site-packages\instagrapi\mixins\fbsearch.py", line 72, in fbsearch_suggested_profiles
    result = self.private_request("fbsearch/accounts_recs/", params=params)
  File "C:\Users\marco\AppData\Roaming\Python\Python39\site-packages\instagrapi\mixins\private.py", line 445, in private_request
    raise e
  File "C:\Users\marco\AppData\Roaming\Python\Python39\site-packages\instagrapi\mixins\private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\marco\AppData\Roaming\Python\Python39\site-packages\instagrapi\mixins\private.py", line 354, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: Not eligible for chaining.
```
The function used to work until about two-three weeks ago, although I never updated instagrapi.
Any solutions available?

**Comment by LosevMikhail** [comment]
Any updates yet??

**Comment by subzeroid** [comment]
This is now covered by the new suggested-profiles helper released in `instagrapi 2.9.1`:

- PR: https://github.com/subzeroid/instagrapi/pull/2613
- Release: https://github.com/subzeroid/instagrapi/releases/tag/2.9.1
- PyPI: https://pypi.org/project/instagrapi/2.9.1/

The old `fbsearch_suggested_profiles()` endpoint can still be rejected by Instagram with `Not eligible for chaining`; the supported replacement is:

```python
cl.user_suggested_profiles(user_id)
cl.user_suggested_profiles(user_id, expand_suggestion=True)
```

Before release I checked it against the live API: default chaining returned suggested users and expanded mode returned suggestion detail items.

Upgrade with:

```bash
pip install -U instagrapi==2.9.1
```

Closing this as addressed by the new helper. If the new method fails for a specific target/account pair, please open a fresh issue with the exact response payload/status so it can be triaged separately.

**Comment by subzeroid** [comment]
Closed as addressed by instagrapi 2.9.1 / PR #2613.
