### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Progaming19199** [adw0rd/instagrapi#923]
Keep getting this issue when starting my script. Does anyone know what it is can't seem to figure it out

Traceback (most recent call last):
  File "C:\Users\Tristan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Users\Tristan\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/2935911135938461440_4366149739/like/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tristan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 434, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\Tristan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 330, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tristan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Users\Tristan\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/2935911135938461440_4366149739/like/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tristan\Desktop\Personal\projects\Instagrapi\main.py", line 32, in <module>
    cl.media_like(media.id)
  File "C:\Users\Tristan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\media.py", line 416, in media_like
    result = self.private_request(
  File "C:\Users\Tristan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 451, in private_request
    return self._send_private_request(endpoint, **kwargs)
  File "C:\Users\Tristan\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 330, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

**Comment by josemmc95** [comment]
Same problem here. 

Trying to login with 2FA and I get an HTML response instead of a JSON.

**Comment by FranciscoDadone** [comment]
Same problem

**Comment by Cyclone5** [comment]
same problem.

**Comment by adw0rd** [comment]
Submit your improvements as PR

**Comment by florifull** [comment]
Same problem

**Comment by romanrsr** [comment]
+1

**Comment by subzeroid** [comment]
Closing this old support thread as Instagram account/session/rate-limit enforcement rather than a specific instagrapi defect.

These states are usually account, proxy, device, session, action-pattern, or server-side trust decisions. The current guidance is documented here:

- https://subzeroid.github.io/instagrapi/usage-guide/best-practices
- https://subzeroid.github.io/instagrapi/usage-guide/handle_exception
- https://subzeroid.github.io/instagrapi/usage-guide/interactions

If a current release returns a new structured response that should be mapped to a typed exception, please open a fresh focused issue with sanitized `last_json` and the exact method call.
