### ISSUE TITLE
[BUG] instagrapi library is broken.

### ISSUE THREAD

**Issue by ghuser9822** [adw0rd/instagrapi#933]
**It is not working at all.**

```
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 434, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 330, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\All Codes\instatweet.py", line 126, in <module>
    asyncio.run(main())
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Lenovo\Desktop\All Codes\instatweet.py", line 70, in main
    upload_post_photo(jpg_name,captions)
  File "C:\Users\Lenovo\Desktop\All Codes\instatweet.py", line 34, in upload_post_photo
    cl.login(IG_USERNAME, IG_PASSWORD)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\auth.py", line 391, in login
    logged = self.private_request("accounts/login/", data, login=True)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 445, in private_request
    self.challenge_resolve(self.last_json)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\challenge.py", line 78, in challenge_resolve
    return self.challenge_resolve_simple(challenge_url)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\challenge.py", line 425, in challenge_resolve_simple
    raise ChallengeUnknownStep(f'ChallengeResolve: Unknown step_name "{step_name}" for "{self.username}" in challenge resolver: {self.last_json}')
instagrapi.exceptions.ChallengeUnknownStep: ChallengeResolve: Unknown step_name "select_contact_point_recovery" for "xxxxxxx" in challenge resolver: 
```

**Comment by therealbdawg** [comment]
no issues been running my bot the last 10 hours

**Comment by zepvalue** [comment]
challenges should be handles differently. I would suggest to first log in on a mobile phone and then use the bot. `challenge_required` it's a n MFA code or simply changing the password will help bypass https://adw0rd.github.io/instagrapi/usage-guide/challenge_resolver.html

Please read the readme before posting in issues

**Comment by ghuser9822** [comment]
I found few pointers. This issue is because of gmail not letting other apps login. 

https://stackoverflow.com/a/25447206

Still unable to find solution. How you guys resolving it ?

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com

**Comment by subzeroid** [comment]
Closing this old generic challenge thread as covered by the active challenge tracking issue: https://github.com/subzeroid/instagrapi/issues/1041

The actionable path is to continue there with current instagrapi versions and sanitized current `last_json` / challenge step data. Gmail IMAP credential failures are local email-provider configuration, not an instagrapi defect.
