### ISSUE TITLE
Status 429: Too many requests

### ISSUE THREAD

**Issue by itsManeka** [adw0rd/instagrapi#934]
### I'm getting error 429 when I try to login.

I've tried on a server with different IP and the same error occurs.
I also tried on a different account. Same error.
Could anyone explain the reason for the error?

Two days ago it was working without problems.

Here's the trace:

```
Status 429: Too many requests
Traceback (most recent call last):
  File "C:\Users\u0180947\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Users\u0180947\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://i.instagram.com/api/v1/feed/reels_tray/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "b:\Dev\VsCode\instagram-heroku-test\src\python\instagram.py", line 140, in <module>
    main()
  File "b:\Dev\VsCode\instagram-heroku-test\src\python\instagram.py", line 130, in main
    result = login()
  File "b:\Dev\VsCode\instagram-heroku-test\src\python\instagram.py", line 45, in login
    cl.login(IG_USERNAME, IG_PASSWORD)
  File "C:\Users\u0180947\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instagrapi\mixins\auth.py", line 418, in login
    self.login_flow()
  File "C:\Users\u0180947\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instagrapi\mixins\auth.py", line 167, in login_flow
    check_flow.append(self.get_reels_tray_feed("cold_start"))
  File "C:\Users\u0180947\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instagrapi\mixins\auth.py", line 244, in get_reels_tray_feed
    return self.private_request("feed/reels_tray/", data)
  File "C:\Users\u0180947\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instagrapi\mixins\private.py", line 447, in private_request
    raise e
  File "C:\Users\u0180947\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instagrapi\mixins\private.py", line 434, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\u0180947\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instagrapi\mixins\private.py", line 365, in _send_private_request
    raise PleaseWaitFewMinutes(e, response=e.response, **last_json)
instagrapi.exceptions.PleaseWaitFewMinutes: Please wait a few minutes before you try again.

**Comment by EdenEitani** [comment]
I have the same error. too many requests on login. my account was suspended on first try

**Comment by itsManeka** [comment]
That's it, my account was temporarily blocked on Saturday. I got it back, but with the consequence of having limited requisitions.

I stopped using the API and a short time later it started working properly again. Of course, it's not an API problem, but a control of Instagram itself.

Using the API is a risk on your own, as Instagram does not allow this type of automation.
For now I'm going to keep this feature disabled in my app and later I'm going to make a better control with longer intervals between one post and another.

If anyone has a better idea of ​​how to escape instagram blocks and wants to contribute, feel free!

P.S.: I indicated that I had the same error with a different account, but I think I was wrong in that statement.
I just changed the value of the login variables, but as in the code I had the control with credentials.json, I believe the app accessed the same account as before.

**Comment by kikawo** [comment]
I have same error. too So there is no way but just waiting some days until instagram release API access?

**Comment by itsManeka** [comment]
> Reference in new iss

Yes, in my case it happened that way.
So I disabled the function until my instagram access goes back to normal (I tested this through the app) and later I enabled the function again.
The error did not happen again.
