### ISSUE TITLE
[BUG]I got this massive HTTPS error today after everything was working fine just a few hours earlier. I haven't changed a thinng.

### ISSUE THREAD

**Issue by grasshaussoftware** [adw0rd/instagrapi#935]
### Compensate with donations ($15 and more) for the time I spent to fix problems or send me your [Pull Request](https://github.com/adw0rd/instagrapi/pulls) with fixes

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

* Tron TRX/USDT: `TLprxuzHjXPkHYa7ZfTTt165p7Fphwy1Ee`
* Bitcoin: `bc1qmp7538hktvg2gx994hrpkmsmyjc03q29awe9ra`
* Ethereum: `0x0E674815d513d4a00F6a7Cd4A990807aB97cC70D`
* Dogecoin: `DSEXzMBYhBTwhNqzPGxVWFsTqVsTCeDejo`

**Describe the bug**
when i was running my script earlier today after finishing it up, i had no problem. then this evening i went to run it again and it gave me the error below. i hadn't changed a thing with the code at all.

**To Reproduce**
simply run this code in the command line
```
import random
from time import sleep
from instagrapi import Client
from cred import *

client = Client()

class StartupRoutine:
    def __init__(self, welcome, insta_username, insta_password, tfa, hashtag, caption, pause):
        self.welcome = welcome
        self.insta_username = insta_username
        self.insta_password = insta_password
        self.tfa = tfa
        self.hashtag = hashtag
        self.caption = caption
        self.pause = pause

startUp = StartupRoutine(print("Instagrapi Bot v.0.0.1 by deusopus@gmail.com"), insta_username, insta_password, input("Enter your 2FA code: "), random.choice(hashtags), random.choice(captions), random.randrange(2400, 4800))

startUp.welcome
startUp.tfa

client.login(startUp.insta_username, startUp.insta_password, verification_code=startUp.tfa)

posts = client.hashtag_medias_recent(startUp.hashtag)

for i, media in enumerate(posts):
        
        client.media_like(media.id)
        print(f"Liked post {i+1} with #{startUp.hashtag} by @{media.user.username}")
        wait = startUp.pause
        print(f"Sleeping for {wait} seconds")
        sleep(wait)
        
        if i % 5 == 0 and i % 3 == 0:
            
            client.user_follow(media.user.pk)
            print(f"Followed @{media.user.username}")
            wait = startUp.pause
            print(f"Sleeping for {wait} seconds")
            sleep(wait)

            caption = startUp.caption
            client.media_comment(media.id,caption)
            print(f"Commented with: {caption} on post {i+1}")
            wait = startUp.pause
            print(f"Sleeping for {wait} seconds")
            sleep(wait)
```

**Traceback**
Traceback (most recent call last):
  File "/home/deusopus/Documents/code/insta/insta-bot-0.0.1.py", line 3, in <module>
    from instagrapi import Client
  File "/usr/local/lib/python3.10/dist-packages/instagrapi/__init__.py", line 4, in <module>
    import requests
  File "/usr/local/lib/python3.10/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 11, in <module>
    from . import exceptions
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 3, in <module>
    from six.moves.http_client import IncompleteRead as httplib_IncompleteRead
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "/usr/lib/python3/dist-packages/six.py", line 196, in find_spec
    return spec_from_loader(fullname, self)
  File "<frozen importlib._bootstrap>", line 437, in spec_from_loader
  File "/usr/lib/python3/dist-packages/six.py", line 226, in is_package
    return hasattr(self.__get_module(fullname), "__path__")
  File "/usr/lib/python3/dist-packages/six.py", line 123, in __getattr__
    _module = self._resolve()
  File "/usr/lib/python3/dist-packages/six.py", line 120, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3/dist-packages/six.py", line 87, in _import_module
    __import__(name)
  File "/usr/lib/python3.10/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.10/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.10/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.10/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/usr/lib/python3.10/email/utils.py", line 29, in <module>
    import socket
  File "/home/deusopus/Documents/code/insta/socket.py", line 2, in <module>
    HTTPConnection.default_socket_options + [
NameError: name 'HTTPConnection' is not defined
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 21, in <module>
    from urllib.request import urlopen
  File "/usr/lib/python3.10/urllib/request.py", line 88, in <module>
    import http.client
  File "/usr/lib/python3.10/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.10/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.10/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.10/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/usr/lib/python3.10/email/utils.py", line 29, in <module>
    import socket
  File "/home/deusopus/Documents/code/insta/socket.py", line 2, in <module>
    HTTPConnection.default_socket_options + [
NameError: name 'HTTPConnection' is not defined

Original exception was:
Traceback (most recent call last):
  File "/home/deusopus/Documents/code/insta/insta-bot-0.0.1.py", line 3, in <module>
    from instagrapi import Client
  File "/usr/local/lib/python3.10/dist-packages/instagrapi/__init__.py", line 4, in <module>
    import requests
  File "/usr/local/lib/python3.10/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 11, in <module>
    from . import exceptions
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 3, in <module>
    from six.moves.http_client import IncompleteRead as httplib_IncompleteRead
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "/usr/lib/python3/dist-packages/six.py", line 196, in find_spec
    return spec_from_loader(fullname, self)
  File "<frozen importlib._bootstrap>", line 437, in spec_from_loader
  File "/usr/lib/python3/dist-packages/six.py", line 226, in is_package
    return hasattr(self.__get_module(fullname), "__path__")
  File "/usr/lib/python3/dist-packages/six.py", line 123, in __getattr__
    _module = self._resolve()
  File "/usr/lib/python3/dist-packages/six.py", line 120, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3/dist-packages/six.py", line 87, in _import_module
    __import__(name)
  File "/usr/lib/python3.10/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.10/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.10/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.10/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/usr/lib/python3.10/email/utils.py", line 29, in <module>
    import socket
  File "/home/deusopus/Documents/code/insta/socket.py", line 2, in <module>
    HTTPConnection.default_socket_options + [
NameError: name 'HTTPConnection' is not defined

**Expected behavior**
It was working just fine earlier today and I got this from my script
```
deusopus@deusopus-ubuntu-egypt:~/Documents/code/insta$ python3 insta-bot-0.0.2.py 
Enter your 2FA code: 000000
Instagrapi Bot v.0.0.1 by deusopus@gmail.com
Liked post 1 with #420 by @the_good_hi
Sleeping for 2722 seconds
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Python version 3.10
 - instagrapi version not sure
 - moveipy version if used
 - imagemagick version if used

**Additional context**

**Comment by Anurag-Varma** [comment]
try to do this:

```
pip uninstall urllib3

pip install urllib3
```

**Comment by subzeroid** [comment]
Closing as a local environment/import-shadowing problem, not an instagrapi bug.

The traceback shows Python importing `/home/deusopus/Documents/code/insta/socket.py`, which shadows the standard-library `socket` module. Rename or remove that local file, clear any cached bytecode, and rerun from a clean virtual environment.
