### ISSUE TITLE
Would not login to instagram (if even used for the first time) error

### ISSUE THREAD

**Issue by JawkeRz** [adw0rd/instagrapi#94]
So I've been getting this error while trying to run this on mac (not sure if it has something to do with it):
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 205, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 432, in main
    insta_bot.login(settings['insta_username'], settings['insta_password'])
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/auth.py", line 342, in login
    if self.private_request("accounts/login/", data, login=True):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 338, in private_request
    raise e
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 325, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 245, in _send_private_request
    raise SentryBlock(**last_json)
instagrapi.exceptions.SentryBlock: Sorry, there was a problem with your request.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 205, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 463, in <module>
    main()
  File "main.py", line 434, in main
    insta_bot.relogin()
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/auth.py", line 357, in relogin
    return self.login(self.username, self.password, relogin=True)
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/auth.py", line 342, in login
    if self.private_request("accounts/login/", data, login=True):
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 338, in private_request
    raise e
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 325, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/instagrapi/mixins/private.py", line 245, in _send_private_request
    raise SentryBlock(**last_json)
instagrapi.exceptions.SentryBlock: Sorry, there was a problem with your request.
```

**Comment by adw0rd** [comment]
@JawkeRz Instagram didn't like your IP, SentryBlock is IP blocking
