### ISSUE TITLE
[BUG] - unable to download all media saved in a private collection

### ISSUE THREAD

**Issue by khaledhawari** [adw0rd/instagrapi#972]
**Describe the bug**
using instagrapi to download all media saved inside a collection., getting few errors while running the script and it does not download all the media saved in a target collection. I already authenticate with user and pass.

Collection has 1135 items, i only get to download around 40 or 50 of them

**To Reproduce**
i can provide the script

**Traceback**
ChallengeResolve: Unknown step_name "submit_phone" for "badr.hosn@gmail.com" in challenge resolver: {'step_name': 'submit_phone', 'step_data': {'phone_number': '+96170102802'}, 'flow_render_type': 3, 'bloks_action': 'com.instagram.challenge.navigation.take_challenge', 'cni': 18328386472007759, 'challenge_context': '{"step_name": "submit_phone", "cni": 18328386472007759, "is_stateless": false, "challenge_type_enum": "SMS", "present_as_modal": false}', 'challenge_type_enum_str': 'SMS', 'status': 'ok'}
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/collection/17934019033848343/?include_igtv_preview=false&max_id=QVFESmt5NTM2RlJhM2Y2MmRpR3pqbE40MUpxdXRfMHRXZENwM0pveGdHQ2ZQYzBscjRUcTF5OEFyWF9ZbVgtVVVDcHhrR2djanp3dTZRS0hvdXBYM2hRVg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagrapi/mixins/private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagrapi/mixins/private.py", line 330, in _send_private_request
    raise ChallengeRequired(**last_json)
instagrapi.exceptions.ChallengeRequired: challenge_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagrapi/mixins/collection.py", line 132, in collection_medias
    params={"include_igtv_preview": "false", "max_id": next_max_id},
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagrapi/mixins/private.py", line 443, in private_request
    self.challenge_resolve(self.last_json)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagrapi/mixins/challenge.py", line 78, in challenge_resolve
    return self.challenge_resolve_simple(challenge_url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagrapi/mixins/challenge.py", line 425, in challenge_resolve_simple
    raise ChallengeUnknownStep(f'ChallengeResolve: Unknown step_name "{step_name}" for "{self.username}" in challenge resolver: {self.last_json}')
instagrapi.exceptions.ChallengeUnknownStep: ChallengeResolve: Unknown step_name "submit_phone" for "badr.hosn@gmail.com" in challenge resolver: {'step_name': 'submit_phone', 'step_data': {'phone_number': '+96170102802'}, 'flow_render_type': 3, 'bloks_action': 'com.instagram.challenge.navigation.take_challenge', 'cni': 18328386472007759, 'challenge_context': '{"step_name": "submit_phone", "cni": 18328386472007759, "is_stateless": false, "challenge_type_enum": "SMS", "present_as_modal": false}', 'challenge_type_enum_str': 'SMS', 'status': 'ok'}

**Expected behavior**
Should be able to download all media from target collection (images, videos, reels, stories, albums, IGTV clips)

**Desktop (please complete the following information):**
 - OS: MAC OS X 13.0
 - Python version 3.6.5
 - instagrapi version 1.16.20

**Comment by subzeroid** [comment]
Fixed in instagrapi 2.10.6: https://github.com/subzeroid/instagrapi/releases/tag/2.10.6

Root cause on the library side was collection pagination: some Instagram collection responses can return the next cursor as `max_id` instead of `next_max_id`. The sync client only read `next_max_id`, so `collection_medias(...)` could stop after an early page for saved/private collections.

The fix is in https://github.com/subzeroid/instagrapi/pull/2650: `collections()` and `collection_medias_v1_chunk(...)` now accept either cursor field, with regression coverage for collection listing, low-level chunks, and high-level pagination.

The async mirror baseline/coverage is released as aiograpi 1.4.6: https://github.com/subzeroid/aiograpi/releases/tag/1.4.6

A live authenticated saved-posts smoke test also passed. The available test-account pool did not contain a prepared multi-page private collection, so the exact `max_id` fallback is covered by deterministic regression tests.
