### ISSUE TITLE
401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by Yan19960220** [adw0rd/instagrapi#987]
### Compensate with donations ($15 and more) for the time I spent to fix problems or send me your [Pull Request](https://github.com/adw0rd/instagrapi/pulls) with fixes

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

* Tron TRX/USDT: `TLprxuzHjXPkHYa7ZfTTt165p7Fphwy1Ee`
* Bitcoin: `bc1qmp7538hktvg2gx994hrpkmsmyjc03q29awe9ra`
* Ethereum: `0x0E674815d513d4a00F6a7Cd4A990807aB97cC70D`
* Dogecoin: `DSEXzMBYhBTwhNqzPGxVWFsTqVsTCeDejo`

**Describe the bug**

**To Reproduce**
Provide a piece of code to reproduce the problem.
When I tried to get the following/follower list for the account (id: 4265355), it also triggered the error Login_required. 

**Traceback**
Show your full traceback so that it is clear where exactly the error occurred.
4265355
Traceback (most recent call last):
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/public.py", line 130, in _send_public_request
    response.raise_for_status()
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.instagram.com/graphql/query/?variables=%7B%22id%22%3A%224265355%22%2C%22include_reel%22%3Atrue%2C%22fetch_mutual%22%3Afalse%2C%22first%22%3A12%2C%22after%22%3A%22QVFDWnl4TE1razFKWnp4QzZPYmxfUTQ2d3cteUNaZF82azFqdl9MZGJ2YlNacFVqU1ZUQU5LNkxBbE1qcGtUWWNfa2M4TkZrdDF2eU1sNk5LQ3pGOG1XQg%3D%3D%22%7D&query_hash=5aefa9893005572d237da5068082d8d5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/user.py", line 754, in user_followers
    users = self.user_followers_gql(user_id, amount)
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/user.py", line 663, in user_followers_gql
    users, _ = self.user_followers_gql_chunk(str(user_id), amount)
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/user.py", line 631, in user_followers_gql_chunk
    data = self.public_graphql_request(
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/public.py", line 210, in public_graphql_request
    body_json = self.public_request(
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/public.py", line 91, in public_request
    raise e
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/public.py", line 74, in public_request
    return self._send_public_request(url, **kwargs)
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/public.py", line 163, in _send_public_request
    raise ClientError(e, response=e.response)
instagrapi.exceptions.ClientError: 401 Client Error: Unauthorized for url: https://www.instagram.com/graphql/query/?variables=%7B%22id%22%3A%224265355%22%2C%22include_reel%22%3Atrue%2C%22fetch_mutual%22%3Afalse%2C%22first%22%3A12%2C%22after%22%3A%22QVFDWnl4TE1razFKWnp4QzZPYmxfUTQ2d3cteUNaZF82azFqdl9MZGJ2YlNacFVqU1ZUQU5LNkxBbE1qcGtUWWNfa2M4TkZrdDF2eU1sNk5LQ3pGOG1XQg%3D%3D%22%7D&query_hash=5aefa9893005572d237da5068082d8d5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/friendships/4265355/followers/?max_id=&count=10000&rank_token=2234892702_bb7163d8-6630-4b5f-a55f-47e4293043ea&search_surface=follow_list_page&query=&enable_groups=true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yanzhang/Projects/work/ins/ins/main.py", line 47, in <module>
    user = User(login, username)
  File "/Users/yanzhang/Projects/work/ins/ins/models/user.py", line 17, in __init__
    self.user_profile = self.get_user_info(user_name, amount=50) if user_name is not None else UserProfile()
  File "/Users/yanzhang/Projects/work/ins/ins/models/user.py", line 71, in get_user_info
    user_pro.followers = self.get_followers(user_pro.user_id, amount=amount)
  File "/Users/yanzhang/Projects/work/ins/ins/models/user.py", line 43, in get_followers
    return list(self.cl.user_followers(user_id).keys())
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/user.py", line 758, in user_followers
    users = self.user_followers_v1(user_id, amount)
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/user.py", line 725, in user_followers_v1
    users, _ = self.user_followers_v1_chunk(str(user_id), amount)
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/user.py", line 690, in user_followers_v1_chunk
    result = self.private_request(f"friendships/{user_id}/followers/", params={
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 447, in private_request
    raise e
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 434, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/Users/yanzhang/miniforge3/envs/myenv/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 323, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required

**Expected behavior**
I want to get the following/follower list

**Desktop (please complete the following information):**
 - OS: [macOS ventura]
 - Python version [3.8]
 - instagrapi version [e.g. 1.16.3]

**Additional context**

**Comment by adw0rd** [comment]
You need to log in, as it is written in the traceback
